### ISSUE TITLE
What's the idea behind planCost being 'varchar' in SQL?

### ISSUE THREAD

**Issue by Strykar** [lirantal/daloradius#10]
Why 128 characters for currency? Besides 'decimal' taking less storage space in what appears to be a decimal only situation, wouldn't this create sanitation issues?
`planCost                     | varchar(128) | YES  |     | NULL`

**Comment by lirantal** [comment]
You're right and it's an old codebase that I haven't updated, and didn't give much respect when creating the schema back then.
