### ISSUE TITLE
daloRADIUS setup on ubuntu server 18.04

### ISSUE THREAD

**Issue by sstmtech** [lirantal/daloradius#100]
Hello Team, 
I'm new to daloRADIUS server, I came accross chillispot and daloRADIUS , while I was searching for open source system to manage my LAN user internet usage . I followed some steps to installed it on ubuntu server 18.04. but I don't know to configure it to manage the users internet data usage. when I run a test, this is the message I received.

xecuted:
echo User-Name='test',User-Password='test' | radclient -c '1' -n '3' -r '3' -t '3' -x '127.0.0.1:1812' 'auth' 'testing123' 2>&1

Results:
(0) No reply from server for ID 110 socket 3
Sent Access-Request Id 110 from 0.0.0.0:36860 to 127.0.0.1:1812 length 44
User-Name = "test"
User-Password = "test"
Cleartext-Password = "test"
Sent Access-Request Id 110 from 0.0.0.0:36860 to 127.0.0.1:1812 length 44
User-Name = "test"
User-Password = "test"
Cleartext-Password = "test"
Sent Access-Request Id 110 from 0.0.0.0:36860 to 127.0.0.1:1812 length 44
User-Name = "test"
User-Password = "test"
Cleartext-Password = "test"

I will be grateful for any support.

**Comment by lirantal** [comment]
Hi,

Please open an issue at https://github.com/lirantal/daloradius/


--
Sincerely, Liran Tal
GitHub <https://github.com/lirantal>, Twitter
<https://twitter.com/liran_tal>, Medium <https://medium.com/@liran.tal>

**Comment by sstmtech** [comment]
Okay

**Comment by MiguelVis** [comment]
duplicated with #101
