### ISSUE TITLE
daloradius setup

### ISSUE THREAD

**Issue by sstmtech** [lirantal/daloradius#101]
Hello Team,
I'm new to daloRADIUS server, I came accross chillispot and daloRADIUS , while I was searching for open source system to manage my LAN user internet usage . I followed some steps to installed it on ubuntu server 18.04. but I don't know to configure it to manage the users internet data usage. when I run a test, this is the message I received.

xecuted:
echo User-Name='test',User-Password='test' | radclient -c '1' -n '3' -r '3' -t '3' -x '127.0.0.1:1812' 'auth' 'testing123' 2>&1

Results:
(0) No reply from server for ID 110 socket 3
Sent Access-Request Id 110 from 0.0.0.0:36860 to 127.0.0.1:1812 length 44
User-Name = "test"
User-Password = "test"
Cleartext-Password = "test"
Sent Access-Request Id 110 from 0.0.0.0:36860 to 127.0.0.1:1812 length 44
User-Name = "test"
User-Password = "test"
Cleartext-Password = "test"
Sent Access-Request Id 110 from 0.0.0.0:36860 to 127.0.0.1:1812 length 44
User-Name = "test"
User-Password = "test"
Cleartext-Password = "test"

I will be grateful for any support.

**Comment by MiguelVis** [comment]
Hi @sstmtech .

I assume you are referring to the option `Config > Test User Connectivity`.

The error you mentioned in the issue comes from the `radclient` utility from FreeRADIUS server, not daloRADIUS:

> (0) No reply from server for ID 110 socket 3

More info in [FreeRADIUS documentation](https://wiki.freeradius.org/config/Radclient).

I suggest to you doing the following steps:

1. Check the FreeRADIUS server is running in your system.
2. Check the FreeRADIUS server configuration is right.
3. Check the daloRADIUS configuration related to `radclient` is right - file `daloradius.conf.php`, fields:
```
$configValues['CONFIG_MAINT_TEST_USER_RADIUSSERVER'] = '127.0.0.1';
$configValues['CONFIG_MAINT_TEST_USER_RADIUSPORT'] = '1812';
$configValues['CONFIG_MAINT_TEST_USER_NASPORT'] = '0';
$configValues['CONFIG_MAINT_TEST_USER_RADIUSSECRET'] = 'testing123';
```

**Comment by sstmtech** [comment]
freeradius.service - LSB: Radius Daemon
   Loaded: loaded (/etc/init.d/freeradius; generated)
   Active: inactive (dead)
     Docs: man:systemd-sysv-generator(8)

Apr 19 13:19:20 nocsrv freeradius[1755]: rlm_sql (sql): Initialising connection pool
Apr 19 13:19:20 nocsrv freeradius[1755]: Ignoring "ldap" (see raddb/mods-available/README.rst)
Apr 19 13:19:20 nocsrv freeradius[1755]:  # Skipping contents of 'if' as it is always 'false' -- /etc/freeradius/3.0/sites-e
Apr 19 13:19:20 nocsrv freeradius[1755]: radiusd: #### Skipping IP addresses and Ports ####
Apr 19 13:19:20 nocsrv freeradius[1755]: Configuration appears to be OK
Apr 19 13:19:20 nocsrv freeradius[1755]: rlm_sql (sql): Removing connection pool
Apr 19 13:19:20 nocsrv systemd[1]: freeradius.service: Control process exited, code=exited status=1
Apr 19 13:19:20 nocsrv systemd[1]: freeradius.service: Failed with result 'exit-code'.
Apr 19 13:19:20 nocsrv systemd[1]: Failed to start FreeRADIUS multi-protocol policy server.
Apr 19 13:19:23 nocsrv systemd[1]: Stopped FreeRADIUS multi-protocol policy server.
~

**Comment by MiguelVis** [comment]
Hi @sstmtech 

It seems your FreeRADIUS configuration is wrong.

What version number of FreeRADIUS have you installed?

**Comment by sstmtech** [comment]
I installed v3 as shown below
root@nocsrv:~# freeradius -v
radiusd: FreeRADIUS Version 3.0.16, for host x86_64-pc-linux-gnu, built on May  5 2018 at 05:00:18
FreeRADIUS Version 3.0.16
Copyright (C) 1999-2017 The FreeRADIUS server project and contributors
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE
You may redistribute copies of FreeRADIUS under the terms of the
GNU General Public License
For more information about these matters, see the file named COPYRIGHT

**Comment by MiguelVis** [comment]
But what about your FreeRADIUS configuration? Have you defined a NAS, a profile and a test user? FreeRADIUS 3 configuration is very different compared to the previous v2.

**Comment by sstmtech** [comment]
Okay, I'm still learning more about it on  how to install and configure it
on Ubuntu server. I have created a test account on the FreeRADIUS.

**Comment by sstmtech** [comment]
> But what about your FreeRADIUS configuration? Have you defined a NAS, a profile and a test user? FreeRADIUS 3 configuration is very different compared to the previous v2.

Hello MiguelVis,
What must I do to get the Freeradius up and running. The NAS is my Router right?

**Comment by MiguelVis** [comment]
> What must I do to get the Freeradius up and running. The NAS is my Router right?

Right.

Take into account that whenever you add a nas or modify any nas configuration, you must restart the FreeRADIUS service, in order to take effect.

**Comment by MiguelVis** [comment]
Duplicated with #105

**Comment by sstmtech** [comment]
> Duplicated with #105

Hello MiguelVis,
I have configured my NAS but when try to browse, I don't see any prompt for username and password. 
I will be grateful if you could assist me to figure out what is wrong with my configuration. I can I can browse internet without any authentication.

This is my Network Connection:
ISP>>>>>>Ciscso Router>>>>>>>>Cisco Switch>>>>>>OLT.

I have configure the router on /16 network.
