### ISSUE TITLE
Change Mysql DB Port

### ISSUE THREAD

**Issue by antoniovalenzuela** [lirantal/daloradius#102]
Please help

I should change the MySQL default port in daloradius.conf.php

configValues ['CONFIG_DB_PORT'] = 'xxxx';

Enter any port other than 3306 or blank and by default it always assumes 3306.

Where can I force the connection to another port?

**Comment by lirantal** [comment]
Do you mean if you specify a port for that config then it's not used?

**Comment by antoniovalenzuela** [comment]
That's right, it does not use the configuration port (in the example xxxx). You can write any port and it will always connect to 3306

configValues ['CONFIG_DB_PORT'] = 'xxxx';

**Comment by antoniovalenzuela** [comment]
port 0 or any number and connects ok!

![Sin título](https://user-images.githubusercontent.com/28113584/56818613-fe350400-6815-11e9-9fb7-0b5cc6671cdc.jpg)

**Comment by antoniovalenzuela** [comment]
![Sin título](https://user-images.githubusercontent.com/28113584/56818691-2cb2df00-6816-11e9-92e0-12d8a8bbd930.jpg)
Port 0 or any number and connects to default 3306

**Comment by lirantal** [comment]
Port 0 or empty will default to 3306 but anything else you put should be used.
I do see it being used here: https://github.com/lirantal/daloradius/blob/918b128e9b0fc4fc82d652c4808fd4f3ae420d23/library/opendb.php#L76 to connect

**Comment by antoniovalenzuela** [comment]
0 is an example. 1234, 8888, 9876, etc
any port does not assume it 

You could change it from opendb.php

**Comment by MiguelVis** [comment]
@antoniovalenzuela you are using daloRADIUS v0.9-9.

Try to download the master branch from GitHub (future v1.0-1 or so), and check if the error persists.

I have checked the `opendb.php` file mentioned by @lirantal and I don't see anything wrong with the code.

**Comment by antoniovalenzuela** [comment]
change all port 3306 on file opendb.php

Error Message: DB Error: connect failed

**Comment by antoniovalenzuela** [comment]
Is there another file that has port 3306 hard?

**Comment by MiguelVis** [comment]
Don't do that. Just update daloRADIUS from master branch and try again.

**Comment by antoniovalenzuela** [comment]
Tested lastest version, same issue

Default mysql 3306 OK

mysql on another port  Error Message: DB Error: connect failed. Port modified on both files.

**Comment by MiguelVis** [comment]
Check the port issue on your MySQL configuration side.

**Comment by antoniovalenzuela** [comment]
New port works on musql.

Freeradius and others apps php connected, except daloradius.

**Comment by antoniovalenzuela** [comment]
they can try in their same environments

**Comment by antoniovalenzuela** [comment]
I think it's a directive that predominates in php-mysql

**Comment by antoniovalenzuela** [comment]
I clarify that the connection 3306 is localhost

The new port is an SSH-Mysql tunnel also in localhost

**Comment by antoniovalenzuela** [comment]
I solved it.

replacing localhost to 127.0.0.1. With the IP address the port change works.

Then with locahost it automatically takes the port configured in mysql.

![Sin título](https://user-images.githubusercontent.com/28113584/56826312-ea939880-6829-11e9-8af1-ee0c67b2773c.jpg)

**Comment by lirantal** [comment]
Happy to hear.
Maybe due to a configuration within your MySQL permissions

**Comment by antoniovalenzuela** [comment]
> Happy to hear.
> Maybe due to a configuration within your MySQL permissions

Info web php (mysql_connect)
Whenever you specify "localhost" or "localhost:port" as server, the MySQL client library will override this and try to connect to a local socket (named pipe on Windows). If you want to use TCP/IP, use "127.0.0.1" instead of "localhost". If the MySQL client library tries to connect to the wrong local socket, you should set the correct path as in your PHP configuration and leave the server field blank.

**Comment by lirantal** [comment]
Sounds good, thanks for the update @antoniovalenzuela 👍
