### ISSUE TITLE
daloradius server

### ISSUE THREAD

**Issue by sstmtech** [lirantal/daloradius#105]
Hello Team,
I have managed to re-installed daloradius server again on my ubuntu 16.04 server but I can't login with from the web. when I type administrator and radius as username and password respectively nothing shows. I will appreciate any support to resolve this isssue.

:~# /etc/init.d/freeradius status
● freeradius.service - LSB: Radius Daemon
   Loaded: loaded (/etc/init.d/freeradius; bad; vendor preset: enabled)
   Active: active (running) since Tue 2019-05-07 10:55:57 GMT; 35min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1201 ExecStart=/etc/init.d/freeradius start (code=exited, status=0/SUCCESS)
    Tasks: 6
   Memory: 8.9M
      CPU: 188ms
   CGroup: /system.slice/freeradius.service
           └─1242 /usr/sbin/freeradius

May 07 10:55:57 ITGUY systemd[1]: Starting LSB: Radius Daemon...
May 07 10:55:57 ITGUY freeradius[1201]:  * Starting FreeRADIUS daemon freeradius
May 07 10:55:57 ITGUY freeradius[1201]:    ...done.
May 07 10:55:57 ITGUY systemd[1]: Started LSB: Radius Daemon.
root@ITGUY:~# /etc/init.d/freeradius stop
[ ok ] Stopping freeradius (via systemctl): freeradius.service.
root@ITGUY:~# /etc/init.d/freeradius restart
[ ok ] Restarting freeradius (via systemctl): freeradius.service.
root@ITGUY:~# radtest sqltest testpwd localhost 18128 testing123
Sending Access-Request of id 83 to 127.0.0.1 port 1812
	User-Name = "sqltest"
	User-Password = "testpwd"
	NAS-IP-Address = 127.0.1.1
	NAS-Port = 18128
	Message-Authenticator = 0x00000000000000000000000000000000
rad_recv: Access-Accept packet from host 127.0.0.1 port 1812, id=83, length=20

**Comment by MiguelVis** [comment]
@sstmtech have you inserted the daloRADIUS database setup located at `/contrib/db/mysql-daloradius.sql` into the FreeRADIUS database?

It contains the creation scripts for the daloRADIUS tables and the initial data for them - ie:

```
INSERT INTO `operators` VALUES (6,'administrator','radius','','','','','','','','','','','','','2009-12-07 20:13:20','2009-12-07 20:12:33','admin','2009-12-07 20:14:01','administrator');
```

**Comment by sstmtech** [comment]
yes, I did insert.

Thanks

**Comment by MiguelVis** [comment]
Hi @sstmtech.

It seems daloRADIUS can't access the database.

Check you have PEAR:DB installed and the MySQL configuration parameters in daloRADIUS are correct.

**Comment by sstmtech** [comment]
I have completed all those configuration.

**Comment by sstmtech** [comment]
Okay. Will you be kind to help me and guide with steps to reinstall system.

Thanks

**Comment by MiguelVis** [comment]
Ok. I will try to help you. Sorry if I ask you something obvious to you.

If we come back to your initial question:

> ...but I can't login with from the web. when I type administrator and radius as username and password respectively nothing shows. 

What means 

> nothing shows

exactly?

And, can you check if the MySql service is running in your system? - as root, something like:

`service mysqld status`

And finally, have you modified the file `library/daloradius.conf.php` to fit your FreeRadius version and MySQL configuration? - default values are:

```
$configValues['FREERADIUS_VERSION'] = '2';
$configValues['CONFIG_DB_ENGINE'] = 'mysqli';
$configValues['CONFIG_DB_HOST'] = 'localhost';
$configValues['CONFIG_DB_PORT'] = '3306';
$configValues['CONFIG_DB_USER'] = 'root';
$configValues['CONFIG_DB_PASS'] = '';
$configValues['CONFIG_DB_NAME'] = 'radius';
```

I assume you have reinstalled the last daloRADIUS version hosted in GitHub from master branch:

`$configValues['DALORADIUS_VERSION'] = '1.0-1';`

**Comment by sstmtech** [comment]
Dear Miguel,
I can now login to the system with administrator and radius as username and
password. I have also created another another for testing and it worked.

what I am looking for now is how to set traffic quota for each user like
10G for 30 Days.


Hope to hear from you soon.

**Comment by MiguelVis** [comment]
Hi @sstmtech 

You can do this in several ways, but the exact details depend on your router trademark / model.

In both cases, when creating and editing users, you can set individual attributes for them, or, even better, assing them one or more groups (profiles):

```
Management > New User > Account Info > Group
Management > New User > Attributes

Management > Edit User > Groups
Management > Edit User > Attributes
```

If, as me, you prefer the Group (profile) option, you can manage them in:

`Management > Profiles`

By using groups / profiles, you can preset some attributes under a name, and assign them to new / existent users.

For example, if you use Mikrotik routes, you could create a profile like this:

```
Name: "10G - 30 days"
Vendor (Mikrotik) Attributes: Mikrotik-Recv-Limit and Mikrotik-Xmit-Limit
Attribute: Session-Timeout
```

Another interesting attribute to add could be `Mikrotik-Rate-Limit`.

You can find more information about Mikrotik and Radius in:

[Mikrotik Manual, Radius Client section](https://wiki.mikrotik.com/wiki/Manual:RADIUS_Client)

Hope it helps.

**Comment by sstmtech** [comment]
Many thanks for your reply Miguel,
I really appreciate the support you have offered to me so far. I have
created the group profile on my freeradius server but I am not using
Mikrotik.
I am using Cisco router 1841 instead.Can I run the command below on my
router to sync the radius-server and the router NAS?

#configure terminal
#aaa new-model
#radius-server host 192.x.x.x
#radius-server key XXXX

Hope to hear from you again.
