### ISSUE TITLE
DaloRadius Network configuration not synchronize

### ISSUE THREAD

**Issue by sstmtech** [lirantal/daloradius#108]
Hello Team,
I have a network layout connection like:
ISP>>>>>>>Cisco Router>>>>>>>Cisco Switch>>>>>>OLT. The Router is configured 192.160.0.0/16.
I can browse through this setup. 
I want to be able to manage the user monthly data quota and also want the users to be authenticate by username and password. 

Thanks

**Comment by MiguelVis** [comment]
You need a RADIUS server (ie FreeRADIUS) and a management tool like daloRADIUS.

**Comment by sstmtech** [comment]
I have Radius server and the management tool  daloradius installed. what
next must i do?

Thanks

**Comment by sstmtech** [comment]
> You need a RADIUS server (ie FreeRADIUS) and a management tool like daloRADIUS.

Hello Miguel, 
what will be my NAS for the integration in this setup ,Cisco Router?

**Comment by kkwised** [comment]
Hello,
@sstmtech , You will have to add a VSA (Vendor Specific Attribute) in your Freeradius configuration.  In this case your want to manage by limiting data quota so tell freeradius what attributes Cisco uses to for limiting data quota.

You can then create a counter with those attributes and use them
