### ISSUE TITLE
 Database import file missing field 数据库丢失一个字段

### ISSUE THREAD

**Issue by willann** [lirantal/daloradius#111]
The radacct data table is missing an acctupdatetime field in contrib/db/fr2-mysql-daloradius-and-freeradius.sql . online users to not display
在contrib/db/fr2-mysql-daloradius-and-freeradius.sql文件的radacct的语句中丢了acctupdatetime字段，导致了在线用户无法显示。

**Comment by tzinmein** [comment]
https://sourceforge.net/p/daloradius/discussion/684102/thread/56b11486/#48ab

**Comment by iamenderst** [comment]
Seeing it with a fresh install and imported DB from daloRAIDUS v0.9-9
`
Thu Jul 28 16:03:31 2022 : ERROR: (866) sql: ERROR: rlm_sql_mysql: ERROR 1054 (Unknown column 'acctupdatetime' in 'field list'): 42S22`
