### ISSUE TITLE
Wont Auth Users with Different Attributes

### ISSUE THREAD

**Issue by bakwenaw** [lirantal/daloradius#114]
@lirantal I want to start by thanking you for this brilliant application and your teams hard work.

No.2 my issue is the following:
I did a fresh install of freeradius 3.0 + daloradius (latest version) +MariaDB 10.13 sql server and everything went smooth. When creating new users(mac auth) with no attributes they are able to auth and use the internet. But once I add any addition attributes(CS-Max-Octects) the auth fails and users cannot login...

Kindly help with regards to this issue or point me to a good direction.. I'm new to the radius thing and daloradius because I've started a WISP but not new to computer or code..

Thanks
Kopano

**Comment by MiguelVis** [comment]
Hi @bakwenaw 

Did you modify the daloRADIUS configuration file `\daloradius\library\daloradius.conf.php` to set freeRadius version variable to "3"?

By default it comes as "2":

`$configValues['FREERADIUS_VERSION'] = '2';`

Regarding the attribute `CS-Max-Octects`, I was not able to find it in the attributes select box in daloRADIUS. There are some `CS-...` attributes, but not this.

What attribute target have you select for it? Check or reply? They are for different purposes.

Anyway, you could start freeRadius in debug mode as explained [here](https://wiki.freeradius.org/guide/radiusd-X) to find out what's happening.

There are even deeper debug modes with -xx if I remember correctly.

Hope it helps.

**Comment by bakwenaw** [comment]
Thanks for the reply @MiguelVis , apologies for not stating the full attribute name, “ CS-Max-Total-Octets” and I use it with the attribute target check. I’ll change the version number as you have indicated in daloradius config file and see how things go. I’ll send feedback once I’ve done so . Thanks

**Comment by bakwenaw** [comment]
@miguelVis I did you advised and still nothing. I'm not even getting any accounting info no matter the mb I download the user use still stays a 0mb. I've tried this attribute    ChilliSpot-Max-Total-Octets with targe "check" and although it authenticates it doesn't limit the user or do any sort of accounting..

**Comment by MiguelVis** [comment]
Hi @bakwenaw.

What router are you using?

I have experience with Mikrotik, and they use specific attributes for that.

**Comment by bakwenaw** [comment]
@MiguelVis thanks for your reply again, yes i'm using a Mikrotik router ;-).. please let me know what atttributes to use... that would be a great help Thanks

**Comment by MiguelVis** [comment]
Hi @bakwenaw 

I leave here two links for your reference:

- [Mikrotik Supported Radius Attributes](https://wiki.mikrotik.com/wiki/Manual:RADIUS_Client#Supported_RADIUS_Attributes)
- [Mikrotik Radius, PPPOE Server and PPPOE Client Setup Guide](https://blog.ibill.io/mikrotik-radius-pppoe-server-setup-guide/)

What you are interested for should be:
`Mikrotik-Recv-Limit`: total receive limit in bytes for the client (**upload** from device!)
`Mikrotik-Xmit-Limit`: total transmit limit in bytes for the client (**download** to device!)

Or may be:
`Mikrotik-Total-Limit:` total transmitted bytes (upload + download), but it's not documented

They are all **reply** attributes.

You could find other interesting attributes for your installation as `Mikrotik-Rate-Limit`.

Hope it helps.

**Comment by bakwenaw** [comment]
@MiguelVis I'll give them all a try and thanks again for your reply and information, you are a great help.
