### ISSUE TITLE
Can I use daloradius with external auth source like rlm_ldap, rlm_rest

### ISSUE THREAD

**Issue by chris-ryu** [lirantal/daloradius#121]
I want to use external auth source like rlm_rest or rlm_ldap with daloradius dashboard functionalities.
Can I use the daloradius with this scenario?
Or, Is there any other suggestion?

**Comment by dmgeurts** [comment]
You closed this request, did you find a solution? I'd like to use LDAP for daloradius administrator authentication rather than use the Radius database for this.

**Comment by lirantal** [comment]
@dmgeurts I think that's going to be a tough one since the daloRADIUS app heavily relies on the database for all the data model. If all of that data exists somewhere else you're going to need to re-write all of those underlying queries.

**Comment by dmgeurts** [comment]
Yeah, I was afraid of that. I'm no coder, so won't tempt fate to try and botch something. If there is such a thing as a feature request list, then I'd love to ask for a means to use something like a 'plugin' model for admin authentication.

The principle I see used elsewhere is that auth is attempted via a plugin and if that succeeds then the user is dynamically added/updated in the app's own database. You just don't store the password, but store users prefs in the normal usual way. So beyond the initial auth, nothing internal to the application changes.

Now, that said, as someone who doesn't code more than a bit of occasional bash, the above sounds simple enough, but I know it's not that easy.

**Comment by lirantal** [comment]
I am no longer actively maintaining daloRADIUS and it has been that way for at least the last 7 years so with that said I'm pretty sure we're not going to see any sort of plugin/feature update like that :)

Sorry, but just keeping your expectations straight.

**Comment by deweydb** [comment]
@lirantal does daloradius have a plugin interface? is there any documentation about it if there is? I would like to create a plugin.

**Comment by lirantal** [comment]
It doesn't but maybe share with us what were you thinking exactly? :)

**Comment by deweydb** [comment]
Sorry I should not have asked in this thread, I will start a new issue.
