### ISSUE TITLE
pfSense config with daloRadius to setup download quota limitation

### ISSUE THREAD

**Issue by Xsmael** [lirantal/daloradius#124]
I have pfsense and daloRadius up and running, I successfully configured radius parameters on pfSense and the NAS on daloRadius and they can talk to each other.

I am able to create users from daloRadius and authenticate them from pfSense.
But when I add some attributes for bandwidth limitation or download quota limitation, authentication fails from pfSense.

Plus in spite of all the search i did, am' not able to understand clearly how radius attributes function:
- Difference between `check` and `reply` and when to use either
- also the operators being used.

Since i didn't understand clearly i tried all combinations that made sense to me but it never worked, I always get `access-reject`.

I added to daloRadius the pfSense radius attribute  dictionary which i got from  [here][1]:

    VENDOR		pfSense				13644
    
    BEGIN-VENDOR	pfSense
    
    ATTRIBUTE	pfSense-Bandwidth-Max-Up		1	integer
    ATTRIBUTE	pfSense-Bandwidth-Max-Down		2	integer
    ATTRIBUTE	pfSense-Max-Total-Octets		3	integer
    
    END-VENDOR pfSense

  [1]: https://github.com/pfsense/pfsense/blob/master/src/usr/share/doc/radius/dictionary.pfsense

but whenever I create a user and try using one of these attributes in either `reply` or `check` attribute, the user is not authorised when logging in, just getting `access-reject` with no explanations.

What am I doing wrong ?

**Comment by MiguelVis** [comment]
Hi @Xsmael 

I suggest to you to start FreeRadius with the -X or -xx options on the command line, to enable debug and see what's going on.

Hope it helps.

**Comment by kkwised** [comment]
Hi,
I agree with @MiguelVis , please run freeradius in debug mode.  You'll definitely see what is causing the access-reject
