### ISSUE TITLE
Fortinet VSA dictionary incomplete

### ISSUE THREAD

**Issue by ccie14140** [lirantal/daloradius#125]
I'm not exactly sure where the vendor VSAs are being retrieved (the Freeradius Fortinet VSA dictionary is correct), but in Dalo, the Fortinet dictionary is incomplete, missing a few definitions.

From Freeradius:
#
#       Fortinet's VSA's
#

VENDOR          Fortinet                        12356

BEGIN-VENDOR    Fortinet
ATTRIBUTE       Fortinet-Group-Name                     1       string
ATTRIBUTE       Fortinet-Client-IP-Address              2       ipaddr
ATTRIBUTE       Fortinet-Vdom-Name                      3       string
ATTRIBUTE       Fortinet-Client-IPv6-Address            4       octets #missing
ATTRIBUTE       Fortinet-Interface-Name                 5       string #missing
ATTRIBUTE       Fortinet-Access-Profile                 6       string #missing

#
# Integer Translations
#

**Comment by lirantal** [comment]
@ccie14140 thanks for raising the issue. there's a table in MySQL that has this information called `dictionary` - https://github.com/lirantal/daloradius/blob/master/contrib/db/mysql-daloradius.sql#L330

Will you be able to create a Pull Request that updates the table in the file according to this new data? you should also apply these changes locally in your DB to see the effect
