### ISSUE TITLE
MULTIPLE MAC ADDRESSES UNDER SAME ACCOUNT IN DALORADIUS

### ISSUE THREAD

**Issue by anthonymukwaya** [lirantal/daloradius#126]
Hi Everyone,

i am trying to create a generic account in daloradius with multiple MAC Addresses. such that we can have several users login with the same username and password but restrict this to the registered MAC Addresses under this account.
I have tried to add multiple "calling-station-id" attributes under the same account and added MAC Addresses but it throws an error of "invalid login credentials" when i try to login with the account.
Please guide me on how i can achieve this.
your guidance is much appreciated.
thank you

**Comment by MiguelVis** [comment]
Hi @anthonymukwaya 

AFAIK you can't do that with daloRADIUS.

**Comment by lirantal** [comment]
I think it's more of a FreeRADIUS SQL check thing.
You could have several entries like that in daloRADIUS, but then you'll need to customize the query that is being made from FreeRADIUS to check if the MAC address is correct to not only get the first one and stop, but retrieve all of the check attributes for the MAC address, go one by one to see if it matches the request, and then allow or deny. It shouldn't be too hard to do in FR.
