### ISSUE TITLE
php7.0+Mysql+daloRadius undefined variable

### ISSUE THREAD

**Issue by torreserne** [lirantal/daloradius#127]
Undefined variable: userTimeLimitGlobal
Undefined variable: userTimeLimitMonthly 
Undefined variable: userTimeLimitWeekly 

I have on my apache´s log this:

Undefined variable: userTimeLimitGlobal on line 225
Undefined variable: userTimeLimitMonthly on line 226
Undefined variable: userTimeLimitWeekly  on line 227
Undefined variable: userTimeLimitDaily on line 228
on file userReports.php and the respective Subscriptcion Analisis, Session Limit don´t show nothing
        	echo "
        		<tr>
        			<td>Session Limit</td>
        			<td>$userTimeLimitGlobal</td>
        			<td>$userTimeLimitMonthly</td>
        			<td>$userTimeLimitWeekly</td>
        			<td>$userTimeLimitDaily</td>
        		</tr>

Thanks.

**Comment by MiguelVis** [comment]
@torreserne, it seems a bug, I'll take a look and revert asap.

**Comment by MiguelVis** [comment]
Fixed with PR #136.

**Comment by MiguelVis** [comment]
Fixed with #138.
