### ISSUE TITLE
Docker build eror , MySQL stopped, Step 12/19

### ISSUE THREAD

**Issue by ashadebi** [lirantal/daloradius#128]
> Step 12/19 : RUN chown -R mysql:mysql /var/lib/mysql /var/run/mysqld; /usr/bin/mysqld_safe &  sleep 10s &&  /usr/bin/mysql --host localhost --port 3306 -u root --password="" -e "CREATE DATABASE radius" &&  /usr/bin/mysql -u root --password="" radius < /var/www/html/contrib/db/fr2-mysql-daloradius-and-freeradius.sql
>  ---> Running in a038e67c53ef
> 2019-10-09T03:11:13.682267Z mysqld_safe Logging to syslog.
**> 2019-10-09T03:11:13.687943Z mysqld_safe Logging to '/var/log/mysql/error.log'.
> 2019-10-09T03:11:13.692621Z mysqld_safe Directory '/var/run/mysqld' for UNIX socket file don't exists.**
> mysql: [Warning] Using a password on the command line interface can be insecure.
> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (20)
> The command '/bin/sh -c chown -R mysql:mysql /var/lib/mysql /var/run/mysqld; /usr/bin/mysqld_safe &  sleep 10s &&  /usr/bin/mysql --host localhost --port 3306 -u root --password="" -e "CREATE DATABASE radius" &&  /usr/bin/mysql -u root --password="" radius < /var/www/html/contrib/db/fr2-mysql-daloradius-and-freeradius.sql' returned a non-zero code: 1

fixed it with add 

> RUN chown www-data.www-data -R /var/www/html && **mkdir -p /var/run/mysqld**

Thanks

**Comment by lirantal** [comment]
thanks I'll update the file ❤️🙏

**Comment by lirantal** [comment]
fixed in https://github.com/lirantal/daloradius/commit/3d89d78ac12c551eae8d4541bb494e8544c7f335
