### ISSUE TITLE
Create releases in GitHub

### ISSUE THREAD

**Issue by frauhottelmann** [lirantal/daloradius#131]
Hi,
can you create releases when you increase your version number? I am pulling Daloradius into my Docker image and pulling a specific version is much easier with a tagged release. Right now I am pulling the v1.1-1 branch, but releases would be neater :wink: 

Thanks

**Comment by lirantal** [comment]
@frauhottelmann yes there we go: https://github.com/lirantal/daloradius/releases/tag/1.1-2
Is this ok?

**Comment by frauhottelmann** [comment]
Yes, perfect. Thank you.

**Comment by lirantal** [comment]
Great. Thanks for pinging me about this!

**Comment by lirantal** [comment]
Great. Thanks for pinging me about this!

**Comment by frauhottelmann** [comment]
Can your make 1.1-3 final and create a release again?

**Comment by lirantal** [comment]
@frauhottelmann a release in github?

**Comment by lirantal** [comment]
there we go: https://github.com/lirantal/daloradius/releases/tag/1.1-3

**Comment by frauhottelmann** [comment]
@lirantal Hey, can you create a new github release with the newest changes?
Thanks

**Comment by lirantal** [comment]
Yep, will work it out in a few hours

**Comment by lirantal** [comment]
There we go, newest release from master branch: https://github.com/lirantal/daloradius/releases/tag/1.1-4
cc @frauhottelmann
