### ISSUE TITLE
Users LogIn always empty

### ISSUE THREAD

**Issue by waver1** [lirantal/daloradius#135]
![Daloradius](https://user-images.githubusercontent.com/58548043/70218013-854e4100-1742-11ea-9397-c2442895e926.JPG)
![Daloradius_logedUsers](https://user-images.githubusercontent.com/58548043/70218015-85e6d780-1742-11ea-9450-d147398a2461.JPG)
![Mikrotik_to_Radius](https://user-images.githubusercontent.com/58548043/70218020-85e6d780-1742-11ea-9567-d4fca6d2c926.JPG)

Hi,

We are testing with "daloRADIUS 1-1-3 BETA" + "Freeradius 3.0" with "MariaDB" on Ubuntu Server 18.04 to check if this solution works fine for us.
At this moment we try with 3 "NAS", 1 NAS works on the same network and works fine, the other two NAS always show "radius timeout" on source (Mikrotik) but on "daloRADIUS" we see "login ok"".
Another question is, on "Graphs"/User LogIns always is empty. We have validated users and working with PPPoE connection but daloRADIUS indicates "0".

Please, we need support with this case, can you say anything?

Thanks,

**Comment by waver1** [comment]
I found an error on networking, This is solved and all clients validate de access but "daloradius" not show  any online users...

**Comment by MiguelVis** [comment]
> I found an error on networking, This is solved and all clients validate de access but "daloradius" not show any online users... Maybe possible "bug" on 1-1-3 BETA?

Hi @waver1.

Is the `radacct` database table populating records with the user accesses?

If not, you have not properly configured Freeradius for accounting into the database.

**Comment by waver1** [comment]
> > I found an error on networking, This is solved and all clients validate de access but "daloradius" not show any online users... Maybe possible "bug" on 1-1-3 BETA?
> 
> Hi @waver1.
> 
> Is the `radacct` database table populating records with the user accesses?
> 
> If not, you have not properly configured Freeradius for accounting into the database.

Yes, i checked "radacct" database table and all seems ok...

![Radacct](https://user-images.githubusercontent.com/58548043/70240118-f3a7f900-176c-11ea-82b6-8714cf12a668.JPG)

Daloradius log show the problem are "radacct"...

![Dalo_Log](https://user-images.githubusercontent.com/58548043/70240230-20f4a700-176d-11ea-843f-30528c4e558f.JPG)


What do you think?

**Comment by MiguelVis** [comment]
Hi @waver1.

With populating the table `radacct`, I mean if there are any records stored in it. Please, check it, because you could have not configured Freeradius 3 properly.

Anyway, by default, daloRadius is configured to work with Freeradius 2, but you are working with Freeradius 3, and there are some differences between its database schemas.

For example, the error you pasted, it shows that field `acctupdatetime` is unknown in the table `radacct` because Freeradius 2 schema does not have it, but Freeradius 3 does.

First of all, be sure that you have changed the value `2` to `3` in the daloRADIUS configuration file located at `\library\daloradius.conf.php`, key `FREERADIUS_VERSION`:

```
$configValues['DALORADIUS_VERSION'] = '1.1-3 BETA';
$configValues['DALORADIUS_DATE'] = '12 Nov 2019';
$configValues['FREERADIUS_VERSION'] = '2';
```

Then, restart and try again.

Looking forward to your comments.

**Comment by waver1** [comment]
> Hi @waver1.
> 
> With populating the table `radacct`, I mean if there are any records stored in it. Please, check it, because you could have not configured Freeradius 3 properly.
> 
> Anyway, by default, daloRadius is configured to work with Freeradius 2, but you are working with Freeradius 3, and there are some differences between its database schemas.
> 
> For example, the error you pasted, it shows that field `acctupdatetime` is unknown in the table `radacct` because Freeradius 2 schema does not have it, but Freeradius 3 does.
> 
> First of all, be sure that you have changed the value `2` to `3` in the daloRADIUS configuration file located at `\library\daloradius.conf.php`, key `FREERADIUS_VERSION`:
> 
> ```
> $configValues['DALORADIUS_VERSION'] = '1.1-3 BETA';
> $configValues['DALORADIUS_DATE'] = '12 Nov 2019';
> $configValues['FREERADIUS_VERSION'] = '2';
> ```
> 
> Then, restart and try again.
> 
> Looking forward to your comments.

Dear @MiguelVis,

First, thanks for your support.

Field "acctupdatetime" is required for "daloradius" and this is present on table "radacct" but you says is unknown in the table, how its possible?

Afte change the version on "daloradius" configuration file the result is the same...

![Dalo_Conf](https://user-images.githubusercontent.com/58548043/70334924-a435fb80-1846-11ea-8436-5fdb841ea433.JPG)

I can try to remove freeradius 3.0 and install 2 but i prefer works with the last version because this is a long term project...

**Comment by MiguelVis** [comment]
Hi @waver1, it seems that your are not alone with that error:

> rlm_sql_mysql: error 1054 (unknown column 'acctupdatetime' in 'field list') 42s22

Some hints:

- [http://freeradius.1045715.n5.nabble.com/quot-acctupdatetime-quot-missing-in-the-radacct-table-accounting-failure-td5754705.html](http://freeradius.1045715.n5.nabble.com/quot-acctupdatetime-quot-missing-in-the-radacct-table-accounting-failure-td5754705.html)
- [https://sourceforge.net/p/daloradius/discussion/684102/thread/56b11486/?limit=25](https://sourceforge.net/p/daloradius/discussion/684102/thread/56b11486/?limit=25)

Please, check if you already have that field in your `radacct` table, or not.

**Comment by MiguelVis** [comment]
Hi @waver1.

Have you solved the issue?

Can we close it?

**Comment by MiguelVis** [comment]
Closed due to thread inactivity.

**Comment by TommasoScardi** [comment]
Hello, I have the same problem with the online user report in daloRadius, i checked and my `radacct` table is empty, even after login a user to the WiFi AP with the its credentials.
Thanks for Any Help !
