### ISSUE TITLE
Database connection error

### ISSUE THREAD

**Issue by dxlvgcw** [lirantal/daloradius#139]
Good day. I am trying to log in my account in http://localhost/daloradius/login.php based on the daloRADIUS Configuration File. Here are the details:
$configValues['CONFIG_DB_ENGINE'] = 'mysqli';
$configValues['CONFIG_DB_HOST'] = 'localhost';
$configValues['CONFIG_DB_PORT'] = '3306';
$configValues['CONFIG_DB_USER'] = 'administrator'; <----------
$configValues['CONFIG_DB_PASS'] = 'radius'; <----------
$configValues['CONFIG_DB_NAME'] = 'radius';

Now when I login the Username as 'administrator' and Password as 'radius', the error shows up like this:
**Database connection error**
**Error Message:** DB Error: connect failed

What seems to be the problem?

**Comment by MiguelVis** [comment]
Hi @dxlvgcw.

You have to set the following configuration variables with the right values to access the database, not daloRADIUS:

```
$configValues['CONFIG_DB_USER'] = 'administrator'; <----------
$configValues['CONFIG_DB_PASS'] = 'radius'; <----------
```
By default, the table `operators` has a record for the user (operator) `administrator` with password `radius` to access the daloRADIUS application.

Hope it helps.

**Comment by dxlvgcw** [comment]
mysql> use radius;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from operators;
+----+---------------+----------+-----------+----------+-------+------------+---------+--------+--------+--------+--------+------------+------------+-------+---------------------+---------------------+------------+---------------------+---------------+
| id | username      | password | firstname | lastname | title | department | company | phone1 | phone2 | email1 | email2 | messenger1 | messenger2 | notes | lastlogin           | creationdate        | creationby | updatedate          | updateby      |
+----+---------------+----------+-----------+----------+-------+------------+---------+--------+--------+--------+--------+------------+------------+-------+---------------------+---------------------+------------+---------------------+---------------+
|  6 | administrator | radius   |           |          |       |            |         |        |        |        |        |            |            |       | 2009-12-07 20:13:20 | 2009-12-07 20:12:33 | admin      | 2009-12-07 20:14:01 | administrator |
+----+---------------+----------+-----------+----------+-------+------------+---------+--------+--------+--------+--------+------------+------------+-------+---------------------+---------------------+------------+---------------------+---------------+
1 row in set (0.00 sec)

Yeah I saw it. I tried accessing my account in the daloRADIUS application with the user (operator) `administrator` with password `radius`. Unfortunately, I'm still receiving the same issue:
**Database connection error**
**Error Message:** DB Error: connect failed

**Comment by dxlvgcw** [comment]
Problem solved. Thanks!
![dalo](https://user-images.githubusercontent.com/49378523/70585089-0a7f9d00-1bfe-11ea-8710-6229289c03a8.png)

**Comment by MiguelVis** [comment]
You're welcome.
