### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by frederikkunze** [lirantal/daloradius#14]
> Database error
> Error Message: DB Error: unknown error
> Debug info: SET GLOBAL sql_mode = ''; [nativecode=1227 *\* Access denied; you need (at least one of) the SUPER privilege(s) for this operation]

I get this with all versions from here and from SF if I use a mysqluser that has no global SUPER privileges.
I wonder why SUPER is needed?

**Comment by lirantal** [comment]
Open the file `library/opendb.php` and remove the last line where it says:
```php
  $dbSocket->query("SET GLOBAL sql_mode = '';");
```

Can you please also let me know which version of MySQL you are running?

**Comment by rrusch** [comment]
You could change the line in `library/opendb.php` to:

`$dbSocket->query("SET SESSION sql_mode = '';");`

If you only change `sql_mode` in the actual session, no additional privileges are needed.

**Comment by lirantal** [comment]
@rrusch awesome, thanks for the input.
Would you like to open a Pull-Request with the change or should I go ahead and commit it? (I'd be happy if you could make the contribution on your own)

**Comment by seanmavley** [comment]
For me, when I faced this issue, all I did was change from the radius user I created for the mysql database to simply `root` so I ended up with this:

`$configValues['CONFIG_DB_USER'] = 'root';`

Or you could assign Super privileges to the Radius database user you created.

**Comment by lirantal** [comment]
Thanks guys! Fixed in https://github.com/lirantal/daloradius/commit/a601ad7e248a934f6e53960813981a361f4563a3

@seanmavley @frederikkunze @rrusch
