### ISSUE TITLE
freeradius 3 and daloradius 1.1.3 online users have no data, all are empty, display 0, will not be updated

### ISSUE THREAD

**Issue by ztaozhang** [lirantal/daloradius#140]
freeradius 3 and daloradius 1.1.3 online users have no data, all are empty, display 0, will not be updated

**Comment by ztaozhang** [comment]
![image](https://user-images.githubusercontent.com/47706186/70990955-89466f80-2101-11ea-84cd-d547070d6010.png)

**Comment by MiguelVis** [comment]
Hi @ztaozhang.

Have you changed the value '2' to '3' in the following configuration variable?

```
$configValues['FREERADIUS_VERSION'] = '2';
```

It's inside the file `/library/daloradius.conf.php`.

Also, check if you have configured Freeradius in order to do accounting into a database, instead of to simple files.

**Comment by ztaozhang** [comment]
$ configValues ​​['FREERADIUS_VERSION'] = '3'; 
can solve the problem? other settings? Need more? I'll test it tomorrow.

**Comment by MiguelVis** [comment]
> $ configValues ​​['FREERADIUS_VERSION'] = '3';
> can solve the problem? other settings? Need more? I'll test it tomorrow.

It could do it.

Again, also, check if your Freeradius configuration is properly set to write accounting into the database.

And I suposse you have merged daloRADIUS DB schema into the Freeradius 3 one.

**Comment by ztaozhang** [comment]
Hello
@MiguelVis 
Thank you! I installed daloradius under freebsd. After the installation is complete, it cannot be displayed with error code 500
DB is installed！

**Comment by MiguelVis** [comment]
> Hello
> @MiguelVis
> Thank you! I installed daloradius under freebsd. After the installation is complete, it cannot be displayed with error code 500
> DB is installed！

Can you paste here the error message from the web server?

It's usually in `\var\log\httpd\error.log` or `error_log` file or similar, depending of your system.

**Comment by ztaozhang** [comment]
Thank you for your help, it is already running, but some functions are not available under bsd, and linux compatibility is good.
Do you develop iptv, do you have a demo management platform or trial version?

**Comment by MiguelVis** [comment]
Hi @ztaozhang.

Ok. Tell us if you need more help.

Regarding off-topic questions (iptv), please, visit my GitHub profile where you will find my website and email addresses.
