### ISSUE TITLE
Upgrade from 0.9-9

### ISSUE THREAD

**Issue by hendrikbl** [lirantal/daloradius#141]
Im currently on version 0.9-9, how can i update to the latest version? Is it enough to just clone this repo and replace my old files? Or are there any database changes required?

I found the update.php file but it looks like it was only used for updates prior to 0.9-9.

**Comment by MiguelVis** [comment]
Hi @hendrikbl.

No database changes are required.

Just update the code and modify the configuration to fit your needs.
