### ISSUE TITLE
daloradius input Chinese, garbled characters are displayed in mysql, the modification of the character set utf8 also does not take effect.

### ISSUE THREAD

**Issue by ztaozhang** [lirantal/daloradius#144]
daloradius input Chinese, garbled characters are displayed in mysql, the modification of the character set utf8 also does not take effect.

**Comment by MiguelVis** [comment]
Hi @ztaozhang.

Any concrete example, please?

**Comment by ztaozhang** [comment]
![image](https://user-images.githubusercontent.com/47706186/71451497-1f3d6280-27b2-11ea-9a50-c4de25fd31c9.png)
![image](https://user-images.githubusercontent.com/47706186/71451502-3da35e00-27b2-11ea-8314-14bf0f0efa23.png)

**Comment by ztaozhang** [comment]
![11](https://user-images.githubusercontent.com/47706186/71451506-6d526600-27b2-11ea-819a-82869d7722de.png)
![22](https://user-images.githubusercontent.com/47706186/71451507-717e8380-27b2-11ea-95ab-fe82ea804025.png)

**Comment by shgyunfei** [comment]
Windows 系统下使用火狐浏览器就不会出现这个问题。国产浏览器绝对是乱码。

**Comment by CN-SaNDuo** [comment]
我有时间在做一份新的daloradius的汉化文件

**Comment by dankey** [comment]
直接中文上了 ：）。
最近也在部署radius.  加个QQ微信聊聊啊。
dolaradius里怎么建不了用户组，是不是哪里设置问题？只有一个daloRADIUS-Disabled-Users。
![image](https://user-images.githubusercontent.com/28786488/76509776-82729300-648b-11ea-95fd-df5841094d56.png)

**Comment by CN-SaNDuo** [comment]
换个ie&nbsp; 试试




三多
吉林省物联星空科技


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"dankey"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月12日(星期四) 晚上6:01
收件人:&nbsp;"lirantal/daloradius"<daloradius@noreply.github.com&gt;;
抄送:&nbsp;"吉祥如意"<1064331064@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [lirantal/daloradius] daloradius input Chinese, garbled characters are displayed in mysql, the modification of the character set utf8 also does not take effect. (#144)





 
直接中文上了 ：）。
 最近也在部署radius.  加个QQ微信聊聊啊。
 dolaradius里怎么建不了用户组，是不是哪里设置问题？只有一个daloRADIUS-Disabled-Users。

**Comment by kratos1995** [comment]
Where is the finished file

**Comment by kratos1995** [comment]
Where is the Chinese document

> 我有时间在做一份新的daloradius的汉化文件

请问做好了吗？
