### ISSUE TITLE
Locate attribute with autocomplete input does not work for add batch user 

### ISSUE THREAD

**Issue by psmit1957** [lirantal/daloradius#145]
I'm using Dalaradius version 1.1-3 BETA / 12 Nov 2019_ on Freeradius 3.05.

I'm trying to create about 125 users via user batch add.
I also need some attributes for dynamic vlan assigment, because i didn't get it to work with a profile, I use the attribute tab in user batch add.

Itried the autocomplete input but nothing happend in the inputfield when i started typing Tunnel.
Entering it myself in this field caused some SQL error (typos?).

The other problem is that the attributes in the profile don't work either. When I define a single user with is own attributes, the dynamic vlan assigment is working fine. But I dont like te enter 125 times a set of attributes.

regards

Piet Smit

**Comment by ozrouter** [comment]
I confirm this. There's something amiss with how attributes are added to the user.
The only way is 1 at a time.

Browser shows this error:
```
mng-batch-add.php:708 Uncaught ReferenceError: autoComEdit is not defined
    at mng-batch-add.php:708
```

**Comment by MiguelVis** [comment]
Hi @psmit1957, @ozrouter.

Fixed custom attributes autocomplete, and group selection (that last one was a global issue!).

I have checked and custom attributes are applied accordingly on each new batch user.

**Comment by ozrouter** [comment]
awesome, thanks.
