### ISSUE TITLE
 Need help in Daloradius

### ISSUE THREAD

**Issue by hackguy2017** [lirantal/daloradius#146]
Dear all please help me i want to apply account expire policy on radius but getting error cant find attriburte of mikrotik

when i apply Access-Period user are not getting login cant find help on web also as all meterial is of radius 2.0

i am using FreeRADIUS Version 3.0.17 and daloradius version 1.1-2

Plesae help

**Comment by MiguelVis** [comment]
Hi @hackguy2017.

I think you are looking for `Session-Timeout` Radius / Mikrotik attribute.

You can learn more about Radius / Mikrotik attributes at:

[https://wiki.mikrotik.com/wiki/Manual:RADIUS_Client](https://wiki.mikrotik.com/wiki/Manual:RADIUS_Client)

Hope it helps.
