### ISSUE TITLE
Suggestion: Plan Information should show Total Data (Upload + Download)

### ISSUE THREAD

**Issue by kkwised** [lirantal/daloradius#147]
Hello, thank you for daloradius.  Currently User Plan information only shows Session Time, Session Upload and Session Download.  Can we have Session Total (Session Upload + Session Download)?

I currently did the following edit in the UserReports.php file
After line 387:     ($planTrafficTotal != 0) ? $trafficTotalDiff = ($planTrafficTotal - ($totalTrafficDown + $totalTrafficUp)) : $trafficTotalDiff = 0;

and after line: 451
 <tr>
					<td>Session Total</td>
					<td>".toxbyte($planTrafficTotal)."</td>
					<td>".toxbyte($totalTrafficDown + $totalTrafficUp)."</td>
					<td>".toxbyte($trafficTotalDiff)."</td>
				</tr> 
<br>
<br>
<img width="688" alt="daloradius session total" src="https://user-images.githubusercontent.com/20517401/72735797-7279b980-3b94-11ea-81cb-a72567aef448.png">

**Comment by MiguelVis** [comment]
Hi @kkwised.

I will check and revert asap.
