### ISSUE TITLE
Batch Add Users won't add group's attributes to user.

### ISSUE THREAD

**Issue by ozrouter** [lirantal/daloradius#151]
On the batch add user page you can select a user group (profile), 

The help tip states:
```
   By assigning a user to a particular group
    the user is subject to the group's attributes
```
The user is in the group but it does not add the attributes to the user.

**Comment by MiguelVis** [comment]
> On the batch add user page you can select a user group (profile),
> 
> The help tip states:
> 
> ```
>    By assigning a user to a particular group
>     the user is subject to the group's attributes
> ```
> 
> The user is in the group but it does not add the attributes to the user.

Hi @ozrouter.

I think this behaviour is correct.

The group attributes affect user, but they are not populated as if they were setted individually to the user.

**Comment by ozrouter** [comment]
oh ok, I see what you mean, thanks.
