### ISSUE TITLE
Next Profile For Expired User

### ISSUE THREAD

**Issue by kraker07** [lirantal/daloradius#153]
Hi,
We would like to use next profile in profile for expired user.Like below;
User X , profile is Std. and exprofile is Disable. , times expired at 01/02/2020 ; query would work at during the auth.
IF user X time is expired when auth. user X should online at Disable profile.

Can anybody hepl us?

**Comment by MiguelVis** [comment]
Hi @kraker07.

I think your question is related to FreeRadius authentication, not something daloRADIUS can deal with, sorry.
