### ISSUE TITLE
FreeRADIUS and Daloradius on CentOS 7

### ISSUE THREAD

**Issue by ayoublab92** [lirantal/daloradius#154]
Hello everyone,

Please I need a help, I have Radius installed on centos 7 server, I want to change the web access password, the default password of interface web management is, Password: radius, I want to change it.

Best Regards,
Ayoub Labidi 
![radius](https://user-images.githubusercontent.com/37629732/74018675-990e6180-4996-11ea-866f-36088c165177.PNG)

**Comment by kkwised** [comment]
Hi,
Default password is "radius"   without the quotes
Please go to your /daloradius/config-operators-list.php
click on the operator (which should be administrator) edit and change the password.

You can also click on the config tab and list operators and edit as you please.

**Comment by ayoublab92** [comment]
Hi , thank you for your reply .  I know that the  default password is "radius" without the quotes, I think in Centos 7 server the php configuration file is under   **/var/www/html/daloradius**

![daloradius](https://user-images.githubusercontent.com/37629732/74514370-b26e5b00-4f0c-11ea-8fe8-63d9c8c539f3.PNG)

**Comment by kkwised** [comment]
Hello, sorry, I meant you have to change it through the web user interface.  

<img width="944" alt="operator" src="https://user-images.githubusercontent.com/20517401/74515674-f4949e00-4f06-11ea-8151-f289a5dcd2be.png">

**Comment by ayoublab92** [comment]
ah okay :)  yES ? , done ! it is so easy. Thanks a lot 

![PPPPP](https://user-images.githubusercontent.com/37629732/74516143-2a8a5000-4f10-11ea-8df1-fa998630dd61.PNG)

**Comment by kkwised** [comment]
You are welcome. I'm happy to help. 😃

**Comment by ayoublab92** [comment]
many thanks

**Comment by ayoublab92** [comment]
Now, I want to secure my Radius server (os: Centos 7 server) by connecting it over HTTPS, do I need to secure Apache web, by generating SSL certificates ??

**Comment by kkwised** [comment]
This can be treated as a new issue.  What do you think?

**Comment by AxeyGabriel** [comment]
Please close this issue

**Comment by baguswahyu** [comment]
> Now, I want to secure my Radius server (os: Centos 7 server) by connecting it over HTTPS, do I need to secure Apache web, by generating SSL certificates ??

just use certbot sir 👍
