### ISSUE TITLE
Dalo won't expire account

### ISSUE THREAD

**Issue by ozrouter** [lirantal/daloradius#155]
Hi all,
I have Daloradius working with pfsense and the pfSense-Max-Total-Octets attribute.

The user is logged out once quota is reached but can immediately log back in.
I have added the pfsense dictionary file. And added a sql-counter to /mods-enabled/sqlcounter

The account terminate cause is NAS-Request.

How do I debug why dalo won't expire the account once limit is reached? It also won't expire upon reaching the max session limit.

**Comment by AxeyGabriel** [comment]
Start by showing us your configuration files..

**Comment by MiguelVis** [comment]
Sorry but that's not a daloRADIUS issue.

Please, check it with the FreeRADIUS project team.
