### ISSUE TITLE
procedure for upgrading from 1.0.0?

### ISSUE THREAD

**Issue by rovewireless** [lirantal/daloradius#156]
Hello!  I tried to upgrade from 1.0.0 to 1.1.3_beta simply by downloading and unzipping files to the same directory.  It looks as though everything for the most part is running normally, except that when I try to run any query on the 'Management' tab (e.g. List Users, Search Users) I don't receive any results.  No error message either, just a blank table.

Oddly enough, clicking list users still shows there are 16 pages of users to display, but none are populated in the table.  Any ideas?

**Comment by rovewireless** [comment]
🙄 

Turns out I wiped the userinfo table by running this in addition:

mysql -uradiusmaster -ptkTFUSmY radius < /var/www/html/daloradius/contrib/db/mysql-daloradius.sql;

Upgrade seems to have worked fine by simply overwriting the daloradius directory with new files and updating ./library/daloradius.conf.php with correct mysql db user/pass.

**Comment by lirantal** [comment]
@rovewireless sorry to hear that, hope you had a backup 🙏

**Comment by rovewireless** [comment]
> @rovewireless sorry to hear that, hope you had a backup 🙏

Yes, took one right before attempting the upgrade, all is good.  😌

**Comment by lirantal** [comment]
Glad to hear ❤️
