### ISSUE TITLE
User id increment

### ISSUE THREAD

**Issue by abstract-arrow** [lirantal/daloradius#157]
Hi, 
It's been a couple of days since I've been using daloRADIUS and I noticed user ids increment by three.
My database user ids look like:
1 - 3 - 6 - 9 -... instead of 1 - 2 - 3 - 4 -...
Is it intentional or am I missing something, and is there any way to fix this?

**Comment by AxeyGabriel** [comment]
The auto increment value is set on your database configuration file. it isn't anything related to daloradius
