### ISSUE TITLE
Mikrotik Rate-Limit Attribute

### ISSUE THREAD

**Issue by sbnetworks** [lirantal/daloradius#158]
Hi All
![dalo 1](https://user-images.githubusercontent.com/63587653/79120122-5dc35100-7d92-11ea-8650-3f486f43cfa6.JPG)
![dalo 2](https://user-images.githubusercontent.com/63587653/79120127-61ef6e80-7d92-11ea-9adc-1861d9563cc0.JPG)
![dalo 3](https://user-images.githubusercontent.com/63587653/79120128-63209b80-7d92-11ea-8852-f2a158483bfd.JPG)

I trust you are well.
I have been using daloRADIUS for about 12 months now, it has been hosted by a company who set everything up for me initially, I was always able to create and edit my own profiles to set user rate limits and it would then write the queues to my Mikrotik Routers.
I have now decided to host the application myself by using the virual application.
However, now when I set the reply attributes on my profiles, using Rate-Limit (as per screenshot), I get errors on the Radius Log (Screenshot).
Could you please assist and or advice how I can rectify this. I am relatively inexperienced when it comes to more advanced CLI commands and configurations.
Thanking you in advance

**Comment by AxeyGabriel** [comment]
This is not a daloradius issue
You should read this https://wiki.mikrotik.com/wiki/Manual:RADIUS_Client
You are using Rate-Limit instead of Mikrotik-Rate-Limit

**Comment by AxeyGabriel** [comment]
hint: the portable way to set speed limit is by using Ascend-Data-Rate and Ascend-Xmit-Rate

**Comment by sbnetworks** [comment]
Hey there
Thanks for taking the time to reply to my comment. The reason Rate-Limit (instead of Mikrotik-Rate-Limit) is shown on one of my screenshots, is to show that this is how it is being used on the daloRADIUS deployment that is being hosted for me by a third party

**Comment by om-ganteng** [comment]
> Hey there
> Thanks for taking the time to reply to my comment. The reason Rate-Limit (instead of Mikrotik-Rate-Limit) is shown on one of my screenshots, is to show that this is how it is being used on the daloRADIUS deployment that is being hosted for me by a third party

Did it solve your problem?

**Comment by dimas-renanda** [comment]
i have this problem too any fix ?
