### ISSUE TITLE
Credentials in Clear on Web Interface

### ISSUE THREAD

**Issue by heywoodlh** [lirantal/daloradius#160]
Is there any way for the user credentials to not just be in clear in the web interface?

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/18178614/79793064-840f6080-833f-11ea-8e65-b0fefd3489b6.png">

**Comment by MiguelVis** [comment]
No, the password must be saved in clear in the database due to FreeRADIUS requirements.

**Comment by heywoodlh** [comment]
@MiguelVis is there no way to have it concealed in the web interface while keeping it in clear in the database?

**Comment by wallacemariadeandrade** [comment]
> @MiguelVis is there no way to have it concealed in the web interface while keeping it in clear in the database?

Yes, you just need to update a variable called `$configValues['CONFIG_IFACE_PASSWORD_HIDDEN']` to `yes` in `/var/www/html/library/daloradius.conf.php` file! After that passwords are not shown in users list.
