### ISSUE TITLE
MSSQL DB Failure

### ISSUE THREAD

**Issue by ByronAP** [lirantal/daloradius#162]
OS: Ubuntu 18
Web: Apache2
PHP: 7.2
Radius: Freeradius 3
Error: ```Database connection error Error Message: DB Error: extension not found```
Config: ```$configValues['DALORADIUS_VERSION'] = '1.1-3 BETA';
$configValues['DALORADIUS_DATE'] = '06 Dec 2019';
$configValues['FREERADIUS_VERSION'] = '3';
$configValues['CONFIG_DB_ENGINE'] = 'odbc';
$configValues['CONFIG_DB_HOST'] = 'MSSQLdb';
$configValues['CONFIG_DB_PORT'] = '1433';
$configValues['CONFIG_DB_USER'] = 'redacted';
$configValues['CONFIG_DB_PASS'] = 'redacted';
$configValues['CONFIG_DB_NAME'] = 'radius';```

I have tried changing the db config around to try and use odbc and mssql. Both options cause the same error. I have no issues connecting to the DB from anything else using either dsn or sql cli.

**Comment by MiguelVis** [comment]
I thing the issue is the same as #184.

I think your problem is that you have not installed the following package, as explained in the main README.md file - Requirements section:

> PEAR package DB in order to access the database. To install it, execute at the command line:
> pear install DB

And you have to use the `mysqli` extension.

**Comment by MiguelVis** [comment]
Or maybe the problem is that only `mysqli` engine is accepted.
