### ISSUE TITLE
Daloradius Mac address authentication

### ISSUE THREAD

**Issue by rajaassad** [lirantal/daloradius#166]
Need help, steps to configure the daloradius mac address authentication. I have successfully tested with username and password, but i am facing problem with mac address authentication.

**Comment by ygalmaster** [comment]
There there is a problem when it comes to mac autentication for some reason the web app stores the Mac address as s continuous number string for some reason it removes the colon. one solution to this is going directly to the text file ir to the database and add the columns yourself

**Comment by rajaassad** [comment]
can you send me your email address, i will send screenshot, or you can take remote desktop of my system.

**Comment by ygalmaster** [comment]
rafamizra@gmail.com

**Comment by christianuhlmann** [comment]
please check Issue https://github.com/lirantal/daloradius/issues/191 and Pull Request https://github.com/lirantal/daloradius/pull/164

**Comment by MiguelVis** [comment]
Fixed with #194.
