### ISSUE TITLE
Unexpected logouts when using Cloudflare proxy

### ISSUE THREAD

**Issue by metallicats** [lirantal/daloradius#175]
This issue only happens when the domain is proxied thru Cloudflare on operators that use mobile phones to access the Daloradius portal. It seems like it's logging out when there is a change in the network which happens a lot when on mobile. Anything I can do to about this without exposing the IP of the Daloradius server? I really need the domain proxied to minimize DDoS impact.

TIA.

**Comment by MiguelVis** [comment]
Sorry but this is a question for the FreeRADIUS project team.
