### ISSUE TITLE
Expiration Date Visibility

### ISSUE THREAD

**Issue by prabhakar-khatri** [lirantal/daloradius#176]
Hello,
 
I'm trying to implement daloradius in our ISP replacing DMA radius Manager. Everything is good except the expiration date of the client. Can we look in the admin portal and know the expiration date of the PPPoE monthly client? I have looked for the expiration tag in the database but was not able to find it. 

Thank You!

**Comment by baguswahyu** [comment]
@prabhakar-khatri hii. what freeradius version you use?

**Comment by prabhakar-khatri** [comment]
@baguswahyu hi, the freeradius version is 3.0.13.

**Comment by baguswahyu** [comment]
> @baguswahyu hi, the freeradius version is 3.0.13.

u can use daloradius out of the box without recreate sqlcounter to freeradius 3 format?
i saw the module counter in contrib path is for freeradius 2 only. and it not match with freeradius 3

**Comment by prabhakar-khatri** [comment]
> d it not match with

I implemented it in lab setup. I can downgrade the freeradius version. But, what i want to find is that the expiration date visibility of client in daloradius admin  panel. Is it possible ?

**Comment by baguswahyu** [comment]
> > d it not match with
> 
> I implemented it in lab setup. I can downgrade the freeradius version. But, what i want to find is that the expiration date visibility of client in daloradius admin panel. Is it possible ?

i dont know actually. im still new in daloradius
and i met this version issue
btw,for ubuntu 20
how to install freeradius on it? do u have advise?
i tried add source but not working anymore ☹️

**Comment by prabhakar-khatri** [comment]
> > > d it not match with
> > 
> > 
> > I implemented it in lab setup. I can downgrade the freeradius version. But, what i want to find is that the expiration date visibility of client in daloradius admin panel. Is it possible ?
> 
> i dont know actually. im still new in daloradius
> and i met this version issue
> btw,for ubuntu 20
> how to install freeradius on it? do u have advise?
> i tried add source but not working anymore

I am using Centos 7 for it and trying to build User friendly GUI. I haven't tried it in ubuntu yet.

**Comment by sudanking** [comment]
> Hello,
>  
> I'm trying to implement daloradius in our ISP replacing DMA radius Manager. Everything is good except the expiration date of the client. Can we look in the admin portal and know the expiration date of the PPPoE monthly client? I have looked for the expiration tag in the database but was not able to find it. 
> 
> Thank You!

Can I ask you why you change from DMA? I was planning to purchase it... As an ISP experience, is it not too good?

**Comment by prabhakar-khatri** [comment]
Yes it is good, but in terms of customization its not.
