### ISSUE TITLE
Can someone contribute config for Daloradius with freeradius 3?

### ISSUE THREAD

**Issue by baguswahyu** [lirantal/daloradius#178]
Its seems daloradius not optimize for freeradius 3
Could someone contribute to add config, especially sqlcounter to this repository?
It will be make users could use all available profile attributes easier without converting counter manually to config
thanks!
*sorry im newbie with this radius things and still learning

**Comment by nima2007** [comment]
And also, accounting won't work unless you replace the radacct table with the freeradius3 one as below. 
`CREATE TABLE radacct (
  radacctid bigint(21) NOT NULL auto_increment,
  acctsessionid varchar(64) NOT NULL default '',
  acctuniqueid varchar(32) NOT NULL default '',
  username varchar(64) NOT NULL default '',
  groupname varchar(64) NOT NULL default '',
  realm varchar(64) default '',
  nasipaddress varchar(15) NOT NULL default '',
  nasportid varchar(32) default NULL,
  nasporttype varchar(32) default NULL,
  acctstarttime datetime NULL default NULL,
  acctupdatetime datetime NULL default NULL,
  acctstoptime datetime NULL default NULL,
  acctinterval int(12) default NULL,
  acctsessiontime int(12) unsigned default NULL,
  acctauthentic varchar(32) default NULL,
  connectinfo_start varchar(50) default NULL,
  connectinfo_stop varchar(50) default NULL,
  acctinputoctets bigint(20) default NULL,
  acctoutputoctets bigint(20) default NULL,
  calledstationid varchar(50) NOT NULL default '',
  callingstationid varchar(50) NOT NULL default '',
  acctterminatecause varchar(32) NOT NULL default '',
  servicetype varchar(32) default NULL,
  framedprotocol varchar(32) default NULL,
  framedipaddress varchar(15) NOT NULL default '',
  framedipv6address varchar(45) NOT NULL default '',
  framedipv6prefix varchar(45) NOT NULL default '',
  framedinterfaceid varchar(44) NOT NULL default '',
  delegatedipv6prefix varchar(45) NOT NULL default '',
  PRIMARY KEY (radacctid),
  UNIQUE KEY acctuniqueid (acctuniqueid),
  KEY username (username),
  KEY framedipaddress (framedipaddress),
  KEY framedipv6address (framedipv6address),
  KEY framedipv6prefix (framedipv6prefix),
  KEY framedinterfaceid (framedinterfaceid),
  KEY delegatedipv6prefix (delegatedipv6prefix),
  KEY acctsessionid (acctsessionid),
  KEY acctsessiontime (acctsessiontime),
  KEY acctstarttime (acctstarttime),
  KEY acctinterval (acctinterval),
  KEY acctstoptime (acctstoptime),
  KEY nasipaddress (nasipaddress),
  INDEX bulk_close (acctstoptime, nasipaddress, acctstarttime)
) ENGINE = INNODB;`

**Comment by econst44** [comment]
Newbie here, so pls excuse my noobness. 
@nima2007 , how could I do that, or how to check if my Radacct table is is like that? TIA

**Comment by nima2007** [comment]
No worries. Freeradius3 radacct table has some additional columns like `framedipv6prefix`. My paste above was just taken from the official freeradius3 database setup script to create the table the way freeradius3 likes it. 

You can run this query and check if you have that column:
`select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME='radacct'`

If you don't have that column then you can delete (drop) the table using `DROP TABLE radacct;` and then run my above paste to create it again.

Note all this is only if you want to use accounting. If you just want authorization then you don't have to worry about this.

**Comment by baguswahyu** [comment]
> No worries. Freeradius3 radacct table has some additional columns like `framedipv6prefix`. My paste above was just taken from the official freeradius3 database setup script to create the table the way freeradius3 likes it.
> 
> You can run this query and check if you have that column:
> `select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME='radacct'`
> 
> If you don't have that column then you can delete (drop) the table using `DROP TABLE radacct;` and then run my above paste to create it again.
> 
> Note all this is only if you want to use accounting. If you just want authorization then you don't have to worry about this.

i did this already. im planning to contribute to this repository for freereadius 3 usage
could i have ur email? if possible i want to ask u some questions for Daloradius. i have some issue 😅

**Comment by econst44** [comment]
Ok, I ran the query and determined that my 'radacct' table was not the same as yours, so i dropped the existing table and re-created one using your paste. I now have the updated 'radacct' table. Thanks for your input.

**Comment by econst44** [comment]
Can you please advise why it was important to have the updated table? Operationally I don't see a difference.  I am running Daloradius ver 1.1-3 Beta. How do you make it more real-time, ie, how can I get it to show what is really happening. For example, I have set up a PPPoE server on PfSense and use an external Freeradius  for AAA. There are times that Daloradius doesn't show a client as connected, even-though that client is working normally.

**Comment by sudanking** [comment]
> Can you please advise why it was important to have the updated table? Operationally I don't see a difference.  I am running Daloradius ver 1.1-3 Beta. How do you make it more real-time, ie, how can I get it to show what is really happening. For example, I have set up a PPPoE server on PfSense and use an external Freeradius  for AAA. There are times that Daloradius doesn't show a client as connected, even-though that client is working normally.

Did you checked interim accounting interval value in pfSense?

**Comment by econst44** [comment]
On my PfSense PPPoE Server settings I have Radius Accounting Update set to 300 seconds. What's a good value?

**Comment by sudanking** [comment]
> On my PfSense PPPoE Server settings I have Radius Accounting Update set to 300 seconds. What's a good value?

That means you will get update every 5 min ... It's depends on how large is your network are and how many requests your server could handle.
You can make it every one or two minutes and see.

**Comment by om-ganteng** [comment]
> CREATE TABLE radacct ( radacctid bigint(21) NOT NULL auto_increment, acctsessionid varchar(64) NOT NULL default '', acctuniqueid varchar(32) NOT NULL default '', username varchar(64) NOT NULL default '', groupname varchar(64) NOT NULL default '', realm varchar(64) default '', nasipaddress varchar(15) NOT NULL default '', nasportid varchar(32) default NULL, nasporttype varchar(32) default NULL, acctstarttime datetime NULL default NULL, acctupdatetime datetime NULL default NULL, acctstoptime datetime NULL default NULL, acctinterval int(12) default NULL, acctsessiontime int(12) unsigned default NULL, acctauthentic varchar(32) default NULL, connectinfo_start varchar(50) default NULL, connectinfo_stop varchar(50) default NULL, acctinputoctets bigint(20) default NULL, acctoutputoctets bigint(20) default NULL, calledstationid varchar(50) NOT NULL default '', callingstationid varchar(50) NOT NULL default '', acctterminatecause varchar(32) NOT NULL default '', servicetype varchar(32) default NULL, framedprotocol varchar(32) default NULL, framedipaddress varchar(15) NOT NULL default '', framedipv6address varchar(45) NOT NULL default '', framedipv6prefix varchar(45) NOT NULL default '', framedinterfaceid varchar(44) NOT NULL default '', delegatedipv6prefix varchar(45) NOT NULL default '', PRIMARY KEY (radacctid), UNIQUE KEY acctuniqueid (acctuniqueid), KEY username (username), KEY framedipaddress (framedipaddress), KEY framedipv6address (framedipv6address), KEY framedipv6prefix (framedipv6prefix), KEY framedinterfaceid (framedinterfaceid), KEY delegatedipv6prefix (delegatedipv6prefix), KEY acctsessionid (acctsessionid), KEY acctsessiontime (acctsessiontime), KEY acctstarttime (acctstarttime), KEY acctinterval (acctinterval), KEY acctstoptime (acctstoptime), KEY nasipaddress (nasipaddress), INDEX bulk_close (acctstoptime, nasipaddress, acctstarttime) ) ENGINE = INNODB;

I can confirm that ny radacct table is not the same as yours.

**Comment by si458** [comment]
HELPFUL TIPS FOR ANYBODY RUNNING FREERADIUS 3:

1. install `freeradius` and `freeradius-mysql`
2. import the freeradius scheme into the db `mysql -u radius -p radius < /etc/freeradius/mods-config/sql/main/mysql/schema.sql`
3. import the daloradius scheme into the db `mysql -u radius -p radius < /var/www/html/daloradius/contrib/db/mysql-daloradius.sql`

**!!! DONT IMPORT `fr2-mysql-daloradius-and-freeradius.sql` AS THIS WIPES THE DATABASE CLEAN !!!**

**Comment by lirantal** [comment]
Thanks Simon!

**Comment by lirantal** [comment]
@si458 I'll close up the thread but if you wanted to send in a Pull Request with the relevant docs/guidelinde/updates in the README about setting up for FR3 I'd be happy to merge them!

**Comment by si458** [comment]
thanks @lirantal!
im just trying to put togther a little `quickguide.md` for freeradius3, mariadb, apache, php 7 on ubuntu 20.04
will sent a request when done
in the mean time the is a quide here - https://computingforgeeks.com/how-to-install-freeradius-and-daloradius-on-ubuntu/ but a few bits need to be changed like the line saying add in the fr2 sql file as that wipes clear the existing radius database

**Comment by lirantal** [comment]
Sounds awesome. Thank you Simon! ❤️
