### ISSUE TITLE
PHP Warning:  A non-numeric value encountered in /var/www/html/daloradius/library/checklogin.php on line 30

### ISSUE THREAD

**Issue by WganMe** [lirantal/daloradius#183]
PHP Warning:  A non-numeric value encountered in /var/www/html/daloradius/library/checklogin.php on line 30
PHP Warning:  A non-numeric value encountered in /var/www/html/daloradius/library/checklogin.php on line 31

		(int)$session_valid="yes";
	} else {
		(int)$session_valid="no";
	}

	return (int)$session_valid;
}

**Comment by MiguelVis** [comment]
Hi @WganMe.

I don't know which daloRADIUS version you are running but the current code shows:
```
		$session_valid="yes";
	} else {
		$session_valid="no";
	}

	return $session_valid;
```

Please update your installation from master branch.
