### ISSUE TITLE
Blank screen on login

### ISSUE THREAD

**Issue by bferrell** [lirantal/daloradius#184]
rh-php56 under rh-httpd24

and this is what I see in my error log when trying to login

PHP Fatal error: Class ‘DB’ not found in /home/sites/site00/web/daloradius/library/opendb.php on line 86

**Comment by MiguelVis** [comment]
I think your problem is that you have not installed the following package, as explained in the main README.md file - Requirements section:

> PEAR package DB in order to access the database. To install it, execute at the command line:
> pear install DB

**Comment by bferrell** [comment]
pear install DB
WARNING: "pear/DB" is deprecated in favor of "pear/MDB2"
WARNING: channel "pear.php.net" has updated its protocols, use "pear channel-update pear.php.net" to update
Failed to download pear/PEAR, latest release is version 1.10.0, but it requires PHP version "5.4.0", use "channel://pear.php.net/PEAR-1.10.0" to install
Skipping package "pear/DB", already installed as version 1.9.0
No valid packages found
install failed

**Comment by MiguelVis** [comment]
Hi @bferrell.

Please, check that your `php.ini` has the right setting for the include path, in order to load the `DB.php` library.

This is mine configuration, you must check what is the right path for you:

```
;;;;;;;;;;;;;;;;;;;;;;;;;
; Paths and Directories ;
;;;;;;;;;;;;;;;;;;;;;;;;;

; UNIX: "/path1:/path2"
include_path = \xampp\php\PEAR
```

**Comment by bferrell** [comment]
This simple test finds the module - test.php:

<?php

/**
 * Simple test for PHP5 
 */

phpinfo();

?>

**Comment by MiguelVis** [comment]
Change the `include_once` at line 84 in `library/opendb.php` for `require_once`:

```
include_once ('DB.php');
```
You would see a PHP error if the library is not found.

Anyway, you could check the Apache / PHP for notices and warnings.

If PHP says that DB class is not found, that's a good clue.

**Comment by si458** [comment]
@bferrell are you using an old php version by any chance? i would try php 5.6
` Failed to download pear/PEAR, latest release is version 1.10.0, but it requires PHP version "5.4.0", use "channel://pear.php.net/PEAR-1.10.0" to install`

**Comment by bferrell** [comment]
I actually was using php5.6 but I'll re-check
