### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by PlanetDigitalBS** [lirantal/daloradius#185]
Hello,

i'm new in this Community,....
I get the following Error, if i try to change User Billing Info.

Database error
Error Message: DB Error: syntax error
Debug info: UPDATE userbillinfo SET contactperson='USER', planname='', company='', email='', phone='', paymentmethod='', cash='', creditcardname='', creditcardnumber='', creditcardverification='', creditcardtype='', creditcardexp='', address='', city='', state='', country='', zip='', notes='', changeuserbillinfo='0', lead='', coupon='', ordertaker='', billstatus='', nextinvoicedue='0', billdue='0', postalinvoice='', faxinvoice='', emailinvoice='', updatedate='2020-09-04 08:02:03', updateby='administrator' WHERE username='bs1' [nativecode=1064 ** You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'lead='', coupon='', ordertaker='', billstatus='', nextinvoicedue='0', billdue='0' at line 1]

can anybody help me?

Thanks

**Comment by edimondi** [comment]
@PlanetDigitalBS Delete mysql and install MariaDB, after installing mariadb install again freeradius, i had same issue

**Comment by PlanetDigitalBS** [comment]
thanks edimondi for your advice,...
i tried a newinstall today, with mariadb, but i have the same issues,....
do you have any other ideas?

thanks for help ;-)

**Comment by MiguelVis** [comment]
Hi @PlanetDigitalBS.

Can you run the following SQL query?

```
ALTER TABLE `userbillinfo`
	CHANGE COLUMN `lastbill` `lastbill` DATE NULL DEFAULT NULL AFTER `billstatus`,
	CHANGE COLUMN `nextbill` `nextbill` DATE NULL DEFAULT NULL AFTER `lastbill`;
```

Please let me know if that solves the issue.

**Comment by PlanetDigitalBS** [comment]
Thanks MiguelVis for your help!
I tried a newinstallation b4 you send me this mesage, and int already worked.
So i think i made something wrong on the last installation.

But now i have a different problem -> I can't see the Attributes of the different Vendors, when i'm creating/editing a user.
When I look into the Attributes directly, everything seems to be ok.

Maybe u already know that issue?



![Bildschirmfoto 2021-02-24 um 09 53 35](https://user-images.githubusercontent.com/70692835/108974952-462d4800-7686-11eb-94a6-868af9bf5c87.png)



![Bildschirmfoto 2021-02-24 um 09 52 03](https://user-images.githubusercontent.com/70692835/108974714-023a4300-7686-11eb-9784-e3d14dcc5d29.png)

**Comment by MiguelVis** [comment]
> Thanks MiguelVis for your help!
> I tried a newinstallation b4 you send me this message, and it already worked.
> So i think i made something wrong on the last installation.

Just for the record, what's your database server, MySQL or MariaDB?

> But now i have a different problem -> I can't see the Attributes of the different Vendors, when i'm creating/editing a user.
> When I look into the Attributes directly, everything seems to be ok.
> 
> Maybe u already know that issue?

I can't reproduce the issue.

I think it could be something related to JavaScript and your web browser. So, more details about your environment please.

Could you open the developers options of your web browser and see if something goes wrong when you select the vendor?

**Comment by PlanetDigitalBS** [comment]
I think I have to give some more informations ;-)

I did a newinstallation on a new Server. The new server has now the mariadb installed.
I did a backup on the old server with the mysql db and a recovery on the new server with the mariadb.
And there I can't see the Vendor Attributes.
Maybe it comes from the importing of the old data!?
