### ISSUE TITLE
Unknown Name: access-period

### ISSUE THREAD

**Issue by metallicats** [lirantal/daloradius#186]
I'm getting this error when setting access-period attributes.

sql: ERROR: Failed to create the pair: Unknown name "Access-Period"

Basically I want to disable an account after X amount of days.

**Comment by metallicats** [comment]
I was able to fix this and also make Access-Period work by doing this:

--Add this line in /etc/freeradius/3.0/dictionary --

ATTRIBUTE Access-Period 3003 integer
ATTRIBUTE Expire-After 3004 integer

-- Edit sqlcounter --
nano /etc/freeradius/3.0/mods-available/sqlcounter
-- Add sqlcounter --
sqlcounter accessperiod {
        sql_module_instance = sql
        dialect = ${modules.sql.dialect}

        counter_name = Max-Access-Period-Time
        check_name = Access-Period
        key = User-Name
        reset = never

        $INCLUDE ${modconfdir}/sql/counter/${dialect}/${.:instance}.conf
}

sqlcounter quotalimit {
        sql_module_instance = sql
        dialect = ${modules.sql.dialect}

        counter_name = Max-Volume
        check_name = Max-Data
        reply_name = Mikrotik-Total-Limit
        key = User-Name
        reset = never

        $INCLUDE ${modconfdir}/sql/counter/${dialect}/${.:instance}.conf
}

-- Add Query --
/etc/freeradius/3.0/mods-config/sql/counter/mysql/accessperiod.conf
query = "\
        SELECT UNIX_TIMESTAMP() - UNIX_TIMESTAMP(AcctStartTime) \
        FROM radacct \
        WHERE UserName='%{${key}}' \
        ORDER BY AcctStartTime LIMIT 1"

/etc/freeradius/3.0/mods-config/sql/counter/mysql/quotalimit.conf
query = "\
        SELECT (SUM(acctinputoctets) + SUM(acctoutputoctets)) \
        FROM radacct \
        WHERE UserName='%{${key}}'"

-- Edit Default Sites --
/etc/freeradius/3.0/sites-enabled/default
-- Add authorize --
authorize {
    expiration
    logintime
    quotalimit
    dailycounter
    accessperiod
    monthlycounter
    noresetcounter
}

-- Edit radiusd.conf --
/etc/freeradius/3.0/radiusd.conf
-- Add sqlcounter --
$INCLUDE mods-enabled/
$INCLUDE mods-available/sqlcounter

**Comment by hichkak** [comment]
Hi
I use your instruction with FR 3.0
but I still getting:
rlm_sql (sql): Reserved connection (6)
(1) accessperiod: Executing select query: SELECT UNIX_TIMESTAMP() - UNIX_TIMESTAMP(AcctStartTime) FROM radacct WHERE UserName='test' ORDER BY AcctStartTime LIMIT 1
(1) accessperiod: SQL query returned no results
rlm_sql (sql): Released connection (6)
(1) accessperiod: EXPAND %{sql:SELECT UNIX_TIMESTAMP() - UNIX_TIMESTAMP(AcctStartTime) FROM radacct WHERE UserName='%{User-Name}' ORDER BY AcctStartTime LIMIT 1}
(1) accessperiod:    --> 
(1) accessperiod: No integer found in result string "".  May be first session, setting counter to 0
(1) accessperiod: Allowing user, &control:Access-Period value (30) is greater than counter value (0)
(1) accessperiod: Setting &reply:Session-Timeout value to 30
