### ISSUE TITLE
Warning: preg_split(): Delimiter must not be alphanumeric or backslash in mng-rad-usergroup-del.php on line 47

### ISSUE THREAD

**Issue by om-ganteng** [lirantal/daloradius#187]
the code below caused Warning: preg_split(): message appear on Daloradius UI
list($username, $group) = preg_split('\|\|', $usergroup);
is it because i'm using PHP Version 7.4.10??

**Comment by MiguelVis** [comment]
Hi @om-ganteng.

I think you are referring to the file `mng-rad-usergroup-del.php`, line 47:
`list($username, $group) = preg_split('\|\|', $usergroup);`

Similar code exists in various files.

Can you explain in more detail what's the issue / message reported by your PHP version?

**Comment by wookielinux** [comment]
this is an error in the regex of preg_split 

changing it to   preg_split('/\|\|/', $value);  fixes the issue for me.

**Comment by lirantal** [comment]
@wookielinux that sounds reasonable. Would you like to create a Pull Request with the suggested fix?

**Comment by lirantal** [comment]
Fixed in https://github.com/lirantal/daloradius/commit/0155ca0ee5795a302168d49d214cf614d61c4542
