### ISSUE TITLE
Daloradius user portal db error

### ISSUE THREAD

**Issue by fitriyusuf** [lirantal/daloradius#189]
Hi, i'm new in daloradius. i'm able to login to web through administrator but not able to login to user portal after i enable user 
 portal.

Database connection error
Error Message: DB Error: connect failed
![daloradius-user](https://user-images.githubusercontent.com/73520979/97273223-05572b00-186e-11eb-92f2-b267386f5753.JPG)

**Comment by toehold** [comment]
Check that your mysql user password is the correct in those 2 places:
1. vi /etc/freeradius/3.0/mods-enabled/sql
2. vi /var/www/html/daloradius/library/daloradius.conf.php

**Comment by fitriyusuf** [comment]
but i'm able to login via web administrator ( x.x.x.x/daloradius/index.php)

> Check that your mysql user password is correct in those 2 places: e.g. login: radius; CONFIG_DB_USER=radius
> 
> 1. vi /etc/freeradius/3.0/mods-enabled/sql
> 2. vi /var/www/html/daloradius/library/daloradius.conf.php

but i'm able to login via web administrator ( x.x.x.x/daloradius/index.php)

**Comment by toehold** [comment]
Yes, I was also able to login. Did you check the 2 config files?

**Comment by fitriyusuf** [comment]
> Yes, I was also able to login. Did you check the 2 config files?

yes.. i did check and now i able to login, but when i make change or edit user it will appear error sql
![daloradius](https://user-images.githubusercontent.com/73520979/100408142-4167f080-30a5-11eb-8be7-44cb130b8b33.JPG)

**Comment by fitriyusuf** [comment]
and when i edit user in administrator portal i can save it but i appear sql error
![daloradius-user](https://user-images.githubusercontent.com/73520979/100408249-783e0680-30a5-11eb-9c58-5c97494879dc.JPG)

**Comment by fitriyusuf** [comment]
but when i edit user and save it in administrator portal it will appear error sql
![radius-error](https://user-images.githubusercontent.com/73520979/100408341-b804ee00-30a5-11eb-83fd-4da51e8c2b09.JPG)

**Comment by toehold** [comment]
Seems like a permission problem; check this https://www.howtoforge.com/how-to-install-freeradius-and-daloradius-on-ubuntu-1804/

**Comment by lirantal** [comment]
Indeed, perhaps the user you have set for the database doesn't have permission to make changes to the tables.

**Comment by fitriyusuf** [comment]
> Indeed, perhaps the user you have set for the database doesn't have permission to make changes to the tables.

![radius-error](https://user-images.githubusercontent.com/73520979/100826476-6b4e5800-3495-11eb-88ec-964bfb9fb22e.JPG)


i can edit and save the change that i done but when i safe@apply it will appear error. :(

**Comment by lirantal** [comment]
@fitriyusuf which version of daloRADIUS are you using? did you clone the master branch from this repository or did you download a zip package from somewhere?

Also which version of MySQL are you using?

Actually that error is related to a bad SQL query, so this one specifically doesn't look like permission related.

**Comment by fitriyusuf** [comment]
> @fitriyusuf which version of daloRADIUS are you using? did you clone the master branch from this repository or did you download a zip package from somewhere?
> 
> Also which version of MySQL are you using?
> 
> Actually that error is related to a bad SQL query, so this one specifically doesn't look like permission related.

@lirantal , yes from master branch repo. my daloradius version 1.1-3Beta and MySql version 8.

**Comment by edimondi** [comment]
@fitriyusuf i had same problem with DB Error Syntax so the problem is with mysql so i deleted mysql and installed mariadb and now its working. How did you fix the User Portal because i have same problem Database connection error
Error Message: DB Error: connect failed. This is what i see in log mysql: **[Warning] Access denied for user 'root'@'localhost'** . But dalo web admin is working fine.

**Comment by lirantal** [comment]
@edimondi thanks for the mariadb tip
about the daloradius users portal, try to edit your daloradius.conf.php for that directory of daloradius-users/

**Comment by fitriyusuf** [comment]
> > @fitriyusuf which version of daloRADIUS are you using? did you clone the master branch from this repository or did you download a zip package from somewhere?
> > Also which version of MySQL are you using?
> > Actually that error is related to a bad SQL query, so this one specifically doesn't look like permission related.
> 
> @lirantal , yes from master branch repo. my daloradius version 1.1-3Beta and MySql version 8.

@lirantal so what solution for me and how i overcome the error

**Comment by lirantal** [comment]
@fitriyusuf look at what @edimondi wrote there about using MariaDB instead of MySQL - try that and let me know if it fixed the problem.

**Comment by edimondi** [comment]
@lirantal yes i got it thanks. I have a question when i make invoice i want the expire date for user to change for example from 03 Dec 2020 to 03 Jan 2021. In Attributes i have Expiration but is not changing automatically when making invoices. Thanks

**Comment by lirantal** [comment]
@edimondi I haven't been looking at the code for quite some time so I wouldn't know in advance what and were we need to change things. I suggest taking a look at the *invoice*.php code files as a start.

**Comment by fitriyusuf** [comment]
> @fitriyusuf look at what @edimondi wrote there about using MariaDB instead of MySQL - try that and let me know if it fixed the problem.

@lirantal but my currently daloradius and DB already in used and have data that save in MySQL :( 
So if i uninstall mysql and install mariaDB how about data that already save in mysql

**Comment by edimondi** [comment]
@fitriyusuf Backup the database first 
**mysqldump -uroot -p radius > radius.sql** than you can restore it with **mysql -uroot -p radius < radius.sql**

**Comment by MiguelVis** [comment]
> @edimondi thanks for the mariadb tip
> **about the daloradius users portal, try to edit your daloradius.conf.php for that directory of daloradius-users**/

I believe this the actual solution because there are two daloradius.conf.php files:
- for the administrator panel.
- for the users panel.

and you have to fix your DB credentials in both files.

**Comment by woronti** [comment]
+1

> > @edimondi thanks for the mariadb tip
> > **about the daloradius users portal, try to edit your daloradius.conf.php for that directory of daloradius-users**/
> 
> I believe this the actual solution because there are two daloradius.conf.php files:
> 
>     * for the administrator panel.
> 
>     * for the users panel.
> 
> 
> and you have to fix your DB credentials in both files.

+1

**Comment by home4lab** [comment]
in my case, change db engine from mysql to mysqli solved my issue
/var/www/html/daloradius/library/daloradius.conf.php

    $configValues['CONFIG_DB_ENGINE'] = 'mysqli';
    $configValues['CONFIG_DB_HOST'] = 'localhost';
    $configValues['CONFIG_DB_PORT'] = '3306';

**Comment by Jalmeida27** [comment]
Hello, I have a issue whit the users login in daloradius 2.0 beta. Defaults user and password are administrator / radius, but when I type the user password, I get credentials error and it does not send me to the main page. can you please help me?

**Comment by firdausriawan2** [comment]
> in my case, change db engine from mysql to mysqli solved my issue /var/www/html/daloradius/library/daloradius.conf.php
> 
> ```
> $configValues['CONFIG_DB_ENGINE'] = 'mysqli';
> $configValues['CONFIG_DB_HOST'] = 'localhost';
> $configValues['CONFIG_DB_PORT'] = '3306';
> ```

**LEGIT** u save me bro, thanks :)
