### ISSUE TITLE
MAC Address strip separator 

### ISSUE THREAD

**Issue by christianuhlmann** [lirantal/daloradius#191]
Hello @dcec and @lirantal ,

why is the mac address shortened here (https://github.com/lirantal/daloradius/pull/164)?
so far it has been in the format for me
`ab:12:ab:34:ab:12`
works great.

All MAC addresses are now stored in this format in my DB. freeradius also works perfectly with this format.

In my view, that shouldn't just be changed.
Can you explain why this was changed? Shouldn't that be configurable?

Thanks and Greetings

Christian

_Originally posted by @christianuhlmann in https://github.com/lirantal/daloradius/issues/164#issuecomment-751462641_

**Comment by MiguelVis** [comment]
Closed with #194,
