### ISSUE TITLE
Bulk upload of users to daloRADIUS

### ISSUE THREAD

**Issue by omabiodun** [lirantal/daloradius#195]
Hi everyone, please I have 10,000+ users I need to upload to my daloRadius user manager for hotspot, how can I go about bulk upload. Your responses and guide will be highly appreciated. Thanks.

**Comment by si458** [comment]
the is an import php page which uses CSV format `/daloradius/mng-import-users.php`
so create an excel with col1 as username and col2 as password so `username,password`
save as csv, then open the csv in a text editor, copy and paste the text into the php page and let it add all the info

**Comment by omabiodun** [comment]
Hi Simon,

I'm really happy with this response I will try it out and revert back to
you.

Many thanks.
