### ISSUE TITLE
NAS is not working in docker-compose

### ISSUE THREAD

**Issue by sarunyu** [lirantal/daloradius#196]
> Listening on auth address * port 1812 bound to server default
Listening on acct address * port 1813 bound to server default
Listening on auth address :: port 1812 bound to server default
Listening on acct address :: port 1813 bound to server default
Listening on auth address 127.0.0.1 port 18120 bound to server inner-tunnel
Listening on status address 127.0.0.1 port 18121 bound to server status
Listening on proxy address * port 41571
Listening on proxy address :: port 38523
Ready to process requests
Ignoring request to auth address * port 1812 bound to server default from unknown client 192.168.88.1 port 57259 proto udp
Ready to process requests
Ignoring request to auth address * port 1812 bound to server default from unknown client 192.168.88.1 port 57259 proto udp
Ready to process requests
Ignoring request to auth address * port 1812 bound to server default from unknown client 192.168.88.1 port 57259 proto udp
Ready to process requests
Ignoring request to auth address * port 1812 bound to server default from unknown client 192.168.88.1 port 49524 proto udp
Ready to process requests
Ignoring request to auth address * port 1812 bound to server default from unknown client 192.168.88.1 port 49524 proto udp
Ready to process requests
Ignoring request to auth address * port 1812 bound to server default from unknown client 192.168.88.1 port 49524 proto udp
Ready to process requests
Ignoring request to auth address * port 1812 bound to server default from unknown client 192.168.88.1 port 60909 proto udp
Ready to process requests
Ignoring request to auth address * port 1812 bound to server default from unknown client 192.168.88.1 port 60909 proto udp
Ready to process requests
Ignoring request to auth address * port 1812 bound to server default from unknown client 192.168.88.1 port 60909 proto udp
Ready to process requests

**Comment by si458** [comment]
make sure you have added the NAS client 192.168.88.1 into the NAS section,
then restart the radius server as the NAS data is only read on start-up
