### ISSUE TITLE
Why daloradius works well on Internet Explorer browser only?

### ISSUE THREAD

**Issue by muhandash** [lirantal/daloradius#198]
Hello,

Anyone knows why daloradius works well only on Internet Explorer?
I've tested Chrome, Firewfox, and MS Edge but Javascripts(with ajax) totally don't work such as action triggered by buttons.
e.g. "Disable", "Enable", "Delete", and so on.
My server is RHEL 8 with PHP 8 and Httpd 2.4.

**Comment by MiguelVis** [comment]
Please @muhandash download and install the current master branch.
