### ISSUE TITLE
Users Listing is empty on Ubuntu 14.04

### ISSUE THREAD

**Issue by arve0** [lirantal/daloradius#2]
Hi!
I've installed daloradius on Ubuntu 14.04, and cannot get the users listing to work. It seems like the SQL is working alright, as one can change pages (27 total, see image below). Also, editing a single user works.

![capture](https://cloud.githubusercontent.com/assets/4810521/8165993/1c52d928-1395-11e5-95bf-99f13b4e53c6.PNG)

Any ideas?

**Comment by lirantal** [comment]
Hi,

If you try to add a user from daloRADIUS itself, does it show it to you in
the listing?

On Mon, Jun 15, 2015 at 8:36 PM, Arve Seljebu <notifications@github.com>
wrote:

> Hi!
> I've installed daloradius on Ubuntu 14.04, and cannot get the users
> listing to work. It seems like the SQL is working alright, as one can
> change pages (27 total, see image below). Also, editing a single user works.
>
> [image: capture]
> <https://cloud.githubusercontent.com/assets/4810521/8165993/1c52d928-1395-11e5-95bf-99f13b4e53c6.PNG>
>
> Any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lirantal/daloradius/issues/2>.
>



-- 
--
Sincerely, Liran Tal

Author
<http://www.amazon.com/Agile-Software-Development-HP-Manager/dp/1484210352/>of
Agile Software Development with HP Agile Manager
Founder and Lead Developer of daloRADIUS <http://www.daloradius.com/>
Blogging at http://www.enginx.com, and tweeting at @liran_tal
<https://twitter.com/liran_tal>

**Comment by arve0** [comment]
Thanks for the response, though I've uninstalled dalo as I got dialupadmin working.

**Comment by basicmonkey** [comment]
I'm having this same issue. 3 users on the system but user list is empty. Users were added before Daloradius installation. userinfo table is empty.

Otherwise software working well, thank you!

**Comment by lirantal** [comment]
@basicmonkey that's probably the reason.
It is required for the user account to exist in both userinfo and userbillinfo.
