### ISSUE TITLE
Daloradius Virtual Machine:Login must use encrypted connection

### ISSUE THREAD

**Issue by chenyedzai** [lirantal/daloradius#20]
Hie Lira

I am having this error:Login must use encrypted connection on virtual machine.How can I resolve this error

Thank you in advance

**Comment by lirantal** [comment]
@chenyedzai how about posting some screenshots / logs? so I can better understand the context

**Comment by chenyedzai** [comment]
![encrypted](https://cloud.githubusercontent.com/assets/20473813/20378881/a009c03c-aca1-11e6-90c5-f5dbc4853cd6.JPG)
@lirantal find the attached screenshot

**Comment by lirantal** [comment]
@chenyedzai  Maybe you should be serving that hotspot login page on an HTTPS connection?
