### ISSUE TITLE
Service Status : Radius Disabled ; Mysql	Disabled

### ISSUE THREAD

**Issue by Youness-ezz** [lirantal/daloradius#203]
Hi ;
I'm running daloradius version 1.1-5 in Centos 8 on the same server with freeradius .
authentification is working and all service is UP and running but I have Service Status : Radius: Disabled ; Mysql :Disabled on daloradius dashboard .
Can you help me fix this .

Best Regards.

**Comment by lirantal** [comment]
Perhaps it's not detecting it correctly.
Can you please check out the latest master branch version here and try with that version of daloRADIUS?

**Comment by Youness-ezz** [comment]
Hi Lirantal ;

Yes I will do this and see . Thank's Lirantal !!
Best regards

**Comment by Youness-ezz** [comment]
Hi Lirantal ;
I tried with the latest version but I have the same issue .
Best regards

**Comment by lirantal** [comment]
@Youness-ezz maybe you should confirm if it really isn't running?

This is the command that daloradius uses: https://github.com/lirantal/daloradius/blob/ae34e8c7b05111bd5523385fa9001a084ef12955/library/exten-radius_server_info.php#L27-L36 - you can try running that locally and confirm if it's indeed finding it or not and we can submit a fix if needed.

**Comment by comcduarte** [comment]
I can confirm his findings.  I too am running CentOS 8.3.2011, and radius is running, but daloradius is reporting it disabled.  By just running `pgrep radius` it outputs a PID, but when the entire command is run (as above), it returns nothing.

![image](https://user-images.githubusercontent.com/33262448/123096897-92eb1a80-d3fd-11eb-92b5-6960e4dfd1d2.png)

**Comment by lirantal** [comment]
Thanks @comcduarte, can you run that full command again with the radius service running and also run the command `echo $?` after it? it'll display the returned exit code of the previous command (the pgrep) and that's what the code is checking. Let's see what it returns.

**Comment by comcduarte** [comment]
Seems to be returning a zero.  Also tested known bad response, and confirmed it returns a 1.  Screenshot below

![image](https://user-images.githubusercontent.com/33262448/123122199-cfc20c00-d413-11eb-8b98-0ecb8de73cd3.png)

**Comment by comcduarte** [comment]
Resolved

This is an SELinux issue.  I ran `setenforce 0` and the correct status displayed.  Although during the displaying of the web page, audit log does not show any errors.

**Comment by lirantal** [comment]
Thanks for sharing @comcduarte 🙏🏼 
Nothing is shown in the logs because they're redirected to /dev/null

Is there a different command I can use with SELinux enabled? if so, I'm happy to change to a generic command that works without requiring higher privileges or disabling SELinux.

**Comment by si458** [comment]
im having a similar issue but mine says `Mysql Disabled and `Radius Enabled`
but im using `mariadb` so the `pgrep mysql` wont work, i need to use `pgrep mariadb` instead

**Comment by Youness-ezz** [comment]
> Resolved
> 
> This is an SELinux issue. I ran `setenforce 0` and the correct status displayed. Although during the displaying of the web page, audit log does not show any errors.

I do the same , it solve this issue .
 thank you so much for sharing

**Comment by Xenserve** [comment]
this is happening to me using mariadb on debian bullseye.

**Comment by hashimg74** [comment]
I know these are old but I'm having this issue - mysql shows disabled

**Comment by abd-aityahya** [comment]
Hi, if you still having this issue, you have to change the name of the service "mysql" to "mariadb" in this file:
**line n° 53:**

`sudo nano -l /var/www/html/daloradius/library/exten-radius_server_info.php`

from:

`
     <td class='summaryKey'> MySQL </td>
     <td class='summaryValue'><span class='sleft'><?php echo check_service("mysql");  ?></span> </td>
`

to:

`
     <td class='summaryKey'> MariaDB </td>
     <td class='summaryValue'><span class='sleft'><?php echo check_service("mariadb");  ?></span> </td>
`

**Comment by hashimg74** [comment]
> Hi, if you still having this issue, you have to change the name of the service "mysql" to "mariadb" in this file: **line n° 53:**
> 
> `sudo nano -l /var/www/html/daloradius/library/exten-radius_server_info.php`
> 
> from:
> 
> `<td class='summaryKey'> MySQL </td> <td class='summaryValue'><span class='sleft'><?php echo check_service("mysql"); ?></span> </td>`
> 
> to:
> 
> `<td class='summaryKey'> MariaDB </td> <td class='summaryValue'><span class='sleft'><?php echo check_service("mariadb"); ?></span> </td>`

And this indeed fixed my issue! Thanks!

**Comment by leond08** [comment]
I encountered this error when you use a docker image 
Radius and Mysql are both disabled since all three services are on its own container

**Comment by lirantal** [comment]
Even if they're running on their own containers it should probably work since we're finding them by processes running on the system.
