### ISSUE TITLE
daloradius with Nginx

### ISSUE THREAD

**Issue by seanmavley** [lirantal/daloradius#21]
I run my entire VPS using Nginx. Introducing Apache wouldn't be a flexible addition, at least if it'll be used to run only one and single service.

On that note, is there a way I can have Daloradius work with Nginx? I'll be honest, I've not spotted even a *single* documentation online using Nginx. Everyone is using Apache,

Except this: https://gist.github.com/atmosx/e1949150e74baae0b813 which doesn't help, and only give 502 Gateway error.

- I want the Radius to run on radius.example.com

Below is my current server block in Nginx:

```
server {
    listen 80;

    root /var/www/html/radius;
    index index.php index.html index.htm;

    server_name radius.khophi.co;

    location ~ .*\.php$ {
        # What should I put in here
        # or what shouldn't I?
    }
}
```

Will appreciate help. Thanks

**Comment by lirantal** [comment]
I haven't configured nginx or apache for so long now that I definitely am in no position to code review your config but an easy googling or nginx documentation lookup on how to configure nginx to work with php should do the trick. It should be a really straight-forward setup.

What issues are you actually having? can you share logs or screenshots?

Quickly googling there's this guide from DO: https://www.digitalocean.com/community/tutorials/how-to-install-linux-nginx-mysql-php-lemp-stack-in-ubuntu-16-04
