### ISSUE TITLE
Login page showing Lang Error! since release 1.2

### ISSUE THREAD

**Issue by PDS-GH** [lirantal/daloradius#210]
Since release 1.2, login page is showing 'Lang Error!' at several places. 
Login in is still possible though. However, language option in 'config > language settings' becomes broken.

![image](https://user-images.githubusercontent.com/8920338/132186846-ba54a6b9-1a00-4745-9ac3-f0920c770ac2.png)

**Comment by lirantal** [comment]
Thanks for raising the issue.
Can you confirm you're on "English" for the language? (it looks like but want to make sure)

Also is it a problem only for the login page or others too?

**Comment by PDS-GH** [comment]
Yes I am using english:
```
grep -i lang /var/www/html/daloradius/library/daloradius.conf.php
$configValues['CONFIG_LANG'] = 'en';
```
So far I have only seen the issue on the login page.

**Comment by PDS-GH** [comment]
@lirantal have you been able to look into it?

**Comment by lirantal** [comment]
Sorry, haven't been able to look at it, no.
Are you on the latest version of daloRADIUS from this repository's master branch?

**Comment by MiguelVis** [comment]
The procedure to find the right language file in `lang/main.php` is broken: it always returns an empty array.

So it always includes the English language file "en.php".

The line 41 reads:

```
return !($ext == "php" and is_file("$langDir/$fileName"));
```

It should be:

```
return ($ext == "php" and is_file("$langDir/$fileName"));
```

I will start from here.

**Comment by PDS-GH** [comment]
> Are you on the latest version of daloRADIUS from this repository's master branch?

Version 1.2 and latest master don't make any difference. Lastest working version is 1.1-5

**Comment by MiguelVis** [comment]
Fixed with PR #211.

Full explanation there.

Now it works as expected:

![image](https://user-images.githubusercontent.com/4165032/133502366-039c6bd7-798c-42f2-87e4-13c1c2f1fbfb.png)

**Comment by PDS-GH** [comment]
@MiguelVis thanks for fixing the issue!

**Comment by lirantal** [comment]
Miguel thank you so much for jumping on this.
A life saver every time! 🙏
