### ISSUE TITLE
Docker build problem.

### ISSUE THREAD

**Issue by scarfase** [lirantal/daloradius#212]
Good day. Try to build radius-web with docker-compose and get error.
How can fix that problem?
`Below is a suggested file layout for your new PEAR installation.  To
change individual locations, type the number in front of the
directory.  Type 'all' to change all of them or simply press Enter to
accept these locations.

 1. Installation base ($prefix)                   : /usr
 2. Temporary directory for processing            : /tmp/pear/install
 3. Temporary directory for downloads             : /tmp/pear/install
 4. Binaries directory                            : /usr/bin
 5. PHP code directory ($php_dir)                 : /usr/share/php
 6. Documentation directory                       : /usr/docs
 7. Data directory                                : /usr/data
 8. User-modifiable configuration files directory : /usr/cfg
 9. Public Web Files directory                    : /usr/www
10. System manual pages directory                 : /usr/man
11. Tests directory                               : /usr/tests
12. Name of configuration file                    : /etc/pear.conf

1-12, 'all' or Enter to continue: Beginning install...
Configuration written to /etc/pear.conf...
Initialized registry...
Preparing to install...
installing phar:///go-pear.phar/PEAR/go-pear-tarballs/Archive_Tar-1.4.14.tar...
installing phar:///go-pear.phar/PEAR/go-pear-tarballs/Console_Getopt-1.4.3.tar...
installing phar:///go-pear.phar/PEAR/go-pear-tarballs/PEAR-1.10.13.tar...
installing phar:///go-pear.phar/PEAR/go-pear-tarballs/Structures_Graph-1.1.1.tar...
installing phar:///go-pear.phar/PEAR/go-pear-tarballs/XML_Util-1.4.5.tar...
PHP Fatal error:  Uncaught Error: Call to undefined function _parseFeaturesHeaderFile() in phar:///go-pear.phar/OS/Guess.php:248
Stack trace:
#0 phar:///go-pear.phar/OS/Guess.php(214): OS_Guess->_readGlibCVersionFromFeaturesHeaderFile()
#1 phar:///go-pear.phar/OS/Guess.php(148): OS_Guess->_detectGlibcVersion()
#2 phar:///go-pear.phar/OS/Guess.php(107): OS_Guess->parseSignature()
#3 phar:///go-pear.phar/PEAR/Dependency2.php(109): OS_Guess->__construct()
#4 phar:///go-pear.phar/PEAR/Downloader.php(277): PEAR_Dependency2->__construct()
#5 phar:///go-pear.phar/PEAR/Downloader.php(556): PEAR_Downloader->getDependency2Object()
#6 phar:///go-pear.phar/PEAR/Downloader.php(458): PEAR_Downloader->analyzeDependencies()
#7 phar:///go-pear.phar/PEAR/Command/Install.php(671): PEAR_Downloader->download()
#8 phar:///go-pear.phar/PEAR/Command/Common.php(270): PEAR_Command_Install->doInstall()
#9 phar:///go-pear.phar/PEAR/Start.php(345): PEAR_Command_Common->run()
#10 phar:///go-pear.phar/PEAR/Start/CLI.php(72): PEAR_Start->doInstall()
#11 phar in phar:///go-pear.phar/OS/Guess.php on line 248
The command '/bin/sh -c ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone  && update-ca-certificates -f  && mkdir -p /tmp/pear/cache  && wget http://pear.php.net/go-pear.phar  && php go-pear.phar  && rm go-pear.phar  && pear channel-update pear.php.net  && pear install -a -f DB  && pear install -a -f Mail  && pear install -a -f Mail_Mime' returned a non-zero code: 255`

**Comment by scarfase** [comment]
need install package php-dev

**Comment by lirantal** [comment]
Thank you @scarfase 
I updated the Dockerfile: https://github.com/lirantal/daloradius/commit/a308d09d44b0fd39c7da4ea219db9577750f7561
