### ISSUE TITLE
Realm : pb with the nostrip option 

### ISSUE THREAD

**Issue by Cryptoplax** [lirantal/daloradius#213]
Hello,

I found a problem when using the nostrip option in realm . The file proxy.conf is changed and a line nostrip=1 is added in the realm but  the nostrip option don't need "=1".
So I changed the file saveRealmsProxys.php   : 

the line "if ($row['nostrip']) fwrite($realmsFd, "\tnostrip = " .$row['nostrip']. "\n"); " is replaced by "if ($row['nostrip']) fwrite($realmsFd, "\tnostrip\n");"

Now,  the nostrip option is applied.

Maybe you should update the file for others users.

Regards.

**Comment by lirantal** [comment]
Thanks @Cryptoplax 
Would you like to create a pull request with the change and I'll merge it?
