### ISSUE TITLE
Error " Trying to access array offset on value of type null" while Users Accounting or Date Sort Accounting. 

### ISSUE THREAD

**Issue by CpServiceSpb** [lirantal/daloradius#215]
The error "Trying to access array offset on value of type null" when trying to access Users Accounting or Date Sort Accounting.
Also there is "Trying to access array offset on value of type null" in mng-rad-nas-edit.php.

**Comment by MiguelVis** [comment]
Please @CpServiceSpb check if commit bd898971e9e072462ce4bd1f46ed343d3808984b solves this issue.
