### ISSUE TITLE
Cannot delete ip from pool when in list ippools

### ISSUE THREAD

**Issue by wookielinux** [lirantal/daloradius#218]
There was a bug in list ippools that if you select a ip  or more then click delete it would not see the checked ips and therefore did not delete them..  

I suggest the following code changes that I have working...

in mng-rad-ippool-del.php
------------------------------------------------------------------------------------
replace/change the following 
------------------------------------------------------------------------------------
                foreach ($itemsArray as $value) {

                        list($poolname, $ipaddress) = preg_split('\|\|', $value);

                        if ( (trim($poolname) != "") && (trim($ipaddress) != "") ) {

                                include 'library/opendb.php';

                                $allPoolNames .= $poolname . ", ";
                                $allIPAddresses .= $ipaddress .", ";

                                $sql = "DELETE FROM ".$configValues['CONFIG_DB_TBL_RADIPPOOL']." WHERE ".
                                        " pool_name='".$dbSocket->escapeSimple($poolname)."' AND".
                                        " framedipaddress='".$dbSocket->escapeSimple($ipaddress)."'";
                                $res = $dbSocket->query($sql);
                                $logDebugSQL .= $sql . "\n";

                                $successMsg = "Deleted IP Address <b>$ipaddress</b> for Pool Name <b>$poolname</b> from database";
                                $logAction .= "Successfully deleted IP Address [$ipaddress] for Pool name [$poolname] on page: ";

                                include 'library/closedb.php';

                        }  else {
                                $failureMsg = "No IPAddress/Pool Name was entered, please specify an IPAddress/Pool Name to remove from database";
                                $logAction .= "Failed deleting empty IP Address/Pool Name on page: ";
                        } //if trim

                } //foreach

------------------------------------------------------------------------------------
with the corrected code below
------------------------------------------------------------------------------------

                foreach ($itemsArray as $value) {

                        list($poolnamex, $ipaddress) = preg_split('/\|\|/', $value);

                        if ( (trim($poolnamex) != "") && (trim($ipaddress) != "") ) {

                                include 'library/opendb.php';

                                $allPoolNames .= $poolnamex . ", ";
                                $allIPAddresses .= $ipaddress .", ";

                                $sql = "DELETE FROM ".$configValues['CONFIG_DB_TBL_RADIPPOOL']." WHERE ".
                                        " pool_name='".$dbSocket->escapeSimple($poolnamex)."' AND".
                                        " framedipaddress='".$dbSocket->escapeSimple($ipaddress)."'";
                                $res = $dbSocket->query($sql);
                                $logDebugSQL .= $sql . "\n";

                                $successMsg .= "Deleted IP Address <b>$ipaddress</b> for Pool Name <b>$poolnamex</b> from database <br>";
                                $logAction  .= "Successfully deleted IP Address [$ipaddress] for Pool name [$poolname] on page: ";

                                include 'library/closedb.php';

                        }  else {
                                $failureMsg = "No IPAddress/Pool Name was entered, please specify an IPAddress/Pool Name to remove from database";
                                $logAction .= "Failed deleting empty IP Address/Pool Name on page: ";
                        } //if trim

                } //foreach

**Comment by lirantal** [comment]
Thanks for finding and suggesting a fix @wookielinux 
Would you like to create a Pull Request with the change so I can merge it?

**Comment by wookielinux** [comment]
Sure,    pull request created.

**Comment by lirantal** [comment]
Thank you!
