### ISSUE TITLE
Question: Can Daloradius run on another server to the FreeRADIUS server?

### ISSUE THREAD

**Issue by dmgeurts** [lirantal/daloradius#225]
I guess I'll soon find out, but thought I'd ask if I should expect issues when running daloradius on a separate server to the FreeRADIUS servers? Essentially the MySQL will be hosted on a cluster, which should be fine. But I wonder if not having FreeRADIUS active on the daloradius server will result in some issues. Always helpful to know what to expect, even if the 'issues' may only be cosmetic.

**Comment by dmgeurts** [comment]
So far the issue appears to be with service status and access to FreeRADIUS logs. I guess the assumption is that daloradius runs on a single FreeRADIUS server. When in fact the implementation may see multiple Radius servers deployed all using the same database (synced, or through a remote MySQL connection).

**Comment by lirantal** [comment]
Yes, definitely. The only you need for daloRADIUS is the MySQL database access.
In fact, I think that the Dockerfile in this repository might be a good example of how to separate the dalorADIUS web app from the database and from the freeradius server.

**Comment by lirantal** [comment]
The only thing that would probably not work for you is the "status" page that shows if FreeRADIUS / MySQL are up and running (since it runs a command on the OS to find the processes, which it won't find)

**Comment by dmgeurts** [comment]
Thank you, it's working great so far.

**Comment by lirantal** [comment]
Happy to hear!
