### ISSUE TITLE
Daloradius attribute issue: sql: Failed to create the pair: Unknown name

### ISSUE THREAD

**Issue by chase200199** [lirantal/daloradius#232]
Dear All:

I followed steps in the link below to build a freeradius with daloradius on my CentOS 8 VM: https://computingforgeeks.com/install-freeradius-and-daloradius-on-centos-rhel-8/

On daloradius, I created a new vendor and a new attrinute as below: 
![new_vendor_attribute](https://user-images.githubusercontent.com/14155576/156513287-b197a921-f64f-48ec-b321-396791916977.png)
Then I also created a user as below: 
![user1](https://user-images.githubusercontent.com/14155576/156513330-e86cfdb9-1927-40fd-bab6-812affe61964.png)
![user2](https://user-images.githubusercontent.com/14155576/156513340-5b4eee98-a9ef-44e3-b2ab-ec01b5a0048e.png)

However, if I tried to access the radius server by the command below: "radtest tester1 1111 192.168.123.87 0 secret1234", I would get "Access-Reject".

From the radius.log, I could see error below:

`Wed Mar  2 03:27:39 2022 : Auth: (2) Login incorrect (sql: Failed to create the pair: Unknown name "Caswell-CW_group"): [tester1] (from client my_lan port 0)`
I have tried to check from my radius server via MariaDB and I could see below: 
![DB_table](https://user-images.githubusercontent.com/14155576/156513505-b60cb6c7-a457-41b2-b1f2-6dd6bfbdd75f.png)

So, I can not understand why I would get access-rejected and why sql would said Unknown name.

If I delete the check attribute in the user account "tester1", I could get access "Access-accept".

Do I miss anything in my settings on radius server?

**Comment by chase200199** [comment]
[](https://stackoverflow.com/posts/71418179/timeline)0


I have founded the answer for my issue. If I want to add a new vendor and attributes, I will need to add a new file under the path: /usr/share/freeradius/.For example, if I want to add a new vendor like "fortesting" and an new attribute "testing attribute". I will need to add a new file called "dictionary.fortesting". And then I will need to modify the file "/usr/share/freeradius/dictionary" to include the file "dictionary.fortesting". After doing steps above, restating freeradius service. And then log in the WEB UI of daloradius, creating the same vendor and attributes.At last, I will be able to use the new vendor and attributes in my freeradius users.I will get " Access-Accept" while using the command "radtest".

**Comment by MiguelVis** [comment]
Hi @chase200199, you're right:

[https://github.com/FreeRADIUS/freeradius-server/blob/v2.x.x/raddb/dictionary.in](https://github.com/FreeRADIUS/freeradius-server/blob/v2.x.x/raddb/dictionary.in)

Thanks.
