### ISSUE TITLE
Cannot add MAC address as username

### ISSUE THREAD

**Issue by dever23b** [lirantal/daloradius#235]
Hello:

It appears that this was caused by the patch in #194 : the PHP filter (FILTER_VALIDATE_MAC) doesn't allow for an un-delimited MAC address, and considers the format AABBCCDDEEFF to be invalid, preventing account creation.  With the inability to change usernames, this presents a challenge requiring backend modification.

**Comment by bdauph85** [comment]
Any fix for this? I would rather not have to input all the devices manually into the SQL datatbase.

**Comment by MiguelVis** [comment]
Hi @dever23b.

AFAIK a string like `AABBCCDDEEFF` is not a valid MAC address format.

From [Wikipedia](https://en.wikipedia.org/wiki/MAC_address):

> The standard (IEEE 802) format for printing EUI-48 addresses in human-friendly form is six groups of two hexadecimal digits, separated by hyphens (-) in transmission order (e.g. 01-23-45-67-89-AB). This form is also commonly used for EUI-64 (e.g. 01-23-45-67-89-AB-CD-EF).[2] Other conventions include six groups of two hexadecimal digits separated by colons (:) (e.g. 01:23:45:67:89:AB), and three groups of four hexadecimal digits separated by dots (.) (e.g. 0123.4567.89AB); again in transmission order.
