### ISSUE TITLE
init.sh always waiting for mysql

### ISSUE THREAD

**Issue by cycloss** [lirantal/daloradius#236]
I've built the docker image, but I'm running into a problem with the `init.sh` script.

On line 54, there is the block:

```shell
while ! mysqladmin ping -h"$MYSQL_HOST" --silent; do
	echo "Waiting for mysql ($MYSQL_HOST)..."
	sleep 20
done
```

However, this loop never exits, unless I modify the script to add in the `-p` flag for the password, so the first line then reads:

```shell
while ! mysqladmin ping -h"$MYSQL_HOST" -p"$MYSQL_PASS" --silent; do
```

Now the program proceeds.

Am I missing something here? I opened a terminal and checked the command `mysqladmin ping -h myhost` and it doesn't work without a password and just gets access denied.

**Comment by lirantal** [comment]
Thanks for reporting the issue @cycloss.

I assume you are working with the current `master` branch's `Dockerfile`, yes?
It sounds like you already had some of your own data in `library/daloradius.conf.php` because the password is empty by default if you look at the `.sample` file that gets copied over in the beginning of `init.sh`, right?

Regardless, I think we should add that password flag as it would still be relevant whether password is specified or not. Do you want to try it out and also check out what I wrote in the previous paragraph to confirm?

**Comment by cycloss** [comment]
Thanks for your response @lirantal . Yes I'm  using the current master branch `Dockerfile`.

So I don't copy or mount my own data into `library/daloradius.conf.php`, but what I do do is set the following environment variables in my `docker-compose.yml`:

```
MYSQL_HOST=rad-db # the container name where the database resides
MYSQL_PORT=3306
MYSQL_DATABASE=radius
MYSQL_USER=radius
MYSQL_PASSWORD=pass
```

I would expect the `init.sh` to attempt to use the `MYSQL_PASSWORD` env variable, as it I can see the environment variable being written to the `daloradius.conf.php` on line 15 of the `init.sh` using `sed`. Surely if a password is being specified in the environment variable, the `mysqladmin ping` command is going to require the password set with the `-p` flag to be successful at testing the connection?

**Comment by lirantal** [comment]
Oh I see.
Maybe you can update the `init.sh` script in a pull request to look for those environment variables first and if it can't find them then it uses the sample file defaults? I'll be happy to merge the changes.

**Comment by cycloss** [comment]
Sure, I can do that for you if you review it. I think it might be as simple as just adding the `-p` flag to line 54 though. If there is no password in the `MYSQL_PASSWORD` environment variable, then it is assumed that there is no password on the database, and an empty password will be passed (which should work I believe). If there is a password in the variable, then it will pass that. What do you think?

I'm curious as to how it ever worked in the first place, unless it has only been used with databases with no passwords? I feel like i'm missing something

**Comment by lirantal** [comment]
If that's the way to solve it then I'm up for that. Would make a simple PR for sure :-)
However, can you please double and triple-check the different conditions to make sure it works as expected in all cases?
