### ISSUE TITLE
Exception when loading "accounting" page

### ISSUE THREAD

**Issue by gheger** [lirantal/daloradius#237]
Hi,

I just set up daloradius 1.3.

My stack: Apache/2.4.52 (Ubuntu), PHP 8.1.2, FreeRADIUS Version 3.0.26

It's a fresh install, and I added no new data in the DB. When loading the account page, I get this exception:

`PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string - null in /var/www/html/daloradius/include/management/userReports.php:386\nStack trace:\n#0 /var/www/html/daloradius/acct-username.php(82): userPlanInformation()\n#1 {main}\n  thrown in /var/www/html/daloradius/include/management/userReports.php on line 386, referer: http://x.x.x.x/daloradius/mng-search.php?username=anyUser`

I just commented out this line 82, because I don't need this _userPlanInformation_ . However, I wanted to let you know about the issue.

Another one was:
`PHP Fatal error:  Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /var/www/html/daloradius/library/libchart/classes/PieChart.php on line 78, referer: http://x.x.x.x/daloradius/mng-main.php`

Thanks,
Garry

**Comment by MiguelVis** [comment]
Fixed with #252
