### ISSUE TITLE
No Listing Online Users

### ISSUE THREAD

**Issue by frontearlol** [lirantal/daloradius#239]
We have had our daloradius/freeradius configuration up and running for approximately 6 months.

Recently it appears that the radacct table is empty on the sql database:

MySQL [radius]> SELECT * from radacct;
Empty set (0.004 sec)

Dalo mapping for this is:
$configValues['CONFIG_DB_TBL_RADACCT'] = 'radacct'

I'm fairly new to this configuration so anything to point towards steps to resolve would be most appreciated.

**Comment by MiguelVis** [comment]
Hi @frontearlol this issue is related to FreeRadius not Daloradius.

Check your FreeRadius configuration in order to active and select the MySQL module as backend and not files as default.
