### ISSUE TITLE
Support of freeradius 3.x ?

### ISSUE THREAD

**Issue by juanluisbaptiste** [lirantal/daloradius#24]
Hi,

Any plans to add support for freeradius 3.x ?

**Comment by lirantal** [comment]
I'm not personally running any FreeRADIUS related setup anymore so it's hard for me to test and verify things. If someone is willing to take a step into wiring things up and configuring it I'll be happy to join them in making necessary changes in daloRADUIS code base to make it work.

Let me know if you or anyone else is up to it.

BTW, I haven't tested FR 3 myself as I stated above, but I did see a few threads of dalo + FR3 so maybe it just works out of the box, or only slight modifications necessary. Possibly there isn't really much to do there.

**Comment by reigelgallarde** [comment]
I can confirm this works for me without problems...

**Comment by lirantal** [comment]
@juanluisbaptiste awesome, thanks for confirming!
I assume you are using the latest daloradius code from github?

**Comment by reigelgallarde** [comment]
no, I'm using the one from sourceforge.
But I have an idea that that will not matter...
Because I check the contrib on github and it looks the same...

**Comment by lirantal** [comment]
but some of the core daloradius code has been updated as well.
any chance you can just download it and check with FR3?

**Comment by reigelgallarde** [comment]
We tested it using this "Pi Hotspot Script. Issue raised here "https://github.com/pihomeserver/Pi-Hotspot-Script/issues/35 (not really an issue but a recommendation)
It's working fine and we are now using github version for the latest Pi Hotspot Script.

**Comment by lirantal** [comment]
awesome, thanks!

**Comment by kafui** [comment]
can you please help with a reference link for freeradius 3.0 and daloradius or help with a step by step tuts
will be very appreciated

**Comment by reigelgallarde** [comment]
@kafui use this script https://github.com/pihomeserver/Kupiki-Hotspot-Script

**Comment by kafui** [comment]
Will it please configure freeradius 3.0.x? with daloradius automatically

**Comment by baguswahyu** [comment]
> @kafui use this script https://github.com/pihomeserver/Kupiki-Hotspot-Script

updates/sqlcounter
i saw your repo with this additional file
this is sqlcounter with freeradius 3 format
will all attribute which available in daloradius latest working with this sqlcounter update from ur repo?
thanks Advance
