### ISSUE TITLE
HTTPS is not working on daloradius.com

### ISSUE THREAD

**Issue by bjarnirafn** [lirantal/daloradius#240]
Server's certificate does not match daloradius.com. The cert is issued to *.github.com.

**Comment by MiguelVis** [comment]
Hi @bjarnirafn this issue is related to the server where you install Daloradius.

It's not related to Daloradius itself sorry.

**Comment by MiguelVis** [comment]
Sorry @bjarnirafn you're right.

AFAIK the website owner is @lirantal.

**Comment by lirantal** [comment]
Oh, right. I'll try and get that resolved
Good catch @bjarnirafn

**Comment by lirantal** [comment]
@bjarnirafn this has been fixed. Thank you for bringing it up!
