### ISSUE TITLE
Issues on Profile/Groups

### ISSUE THREAD

**Issue by doisanity** [lirantal/daloradius#246]
Hello! Doi here :) 

I'm very new with DaloRADIUS and Radius in general but somehow managed to make one. So here goes.
I have created a Profile to limit internet usage using WISPr (max up/max down) and another profile to limit connected accounts (Simultaneous-use). 
![image](https://user-images.githubusercontent.com/108038455/175856501-2c21ce6f-7678-4bbb-a896-74adad620062.png)

I have set the profile/group created to a test user account but somehow, the profile/group created is not being applied. Internet speeds I get on speedtest is the speeds I set on my PfSense rule. 
![image](https://user-images.githubusercontent.com/108038455/175856771-3c1aac8f-adbb-427c-9a62-7627770d4ae3.png)

Is there any fix on this? 

Thank you so much

**Comment by MiguelVis** [comment]
Hi @doisanity IIRC only a group will be applied to a user in the end.

See the group priority?

Check if "1 device per user" is applied as expected.
