### ISSUE TITLE
Accounting Backup Server

### ISSUE THREAD

**Issue by iamenderst** [lirantal/daloradius#247]
I've been clicking around looking looking for setting up an accounting backup server. Is that not available thru daloradius and I need to take care of it directly in freeradius?

**Comment by lirantal** [comment]
Correct @iamenderst. daloRADIUS simply reads off of the primary (MySQL) database that FreeRADIUS writes to. Any sort of backup configuration and syncs you'd have to come up with yourself.

**Comment by iamenderst** [comment]
Got it, thank you.
