### ISSUE TITLE
Database error Error Message: DB Error: no such table Debug info: SELECT * FROM radhuntgroup [nativecode=1146 ** Table 'radius.radhuntgroup' doesn't exist]

### ISSUE THREAD

**Issue by leond08** [lirantal/daloradius#257]
This is my first time to use daloRadius as I was exploring the system I encountered an error

```
Database error
Error Message: DB Error: no such table
Debug info: SELECT * FROM radhuntgroup [nativecode=1146 ** Table 'radius.radhuntgroup' doesn't exist]

```
Under Hunts Group there is database error the radhuntgroup table doesn't exist
I used the docker configuration provided on the source code.

**Comment by filippolauria** [comment]
Please refere to this wiki: https://wiki.freeradius.org/guide/SQL-Huntgroup-HOWTO.
