### ISSUE TITLE
Blank Page After Login 

### ISSUE THREAD

**Issue by 0sifat** [lirantal/daloradius#258]
When i am using username : administrator
and pass: radius
it goes to http://192.168.130.200/daloradius/dologin.php but a blank page with this error 

This page isn’t working192.168.130.200 is currently unable to handle this request.
HTTP ERROR 500

**Comment by lirantal** [comment]
Look up the server logs. You're missing something in your setup.

**Comment by samuelchchan** [comment]
Lirantal, which part of the server log should be looking at? I have the exact same situation and seem this is the error

`PHP Fatal error:  Call to undefined function hash_equals() in /var/www/html/daloradius/library/sessions.php on line 45,`

**Comment by filippolauria** [comment]
@0sifat which version of PHP are you using?

**Comment by filippolauria** [comment]
Nevermind, thanks to @samuelchchan comment I found out that [hash_equals](https://www.php.net/manual/en/function.hash-equals.php) function has been added in PHP version >= 5.6.0.

This issue has been resolved with one of the last commits.

**Comment by lirantal** [comment]
Go Filippo 🙌
