### ISSUE TITLE
daloRADIUS 1.3 looks ugly - what did I do wrong?

### ISSUE THREAD

**Issue by j4nd3r53n** [lirantal/daloradius#279]
I have just succeeded in getting daloRADIUS to work, and I can log in as Administrator - but it looks quite ugly, especially compared to the pictures in the User's Manual, which I have for version 0.9. Is there something missing from my installation?

![daloRADIUS](https://user-images.githubusercontent.com/44969502/200586899-b9c00e22-0127-4219-8ae2-3e1559d7a2a0.png)

**Comment by filippolauria** [comment]
Hi.
Probably there is a failure in loading CSS styles.

Open your browser "developers tools", tab "network" and visit daloRADIUS.

Can you provide a screenshot of the tab "network"?
