### ISSUE TITLE
latest version last connection attempts not showing up?

### ISSUE THREAD

**Issue by jeepmullet** [lirantal/daloradius#28]
Using FR 3.1.2 and the latest commit of daloRADIUS last connection attempts never updates.  

Debugging SQL Queries: 
SELECT radpostauth.username, radpostauth.pass, radpostauth.reply, radpostauth.authdate FROM radpostauth WHERE (radpostauth.username LIKE '%%') AND (authdate >='2017-01-01' AND authdate <='2017-02-28') ORDER BY radpostauth.id desc LIMIT 0, 25 

is there something I need to change from the previous config?  It's been working well for going on a year with every update until this last one.  Thank you

**Comment by lirantal** [comment]
@jeepmullet hard to tell what changed. you sure it's due to daloradius latest update? can you tell on which commit were you before? I can try to review the commits between and see if there's something that jumps out.
