### ISSUE TITLE
No graphs displaying

### ISSUE THREAD

**Issue by CALROB** [lirantal/daloradius#281]
Hi all, anyone else having an issue with dalo radius where the graphs aren't working?

Console showing 500 internal server error which seems to relate to a 404 also.

It definitely exists too

**Comment by filippolauria** [comment]
Hello @CALROB , I suppose you are talking about the most recent version of daloRADIUS.

Can you please provide details on your environment (OS, DB, PHP, Web Server, etc.) and also the error taken from the log of the Web Server?

**Comment by CALROB** [comment]
Ofcourse, I'll provide this shortly, stay tuned

**Comment by CALROB** [comment]
Firstly, here's a screenshot of the page and console tab within chrome:
<img width="1774" alt="image" src="https://user-images.githubusercontent.com/10970988/201634041-5a28d9a7-bc5d-42a0-999e-4f2c0fbf599d.png">

OS: Ubuntu 22.04
DB: Maria
PHP: 8.1
We Server Apache.

Apache error log:
`[Mon Nov 14 00:00:02.222361 2022] [mpm_prefork:notice] [pid 26562] AH00163: Apache/2.4.52 (Ubuntu) OpenSSL/3.0.2 configured -- resuming normal operations
[Mon Nov 14 00:00:02.222395 2022] [core:notice] [pid 26562] AH00094: Command line: '/usr/sbin/apache2'
[Mon Nov 14 03:12:25.291131 2022] [authz_core:error] [pid 28672] [client IP] AH01630: client denied by server configuration: /var/www/html/server-status
[Mon Nov 14 03:12:25.293958 2022] [php:error] [pid 29516] [client IP] script '/var/www/html/info.php' not found or unable to stat
[Mon Nov 14 10:10:55.546172 2022] [php:error] [pid 37973] [client IP] PHP Fatal error:  Uncaught TypeError: array_push(): Argument #1 ($array) must be of type array, null given in /var/www/html/library/libchart/classes/model/XYDataSet.php:44\nStack trace:\n#0 /var/www/html/library/libchart/classes/model/XYDataSet.php(44): array_push()\n#1 /var/www/html/library/chart-mng-total-users.php(40): XYDataSet->addPoint()\n#2 {main}\n  thrown in /var/www/html/library/libchart/classes/model/XYDataSet.php on line 44, referer: https://rad.giantcomms.co.uk/mng-main.php`

**Comment by CALROB** [comment]
fixed sir, amazing work!
