### ISSUE TITLE
daloradius-users/dologin.php Database connection error 

### ISSUE THREAD

**Issue by jaschadub** [lirantal/daloradius#29]
Database connection error
Error Message: DB Error: extension not found

When trying to connect as user to change password using PHP7.0

Main install works just trying to login as user to edit password and so forth.

**Comment by lirantal** [comment]
Odd, it should use the same DB extension but maybe I didn't update the dologin.php for daloradius-users like I did for the tool itself. I'll take a look and see.

**Comment by lirantal** [comment]
Seems like opendb.php are similar in both.
Do you have more detailed logs maybe? are you sure the regular daloradius login works?

**Comment by bitak1** [comment]
I had the same problem and I found out, that daloradius-users library didn't have some files updated. Copying them from daloradius library solved the issue.
```text
cd /var/www/daloradius/
cp ./library/daloradius.conf.php ./daloradius-users/library/
cp ./library/opendb.php ./daloradius-users/library/
cp ./library/tableConventions.php ./daloradius-users/library/
cp ./library/errorHandling.php ./daloradius-users/library/
chown -R www-data:www-data ./daloradius-users/library/
```

**Comment by lirantal** [comment]
@bitak1 thanks, would you be interested in submitting a PR with the proposed changes to fix the `daloradius-users/` directory?

**Comment by charliez100** [comment]
atabase connection error
Error Message: DB Error: extension not found

First login using PHP7.0

**Comment by charliez100** [comment]
Also have the following challenge:
[root@localhost /]# yum install php-pear
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: jnb.mirror.kvm.net
 * epel: mirror.netweaver.uk
 * extras: jnb.mirror.kvm.net
 * ius: mirror.slu.cz
 * updates: jnb.mirror.kvm.net
Resolving Dependencies
--> Running transaction check
---> Package php-pear.noarch 1:1.9.4-21.el7 will be installed
--> Processing Conflict: 1:php70u-pear-1.10.5-1.ius.centos7.noarch conflicts php-pear < 1:1.10.5-1.ius.centos7
--> Finished Dependency Resolution
Error: php70u-pear conflicts with 1:php-pear-1.9.4-21.el7.noarch
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by sayayin2023** [comment]
Cuando intento logearme a  me redirige a dologin.php

Cual es el error y como podria salucionar?
