### ISSUE TITLE
mng-rad-hunt-list.php does not show list of hunt group

### ISSUE THREAD

**Issue by microservizi** [lirantal/daloradius#291]
mng-rad-hunt-list.php does not execute list of mng-rad-hunt-list.php

**Comment by microservizi** [comment]
here is the log on apache error log
[php:error] [pid 75348] [client xxx:61087] PHP Fatal error:  Uncaught Error: Call to undefined function sprint() in /var/www/html/daloradius2/mng-rad-hunt-list.php:156\nStack trace:\n#0 {main}\n  thrown in /var/www/html/daloradius2/mng-rad-hunt-list.php on line 156, referer: http://xxx/daloradius2/mng-rad-hunt-list.php

**Comment by filippolauria** [comment]
There was a typo in mng-rad-hunt-list.php. I have addressed this issue in #293
