### ISSUE TITLE
daloradius-master bug url

### ISSUE THREAD

**Issue by predators46** [lirantal/daloradius#294]
@lirantal 

i just tried daloradius master branch. 

tested on openwrt php7.4.33, uhttpd

when I use the url http://192.168.1.1/daloradius 

i can't access daloradius and i get an error message 

```not Found The requested URL /login.php was not found on this server```

the solution to being able to access my daloradius is using this url http://192.168.1.1/daloradius/login.php

i have tested daloradius tag release 1.3 everything works fine. 

maybe this is due to changes in daloradius in the master branch

**Comment by Skad0sh** [comment]
Move the DaloRadius files to the apache2 root directory and everything will be fine. This occurs because index.php is redirected to /login.php (absolute path) and there is no login.php in your apache2 root directory.
do ``sudo mv ./* ..`` in the daloradius directory.

**Comment by predators46** [comment]
> Move the DaloRadius files to the apache2 root directory and everything will be fine. This occurs because index.php is redirected to /login.php (absolute path) and there is no login.php in your apache2 root directory. do `sudo mv ./* ..` in the daloradius directory.

I don't use Apache because the file size is very large, I use a router for OpenWrt installation. instead of apache I use uhttpd which is in openwrt the file size is not too big

**Comment by filippolauria** [comment]
Hello @predators46 , you can try to resolve this configuration issue just by putting daloRADIUS files directly inside your _server document root_ (specified in the option _home_, according to https://openwrt.org/docs/guide-user/services/webserver/uhttpd) without using any subdirectory.

**Comment by predators46** [comment]
> Hello @predators46 , you can try to resolve this configuration issue just by putting daloRADIUS files directly inside your _server document root_ (specified in the option _home_, according to https://openwrt.org/docs/guide-user/services/webserver/uhttpd) without using any subdirectory.

i had this on daloradius-master and i have tried the 1.3 release version no problem. I already understand about uhttpd in openwrt

**Comment by xeonz15** [comment]
In library/checklogin.php line 38 replace
`    header('Location: /login.php');`
with
`    header('Location: login.php');`

**Comment by predators46** [comment]
Thanks fix

```header('Location: login.php');```

**Comment by predators46** [comment]
@filippolauria 

please fix

**Comment by predators46** [comment]
Update !!

daloradius-master is broken for openwrt

![Screenshot_2022-11-26_094154](https://user-images.githubusercontent.com/31931530/204067717-def6e930-01ee-4d1d-a2b6-818825fd4c39.jpg)

**Comment by predators46** [comment]
@filippolauria 

there's another problem

![Screenshot_2022-11-26_094154](https://user-images.githubusercontent.com/31931530/204073807-e8a47289-4919-4d9b-a2d3-e19adbbca0af.jpg)
![Screenshot_2022-11-26_133010](https://user-images.githubusercontent.com/31931530/204073811-3aff9959-2c9e-4bdf-b57d-94396a0f1f3e.jpg)
