### ISSUE TITLE
Can not add Hotspot in mng-hs-new.php

### ISSUE THREAD

**Issue by momothefox** [lirantal/daloradius#306]
Hotspot MAC address not showing in mng-hs-edit.php

![bandicam 2022-12-14 00-07-43-551](https://user-images.githubusercontent.com/25464943/207454811-35c389b4-c85e-4f8d-8935-cd444bb07af3.jpg)

**Comment by huseyinyildirim** [comment]
Please look: https://github.com/lirantal/daloradius/pull/304

**Comment by momothefox** [comment]
> Please look: #304

that did not fix mng-hs-edit.php

actually mng-hs-new.php also not functioning well 

![bandicam 2022-12-14 13-36-52-465](https://user-images.githubusercontent.com/25464943/207585384-9bcec93a-b103-4ce8-b3ff-eb71e2fb7fdb.jpg)

**Comment by filippolauria** [comment]
@huseyinyildirim your contribution ( #304 ) fixed a typo in the data presentation phase.
Instead, the issue reported here was caused by another error in the validation phase.
I have addressed it in #311 .
