### ISSUE TITLE
Can't add attributes to existing user

### ISSUE THREAD

**Issue by Mindless999** [lirantal/daloradius#307]
I'm currently missing the "Attributes" tab that was in one of the older version to add new attributes to a user after it has been created.

Right now we have the attributes tab that is available when creating a new user, however if the user already exists it will not show up and we can't add new attributes.
This was available in the older version
see pictures below for the tab missing on the edit user.
![daloradius1](https://user-images.githubusercontent.com/20699783/207567390-2cf452e3-2ac3-4b87-be0b-114ecd9dcae6.png)
![daloradius2](https://user-images.githubusercontent.com/20699783/207567394-ba38f7b4-06b3-44b7-b156-f15a16509750.png)
![daloradius3](https://user-images.githubusercontent.com/20699783/207567956-89298be2-6906-4444-a3a6-b6423e2fad8b.png)

**Comment by filippolauria** [comment]
Ok. Thank you for noticing that. Your PR has been merged.
