### ISSUE TITLE
Allow empty password in mng-batch-add.php

### ISSUE THREAD

**Issue by momothefox** [lirantal/daloradius#314]
Please allow empty password for generating vouchers / coupons with username only.

**Comment by filippolauria** [comment]
At the moment, when you create batch users, the system basically adds a password-like attribute (with a random value) to radcheck for each random (or sequential) username of the batch.

What you are asking is to create a kind of "batch pin-code authentication". In this case the process should add the attribute 'Auth-Type' := Accept for each random (or sequential) pin codes of the batch.

Is that what are you asking?

**Comment by momothefox** [comment]
> At the moment, when you create batch users, the system basically adds a password-like attribute (with a random value) to radcheck for each random (or sequential) username of the batch.
> 

yes and what is needed just to allow 0 password length to allow creating password attribute with empty password. 
actually it was like that in daloRADIUS 1.3 

this is current code 
```
        $input_descriptors1[] = array(
                                        "name" => "length_pass",
                                        "caption" => t('all','PasswordLength'),
                                        "type" => "number",
                                        "value" => ((isset($failureMsg)) ? $length_pass : "8"),
                                        "tooltipText" => t('Tooltip','lengthOfPasswordTooltip'),
                                        "min" => "8",
                                     );
```
 Needs to be like this 

```
        $input_descriptors1[] = array(
                                        "name" => "length_pass",
                                        "caption" => t('all','PasswordLength'),
                                        "type" => "number",
                                        "value" => ((isset($failureMsg)) ? $length_pass : "0"),
                                        "tooltipText" => t('Tooltip','lengthOfPasswordTooltip'),
                                        "min" => "0",
                                     );

```


> What you are asking is to create a kind of "batch pin-code authentication". In this case the process should add the attribute 'Auth-Type' := Accept for each random (or sequential) pin codes of the batch.

Actually what is happening is that the user can Auth with entering pin only with empty password. 
without the need of any more attributes. 

it was working with pervious code of daloRADIUS 1.3 you could put min length of auto generated password to 0 
and no other attributes needed.

**Comment by filippolauria** [comment]
Hi @momothefox ,
check out #331

**Comment by momothefox** [comment]
> 

Hi @filippolauria  
i checked out #331 i downloaded and tested it. 
that is not what i wanted to say. 
when i tried to generate vouchers with Account Type Random Pin Code (no Password) 
it resulted in empty batch when exported is totally empty 
what is needed is simply allow Length of password string to be Zero 
and that's it.  it was working before like that.
