### ISSUE TITLE
daloradius ui

### ISSUE THREAD

**Issue by predators46** [lirantal/daloradius#323]
@filippolauria 

when opening daloradius using android it looks ugly
![Screenshot_2023-01-01_093721](https://user-images.githubusercontent.com/31931530/210193581-2d735d1a-f516-4468-acb4-c6b47e183c10.jpg)

**Comment by predators46** [comment]
![Screenshot_2023-01-02_124942](https://user-images.githubusercontent.com/31931530/210196001-4e03f9b4-1257-4a16-8352-7758858da57a.jpg)
![Screenshot_2023-01-02_124956](https://user-images.githubusercontent.com/31931530/210196008-6ba41418-b3e6-4101-a64f-e56efe6b7c4f.jpg)

**Comment by predators46** [comment]
![Screenshot_2023-01-02_124942](https://user-images.githubusercontent.com/31931530/210196060-0e9a21f6-71ec-418e-9886-61c279889b3d.jpg)
![Screenshot_2023-01-02_124956](https://user-images.githubusercontent.com/31931530/210196064-e78c86ed-ad99-4e9a-8530-5b6be6ca7cb1.jpg)

**Comment by predators46** [comment]
i tried old version of daloradius and see error

![Screenshot_2023-01-01_010426](https://user-images.githubusercontent.com/31931530/210474376-391a42ec-2171-4271-879e-3f40db6db9ba.jpg)

**Comment by filippolauria** [comment]
Hi @predators46 ,
at the moment, on mobile devices the app does not display correctly.
However, as a workaround, on the browser in use on your mobile device you can enable the "view as desktop site" option.

**Comment by predators46** [comment]
> Hi @predators46 , at the moment, on mobile devices the app does not display correctly. However, as a workaround, on the browser in use on your mobile device you can enable the "view as desktop site" option.

I've tried desktop mode it's still like that

**Comment by predators46** [comment]
@filippolauria 

how to fix this? 

I want to use the old version of Daloradius
https://github.com/lirantal/daloradius/issues/323#issuecomment-1370425248

**Comment by filippolauria** [comment]
We are working to a new release. Until then, we recommend to use master-branch.
