### ISSUE TITLE
User info importing

### ISSUE THREAD

**Issue by noushadalip786** [lirantal/daloradius#324]
Hi, I have morethan 8000 users, adding user info manually is a time consuming task, instead How import user info such as firstname, last name, mail, etc into daloradius. Your Responses are highly appreciatd

**Comment by filippolauria** [comment]
Hi @noushadalip786 ,
at the moment, the user import feature allows you to import user/password(s), mac-addresses or pin codes.
In the future we could add other fields. Feel free to write a few lines of PHP code to help in adding these new features as well.

**Comment by GreenGalah** [comment]
+1 vote for this enhancement. 
I am using the workaround of using phpmyadmin to import users directly into the user table, as I suspect many other people are.
