### ISSUE TITLE
Looking for a change to rep-lastconnect.php

### ISSUE THREAD

**Issue by trosenda** [lirantal/daloradius#333]
Hi,
using daloradius in a Mac-Auth-Bypass environment, where username equals the password equals the mac address.
For reporting/troubleshooting I would like rep-lastconnect.php to display the full name (first+last) also, as it would make tracking an issue much easier. Unfortunately my php knowledge is -zero-, so any helping hand appreciated.

thanks.

**Comment by filippolauria** [comment]
Hi @trosenda ,
check out #334 .

**Comment by trosenda** [comment]
Hi @filippolauria ,

that was quick. Thanks a bunch !
Can I buy you a coffee ?

**Comment by filippolauria** [comment]
Thanks mate. Don't worry about that. I'm glad these changes were helpful to you. In case you have any other useful advice, don't hesitate to write here again.

Cheers

**Comment by trosenda** [comment]
Thanks again!
