### ISSUE TITLE
Feature Request : Report for unknown/failed Access Requests

### ISSUE THREAD

**Issue by trosenda** [lirantal/daloradius#337]
Hi, it's me again, 
using daloradius in a Mac-Auth-Bypass environment, where username equals the password equals the mac address.

the latest change to rep-lastconnect.php did what I previously asked for. Thanks again.

I now noticed that it only contains entries for known users.
I'm not sure my "wish" is a corner case, but I would like to be able to see *all* access-rejects, also for unknown users (equaling unknown devices).

Judging the headline "Last Connection Attempts" I think they belong there, but I am not sure it would create to much noise in other environments, so maybe asking for a new report here, or optionally to include them.

I am helping myself with the following query 
`"SELECT * FROM radpostauth WHERE reply = 'Access-Reject' ORDER BY id DESC LIMIT 50;"`

Thanks

**Comment by filippolauria** [comment]
Hi @trosenda ,
check out #339 .
