### ISSUE TITLE
Freeradius 3.x PHP7 and Postgres: DB connection failure

### ISSUE THREAD

**Issue by kbaegis** [lirantal/daloradius#34]
On dologin.php:
```
 Warning: include_once(DB.php): failed to open stream: No such file or directory in /var/www/localhost/htdocs/daloradius/library/opendb.php on line 84

Warning: include_once(): Failed opening 'DB.php' for inclusion (include_path='.:/usr/share/php7:/usr/share/php') in /var/www/localhost/htdocs/daloradius/library/opendb.php on line 84

Fatal error: Uncaught Error: Class 'DB' not found in /var/www/localhost/htdocs/daloradius/library/opendb.php:86 Stack trace: #0 /var/www/localhost/htdocs/daloradius/dologin.php(49): include() #1 {main} thrown in /var/www/localhost/htdocs/daloradius/library/opendb.php on line 86
```
Never had daloradius working, so I don't know what to compare this output to.

**Comment by lirantal** [comment]
There's an issue here where we logged how to make sure you have all of these dependencies installed. Take a quick look in the issue queue and you'll find it.

**Comment by daniel2029** [comment]
Was there a solution to this?

**Comment by lirantal** [comment]
@daniel2029 still an issue for you? we have detailed installation instructions on this issue https://github.com/lirantal/daloradius/issues/87 - perhaps you can try and follow it?

**Comment by daniel2029** [comment]
Thanks for your reply @lirantal I appreciate it. However I gave up.

**Comment by lirantal** [comment]
Sorry to hear and goodluck
