### ISSUE TITLE
Possible fix for no hashing in mng-import-users.php

### ISSUE THREAD

**Issue by DutchGalah** [lirantal/daloradius#342]
Hi,
I figured out that the password hash is not applied regardless of chosen password type if you import users.
Adding two lines seem to fix it for me, but I don't know if it breaks anything else.
line 135: include("library/attributes.php");
line 138: $value = hashPasswordAttribute($passwordType, $value);

I hope this helps, looks like this has been missing for a while.
Regards, Malcolm

**Comment by filippolauria** [comment]
Hi Malcolm,
check out #344 which should have fixed the issue you have reported.

**Comment by DutchGalah** [comment]
Tested and this works thank you. Issue can be closed.
