### ISSUE TITLE
Link to new user on the user added page

### ISSUE THREAD

**Issue by tylla** [lirantal/daloradius#345]
I would like to propose a small but useful enhancement:
- on the page after adding a new user there is a small entry with a star that says: "Added to database new user: UsErNaMe"
- this would be a really nice opportunity to make the username a link to the edit user page, so this could look something like "Added to database new user: <a href='/mng-edit.php?username=UsErNaMe'>UsErNaMe</a>"

**Comment by filippolauria** [comment]
Hi @tylla ,
what version of daloRADIUS are you talking about?
In the master-branch version the enhancement you propose has been already added both in [mng-new-quick.php](https://github.com/lirantal/daloradius/blob/561884c8d2403aac40ddac7e7df1bb5372115f71/mng-new-quick.php#L253) and in [mng-new.php](https://github.com/lirantal/daloradius/blob/561884c8d2403aac40ddac7e7df1bb5372115f71/mng-new.php#L302).

**Comment by tylla** [comment]
Hmmm, "version 1.3 / 04 Nov 2021".
Sorry about that, I searched for this thing in both open and closed tickets, but I couldn't find anything related.
But I'm really happy to hear that it's already done. ;-)
We'll get the feature as soon as we update to the next release (this is a production environment, so unstable versions are out of question).

**Comment by filippolauria** [comment]
Got it. A new release will be available as soon as we are ready. In the meanwhile, please, consider to install the master-branch version on a testing environment. Try to use it and maybe give us some feedback on bug or new features.
