### ISSUE TITLE
Daloradius user under daloradius-user url not works 

### ISSUE THREAD

**Issue by gvt2015** [lirantal/daloradius#346]
Daloradius user under daloradius-user url not works , tried using latest 1.3 version of daloradius with enabled user portal login and password but client ie user not able to login. Need solution for this issue.

**Comment by gvt2015** [comment]
Any updates

**Comment by filippolauria** [comment]
Hello @gvt2015 , currently I'm focusing on the management part of the project.
In the future I am planning to also review the user part, but I am not able to indicate a precise date.
