### ISSUE TITLE
No Cleartext-Password Option

### ISSUE THREAD

**Issue by dmenam** [lirantal/daloradius#348]
![Captura de pantalla 2023-01-24 144332](https://user-images.githubusercontent.com/105247079/214406765-3676dbb9-882a-457e-94fd-cb3379f4d722.png)

**Comment by filippolauria** [comment]
Hi @dmenam ,
#351 should have fixed the issue.
Also, make sure that cleartext passwords are allowed on your configuration section
![image](https://user-images.githubusercontent.com/4223503/214582182-12f24bb0-baf3-4692-a438-26db6c067a84.png)

**Comment by dmenam** [comment]
It is fixed now, thanks
