### ISSUE TITLE
Sub menu not visible

### ISSUE THREAD

**Issue by prabath84** [lirantal/daloradius#359]
I have an issue in FreeRADIUS with MariaDB, along with daloRADIUS in Ubuntu 20.04 . In daloRADIUS Web Interface I cannot view the Sub Menu. Please see the attached Image for more detail.

DaloRADIUS Version : version 1.3 / 04 Nov 2021.

![Dalo-1675051818 8532](https://user-images.githubusercontent.com/23372577/215516481-b3356c62-63c5-4df2-af34-592ea91e0e43.jpg)

**Comment by ErBinay** [comment]
Dear user, I have faced the same issue and has been resolved by today. Visit the below link where you will find the full details of resolution. Thank You.
https://github.com/filippolauria/daloradius
