### ISSUE TITLE
Unknown column 'acctupdatetime' in 'field list' - Accounting feature bug

### ISSUE THREAD

**Issue by prabath84** [lirantal/daloradius#361]
Hi @filippolauria 

I have installed FreeRADIUS & daloRADIUS on Ubuntu 22.04 + MariaDB. 

I can see following error after Accounting enabled while VPN Users connecting.

When FreeRadius runs on debug mode : sudo freeradius [-X](url)

sql: ERROR: rlm_sql_mysql: ERROR 1054 (Unknown column 'acctupdatetime' in 'field list')

How can I prevent this issue ? 
Please refer to the attached Debug Info TXT for more detail. 

[debug-info-radius.txt.txt](https://github.com/lirantal/daloradius/files/10553485/debug-info-radius.txt.txt)

**Comment by filippolauria** [comment]
Hi @prabath84 ,
it seems you used a mismatching SQL schema.
Try using [fr3-mysql-freeradius.sql](https://github.com/lirantal/daloradius/blob/master/contrib/db/fr3-mysql-freeradius.sql).

**Comment by prabath84** [comment]
Thank you very much. Issue Resolved.
