### ISSUE TITLE
Imported users are 'read only'. There is no Apply button displayed in mng-edit.php

### ISSUE THREAD

**Issue by DutchGalah** [lirantal/daloradius#363]
Hi,
I cannot apply any changes made to imported users as there is no Apply button displayed on the mng-edit.php screen.
Manually created users are uneffected.
I have tested with no group, group, NT Password and UserPassword selected in the import form.

I am happy to look at the code for a fix, but I cannot find the relevant code as yet.

Regards,
Malcolm

**Comment by DutchGalah** [comment]
I have spend the evening having a look.
The html code stops after
![image](https://user-images.githubusercontent.com/123048953/216820076-9106fefa-0244-4fe1-bba0-f9cf1079fc99.png)
with no  and the form ends without drawing the submit button. The 'Back to Previous Page' link also does not get printed.
One of the functions after line 833 in mng-edit.php causes a IF statement in print_form_component to fail I think, but the code is a little dense for me.

**Comment by DutchGalah** [comment]
Actually ignore this for now. I have found other things wrong, so I am refreshing my database and installation.

**Comment by DutchGalah** [comment]
Issue can be closed. It started to happen on most users, added or imported, so I loaded a commit from 30th Jan (before the dynamic menu changes) and tested on a cleaned setup. No longer happening.

**Comment by filippolauria** [comment]
Hi @DutchGalah , check out  #370 . This should have fixed most of the issues and hopefully not created many new ones :)
