### ISSUE TITLE
Web Interface - most of the features not working anymore

### ISSUE THREAD

**Issue by prabath84** [lirantal/daloradius#365]
I cannot see ADD button when I try to add new radius user via web admin page even if i login as adminsitrator 

Please see the below images 

![image](https://user-images.githubusercontent.com/23372577/216748973-5ffb55f7-c592-44ab-a3a4-6bc33e7b6d27.png)
![image](https://user-images.githubusercontent.com/23372577/216748989-746b6a33-9129-4985-9d30-b211145145de.png)

Radius Logs even not able to view 

![image](https://user-images.githubusercontent.com/23372577/216749008-c0e04576-b297-4ded-be9a-85384522d1ce.png)

I have used Ubuntu Server 22.04 with maria DB
also I used "contrib/db/fr3-mysql-freeradius.sql" 

![image](https://user-images.githubusercontent.com/23372577/216749054-6e5e899e-a20d-4ea8-a278-1cff36b840bb.png)

What could be the Issue ?  My worry is I have recently installed same in another VM ( few days back) that web interface full working as expected.

**Comment by norrizuan1** [comment]
Hi,
Just want to confirm the issue. I have to use the 1.3 version for the moment. Look forward for the updates.
