### ISSUE TITLE
DD-wrt chilispot

### ISSUE THREAD

**Issue by douglashipocreme** [lirantal/daloradius#37]
why i cannot see the splash (signup-free) on clients ? Any Glue ?

i am using the last 0.9.9 daloradius  with freeradius on Ubuntu .

DD-wrt is v2.4 sp2

**Comment by lirantal** [comment]
I don't know.
Can you provide some more debug information and background on the setup?

**Comment by douglashipocreme** [comment]
ubuntu 16.04 - freeradius - and last daloradius ... i can see the account packages from dd-wrt...

but my clients not splash the signup-free screen 
nothing happens..
and no internet on clients

if i disable chilispot on dd-wrt ... internet is working nornal ..

**Comment by lirantal** [comment]
you need to be able to debug things more cleanly to identify what's the problem.
first of all, try to simulate some radius requests for freeradius+daloradius to figure out if you have that part integrated well (there's a radius client tool for that).

**Comment by douglashipocreme** [comment]
i am testing with your VM . the radius part works ok, i had tested with radclient from remote machines. the strange thing is DD-WRT this is not sending requests to server. my config looks like this ..

![image](https://user-images.githubusercontent.com/5216247/29518711-ce988076-8650-11e7-9122-a9c6ff260a89.png)

**Comment by lirantal** [comment]
It has been years since I managed a dd-wrt setup so apologies for not being helpful there.
If you start freeradius in debug mode you don't see any requests coming in from dd-wrt? if so definitely something mis-configured (ips, port, something). Double-check your FR logs, maybe you didn't allow the NAS as a trusted client to send you data.

**Comment by douglashipocreme** [comment]
thanks .. DD-WRT not working at all .. i changed firmaware to OpenWRT and now is working. 
new doubt .. using freesignup, how can i redirect login (user and password) automatically ?
