### ISSUE TITLE
Batch Users Not Exporting Users rep-batch-details.php

### ISSUE THREAD

**Issue by momothefox** [lirantal/daloradius#374]
While Going to a pre generated batch to have it csv exported 
the exported file only contains 
```
Batch Name, Username, Password
```
meanwhile if you exported the batch the from the generation page 
the password column is filled with (empty) 
also missing column 1 batch name 
```
Username,Password
79568233,(empty)
55631967,(empty)
98334709,(empty)
21269958,(empty)
97471615,(empty)
69240659,(empty)
```

**Comment by filippolauria** [comment]
Hi @momothefox ,
I have slightly modified this feature with the last PR. Check that out.

**Comment by momothefox** [comment]
> Hi @momothefox , I have slightly modified this feature with the last PR. Check that out.

Hi @filippolauria , Yes it is modified 
Exported CSV from Generation Page  Still exporting random Pin Codes with (empty) password typed in password column
But exported CSV file from listing batches and entering batch details exporting pin codes correctly without any other more columns. 
```

so i created another batch with user/passwords 

and tried exporting it from generation page working fine 
but trying exporting from entering batch details 
it exported only username column and no password field was found 

```
Username,Password
34054709,33416187
21562329,55199625
03579483,05416674
89388854,59661485
92245049,25766817
61624020,75881742
38140484,11041814
06957109,24025662
38306071,07329642
64188607,75139452
```

```
# batch name: 74574564, users num.: 39
Username
34054709
21562329
03579483
89388854
92245049
61624020
38140484
06957109
38306071
64188607
```

**Comment by filippolauria** [comment]
If you want to export your user/pass batch later, through the Batch Details page, you **must** save in the db cleartext creds, i.e. when you create the batch you have to choose Cleartext-Password as password type.
![image](https://user-images.githubusercontent.com/4223503/219623534-2d675e59-67f9-4ec5-8666-2f21e19d48ed.png)

Right after the creation of a user/pass batch, you can **always** (i.e. no matter what **Password Type** you select) download both CSV and PDF exports.

If you create a MAC addr/PIN code batch, you don't need the password.

**Comment by momothefox** [comment]
Yes you are right. 
i am not sure i did choose cleartext-password or not yesterday.. 
confirmed.
