### ISSUE TITLE
RTL - LTR

### ISSUE THREAD

**Issue by momothefox** [lirantal/daloradius#375]
Did you take in consideration in the layout the possibility for RTL Languages ? 
you know i have been working on Arabic Translation for daloRADIUS 

Also subnav is missing from language file and can not be translated

**Comment by filippolauria** [comment]
With the last PR I have introduced some LTR/RTL features.
Create a PR with your arabic language (ar.php). Also make sure to edit library/validation.php including the new language among allowed languages.

**Comment by momothefox** [comment]
Great 
I will setup my PR but after you include Subnav in English Language file.

**Comment by momothefox** [comment]
check out #384
