### ISSUE TITLE
Reports Page > General

### ISSUE THREAD

**Issue by momothefox** [lirantal/daloradius#376]
Missing Online Users.
You must type a username to display last connection attempts.
You must type a username to display top users.

**Comment by filippolauria** [comment]
This has been fixed with the latest PR.

**Comment by momothefox** [comment]
> This has been fixed with the latest PR.

Yes it is 
But still missing Online Users

**Comment by filippolauria** [comment]
Isn't this the menu item you are talking about?
![image](https://user-images.githubusercontent.com/4223503/219621305-dc374b36-c29e-4f0a-8216-2a68486e851f.png)

**Comment by momothefox** [comment]
Yes it is but it cannot be found here 

![bandicam 2023-02-17 15-26-07-409](https://user-images.githubusercontent.com/25464943/219664886-769420b3-a254-4008-a7dc-70aab44f0baa.jpg)

Am i missing something here ? 
must be some online users for the menu to appear ?!!

**Comment by filippolauria** [comment]
> must be some online users for the menu to appear ?!!
Exactly :)

**Comment by momothefox** [comment]
Confirmed :)

![bandicam 2023-02-17 16-27-19-000](https://user-images.githubusercontent.com/25464943/219681909-de2ffbc2-2988-4b8a-a603-fc76d5d809be.jpg)
