### ISSUE TITLE
Unable to add a new User Grouop

### ISSUE THREAD

**Issue by gregbinsd** [lirantal/daloradius#377]
I am a new user.  Running daloRADIUS - RADIUS Management version 2.0 beta / 9 Feb 2023.
There are many features that are not working, but one of them is I cannot add a group.  There is no place, no field, to type in the new group name.
The only group that exists is daloRADIUS-Disabled-Users.
I did not realize that I had chosen a beta version of daloRADIUS.  I will look for an older version.  Please recommend the best version for me to use.
Thank you.
Greg

**Comment by filippolauria** [comment]
Hello Greg,
daloRADIUS v2.0 is under development.
If you spot some features that are not working, please include part of your web server error.log file.

**Comment by gregbinsd** [comment]
Filippo,

Thank you for contacting me.  I eventually downloaded version 1.3 of daloRADIUS and was able to get it working.

I hope you can take a minute or two to answer a few questions.  Quick answers are fine ;-)

I bought your book!

Purchase Date: 16 February 2023
Invoice Number: E5C5AF58A9EA4E1E967970D4180B4017
Payment Terms: Paid In Full
Due Date: N/A
Sold To: ***@***.***


Purchases

Description: daloRADIUS User Guide
URL: http://leanpub.com/daloradius-user-guide<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fleanpub.com%2Fdaloradius-user-guide&data=05%7C01%7C%7C094950815a6c41b82be108db105aaab7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638121754538370530%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qfB34fnRefOSMbP3FIK2nLn09ZTP8OmOaz8hdGg0sto%3D&reserved=0>
Unit Price: $15.00 USD
Copies: 1
Item Total: $15.00 USD


Summary

Subtotal: $15.00 USD
Grand Total: $15.00 USD


I noticed that the book is dated May, 2011.


I want to setup daloRADIUS to support assigning VLANs to users.  I hope that the book will show me how to do this using the latest supported version of daloRADIUS, version 1.3.


Should I use version 1.3 or some other version?


Thank you,


Greg

________________________________

**Comment by filippolauria** [comment]
Hello Greg,
I am not an author of that book, but I think that other users have already dealt with the use case you propose.
IMHO, the new version I'm working on is the best. It still requires further testing, though, as you can see from the number of reported issues.
