### ISSUE TITLE
Hotspots

### ISSUE THREAD

**Issue by momothefox** [lirantal/daloradius#378]
No delete button after you select several Hotspots. mng-hs-list.php
if you go to remove hotspot page it is working fine 
but what is the need for select all / select none buttons without remove button 

Also if you try to edit and Hotspot  it returns 
MAC/IP address already in use

**Comment by filippolauria** [comment]
The delete button was missing also in other listing views.
I have fixed these issues in the last PR.

**Comment by momothefox** [comment]
> The delete button was missing also in other listing views. I have fixed these issues in the last PR.

yes delete button is back and working 

now for error that MAC is already used it is gone 

but there are several issues 

1- if you created Hotspot from mng-hs-new.php
*in contact info 
Owner Name, Owner Email, Manager Name and Manager Email 
*whatever you enter there it is not going to be stored in DB 
*Hotspot Type gets stored in DB but cannot be viewed from edit page although it is visible from listing hotspots page 
*Creation date and created by gets stored in DB 
* If hotspot information edited no update date or updated by is stored in DB 

2- if you created Hotspot from GIS Edit Map 
same as above except 
when created 1st time no creation date or admin 
when edited it is shown in DB Updated By and date

**Comment by momothefox** [comment]
Still one thing only 

Hotspot Type filed does not display data from mng-hs-edit.php

![bandicam 2023-02-17 15-20-19-022](https://user-images.githubusercontent.com/25464943/219663693-51fb2cba-ce15-4a2d-8d96-ab3fd7bd730e.jpg)

Although it is visible from mng-hs-list.php

![bandicam 2023-02-17 15-19-39-231](https://user-images.githubusercontent.com/25464943/219663596-1c257a73-47db-4f4a-9bcc-485db8f58e9b.jpg)

so if you edit Hotspot and did not retype hotspot type data  and applied changes it will simply  delete corresponding data from db
