### ISSUE TITLE
Get from repo or download from website

### ISSUE THREAD

**Issue by theScrabi** [lirantal/daloradius#38]
Hi there,

is it better do get daloRadius from this repository, or download the 2012 version from the website?

rgd schabi

**Comment by lirantal** [comment]
Definitely to get the version from here on github.

**Comment by theScrabi** [comment]
Is master stable then?

**Comment by lirantal** [comment]
As stable as can be with a code-base that old :-)
I'd say just try it and I'll try to help if you get into any issues.

**Comment by theScrabi** [comment]
All right sounds good :) lets do it so.
