### ISSUE TITLE
User Search 

### ISSUE THREAD

**Issue by momothefox** [lirantal/daloradius#382]
Some thing wrong with mng-search.php 

![bandicam 2023-02-17 16-33-26-072](https://user-images.githubusercontent.com/25464943/219683881-a32ae9c7-d6ee-4661-8c28-88dc667dda0d.jpg)

Although user exists 

![bandicam 2023-02-17 16-33-39-744](https://user-images.githubusercontent.com/25464943/219683945-ae596759-1f6b-4be8-97a3-f36f0f713355.jpg)

**Comment by filippolauria** [comment]
List/search features doesn't deal with batch users.
With #387 I have introduced a new feature that allows you to deal with batch user (list, search, enable, disable, delete).
![image](https://user-images.githubusercontent.com/4223503/221142357-6c6e6748-12b4-4452-9c86-9c1fc80a317d.png)
