### ISSUE TITLE
Is there a plugin interface? I want to extend daloradius to add a simple REST API

### ISSUE THREAD

**Issue by deweydb** [lirantal/daloradius#388]
Hello,

I am using daloradius as a management tool for our freeradius instance and I want to have the ability to add and delete radius users via an API endpoint. I could of course do this many different ways, independent of daloradius on the same server via other web services that I build, but as the server already contains daloradius it seemed most appropriate to leverage it. 

It seems right now daloradius frontend sends a request like this to make a new user:
```
curl 'http://hostname.example.com/daloradius/mng-new.php'   
-H 'Cookie: PHPSESSID=<redacted>' 
--data-raw  'authType=userAuth&username=someone&password=hunter2&passwordType=SHA1-Password&groups%5B%5D=&submit=Apply' 
```

So technically my 3rd party scripts could first login:
`curl 'http://hostname.example.com/daloradius/dologin.php'   --data-raw 'operator_user=administrator&operator_pass=<redacted>' `

then get the php session cookie in the response, and then do the above post request. but that's pretty janky.
I would rather extend daloradius with an API functionality, so that my third party scripts can authenticate with a key.

**Comment by bingy92** [comment]
Hi,

I am interested in a REST interface as well as this would bring a lot of flexibility to how we could use daloradius. I am not a hardcore developer but can offer some technical input. 

Shall we look deeper into this?

**Comment by filippolauria** [comment]
Hi @deweydb and @bingy92 ,
your contributes will be really appreciated.
