### ISSUE TITLE
Adding Custom Attribute

### ISSUE THREAD

**Issue by momothefox** [lirantal/daloradius#389]
While Adding Custom Attribute in profile page 
Failed to load Op and Target Values
![bandicam 2023-02-27 23-46-59-482](https://user-images.githubusercontent.com/25464943/221693830-b8039ba6-a5db-4b87-aae4-6b77735bbb98.jpg)
![bandicam 2023-02-27 23-47-03-480](https://user-images.githubusercontent.com/25464943/221693823-5df34ba4-10ec-401c-b159-ed8e9cfb016d.jpg)

**Comment by filippolauria** [comment]
This has been addressed in #409

**Comment by momothefox** [comment]
Confirmed 👍
