### ISSUE TITLE
ACL page does not save

### ISSUE THREAD

**Issue by ioudas210** [lirantal/daloradius#39]
When using the acl page for an operator. Certain options when set to disable make the acl page hang and not process the request. What is the fix for this?

**Comment by lirantal** [comment]
I'm not aware of any such issue. Can you help me debug it and provide more information?
Which options exactly cause this when you toggle them on?

The only thing that page is doing is querying the DB, there's no other logic there AFAIR.
Maybe the problem is that if you toggle a lot of the options then it hits the query parameters limit in PHP?

**Comment by ioudas210** [comment]
Sure, let me provide some more information.

I have tried this with a single change. Right now im in the operator ACL page. I select 


Reporting | Status | rep_stat_server.

Select disabled. Then once i hit apply. the page stops entirely. If i refresh the page. I get notification that the form data will not be saved and it just sits indefinitely. 

Id say literally 1/2 the options via a single select disabled do this.


Management | Proxys | mng_rad_proxys_edit

Accounting | General | acct_nasipaddress

Are other examples of this which just hang the page entirely.

It would also be nice to mass disable a lot of options. Instead of having 100 manual selections.


If helpful i can provide video and a list of options that do not work by default.






Id also note that manually disabling 100 options by hand is beyond tedious.

**Comment by ioudas210** [comment]
Did some more testing on this bug. Once a user applies a setting in this page. The get for the url for the username disappears on edit page. The url goes from:  config-operators-edit.php?operator_username=frontdesk
to: http://serverurl/config-operators-edit.php

And no other edits can be placed at this time, even when looking at the edit view.

I noticed this also occurs in other pages. Making me go back through the menus.

Feel free to close if this is expected behavior, but that being said. Im a computer programmer who found it more than confusing.

**Comment by lirantal** [comment]
you said:
> Select disabled. Then once i hit apply. the page stops entirely. If i refresh the page. I get notification that the form data will not be saved and it just sits indefinitely.

is it actually submitting and saving or not?
if it's not, I'd check about the php setting for the maximum amount of HTML attributes that can be sent, it probably hit that limit (IIRC around 1024 or something like that).
Also, always check the logs and try to figure out why exactly the app is crashing.

The username query parameter that disappears from the URL is a side-effect and I think this is how it works but TBH I'm not sure as I didn't use it for a while.
