### ISSUE TITLE
Adding New NAS

### ISSUE THREAD

**Issue by momothefox** [lirantal/daloradius#390]
Missing NAS Types 
![bandicam 2023-02-28 00-36-00-836](https://user-images.githubusercontent.com/25464943/221701668-68b6a6c0-fe57-4d37-bf99-0acc8e53c396.jpg)

**Comment by filippolauria** [comment]
Hello @momothefox 
the list you see is taken from freeradius 3.0.21.
What type is missing?

**Comment by momothefox** [comment]
Hi @filippolauria Great effort you are doing for daloRADIUS.

my mistake the list exists but because "other" is selected by default i did not notice i have to delete "other" to see the list 
i am closing this 👍 

![bandicam 2023-03-07 19-35-46-719](https://user-images.githubusercontent.com/25464943/223503227-da2d64ca-7ca1-40e4-b4e3-12a3c88c34db.jpg)
