### ISSUE TITLE
first time browsing daloradius login error

### ISSUE THREAD

**Issue by Verlights** [lirantal/daloradius#395]
I have deployed Apache/2.4.54, MySQL 8.0.32, PHP 8.2.3, FreeRadius 3.0.21, and daloRADIUS 2.0 beta on Debian 11 (kernel 5.10.0-21-amd64). The daloRADIUS package is located at /var/www/html/daloradius with chown www-data:www-data

The first time I browse the webpage  http://IP-address/daloradius and it shows 404 not found and redirect to http://IP-address/login.php

I tried to verify the PHP code and modify this file /var/www/html/daloradius/library/checklogin.php
```
    // implement a sort of "dynamic redirect finder" based on the number of "/" in the PHP_SELF value
    $count = substr_count($_SERVER['PHP_SELF'], "/", 1);
    $location = str_repeat("../", $count) . "daloradius/login.php";

    header("Location: " . $location);
    exit;
}
```
Now, I can access the login page normally
http://IP-address/daloradius redirect to http://IP-address/daloradius/login.php

**Comment by filippolauria** [comment]
Hello @Verlights ,
thanks for your feedback.
This has been addressed in #409
