### ISSUE TITLE
Requests form nas are not arriving

### ISSUE THREAD

**Issue by santiarenos** [lirantal/daloradius#398]
I have installed freeradius and daloradius witch myql and I access to daloradius web perfectly but it seems requests not arriving to freeradius.
If I execute

**radtest user password localhost 1812 test123:**

Sent Access-Request Id 150 from 0.0.0.0:35171 to 127.0.0.1:1812 length 75
        User-Name = "user"
        User-Password = "password"
        NAS-IP-Address = 10.0.0.216
        NAS-Port = 1812
        Message-Authenticator = 0x00
        Cleartext-Password = "password"
**(0) No reply from server for ID 150 socket 3**

Any ideas what is not correct??

**Comment by momothefox** [comment]
@santiarenos check if Freeradius service is running. 
you can check out all services related through rep-stat-services.php
