### ISSUE TITLE
User portal not compartible with PHP7

### ISSUE THREAD

**Issue by theScrabi** [lirantal/daloradius#40]
https://github.com/lirantal/daloradius/blob/8fe8cb45fb55c3f66ae45a5198f575f5fdb7847d/daloradius-users/include/management/pages_common.php#L109

This line failes dueto a deprecated function call of [ereg_replace()](http://php.net/manual/en/function.ereg-replace.php) according to [this](http://php.net/manual/en/function.ereg-replace.php) site [preg_replace()](http://php.net/manual/en/function.preg-replace.php) should be used.

**Comment by lirantal** [comment]
Thanks! Applied a fix now in master branch.
