### ISSUE TITLE
Access-reject when we use access-period attributes

### ISSUE THREAD

**Issue by khant0** [lirantal/daloradius#400]
FreeRADIUS Version 3.0.26
mysql  Ver 15.1 Distrib [10.6.12-MariaDB]
Dalo ver 1.3

<img width="472" alt="access-reject" src="https://user-images.githubusercontent.com/126749652/222342931-b94a6540-434e-47d4-9f01-c92a3803ea8a.png">
<img width="845" alt="Screenshot_2" src="https://user-images.githubusercontent.com/126749652/222346252-a80fb5ca-ec08-461f-b667-022da0a5dfcc.png">

**Comment by momothefox** [comment]
@khant0 check that you have correct sqlcounter for this attribute 
/etc/freeradius/3.0/mods-enabled/sqlcounter

**Comment by momothefox** [comment]
@khant0 check that you have correct sqlcounter for this attribute
/etc/freeradius/3.0/mods-enabled/sqlcounter
for me >
``` 
sqlcounter accessperiod {
sql_module_instance = sql
dialect = ${modules.sql.dialect}

counter_name = Max-Access-Period-Time
check_name = Access-Period
key = User-Name
reset = never

$INCLUDE ${modconfdir}/sql/counter/${dialect}/${.:instance}.conf
}
```
Note that sqlcounter accessperiod can be found in 
/etc/freeradius/3.0/mods-config/sql/counter/mysql/accessperiod.conf

```
query = "\
SELECT UNIX_TIMESTAMP() - UNIX_TIMESTAMP(AcctStartTime) \
FROM radacct \
WHERE UserName='%{${key}}' \
ORDER BY AcctStartTime LIMIT 1"
```

so this counter works after accounting start 
AcctStartTime

you need to test this out from actual NAS or generate acctstart packet

**Comment by khant0** [comment]
@momothefox
i don't have accessperiod.conf   under /etc/freeradius/3.0/mods-config/sql/counter/mysql/
so i manually created accessperiod.conf under /etc/freeradius/3.0/mods-config/sql/counter/mysql/
And insert it 
-----------------------------------------
sqlcounter accessperiod {
sql_module_instance = sql
dialect = ${modules.sql.dialect}

counter_name = Max-Access-Period-Time
check_name = Access-Period
key = User-Name
reset = never

$INCLUDE ${modconfdir}/sql/counter/${dialect}/${.:instance}.conf
}
query = "\
SELECT UNIX_TIMESTAMP() - UNIX_TIMESTAMP(AcctStartTime) \
FROM radacct \
WHERE UserName='%{${key}}' \
ORDER BY AcctStartTime LIMIT 1"
---------------------------------------
After that i got access- accept but the user who use access-period attribute still doesn't work.

Any idea?

**Comment by momothefox** [comment]
Hi @khant0 
something doesn't look right 
what is the profile name ? 
did you add the attribute Access-Period with correct op and target ? 
Access-Period op is := and target is check 
as it is freeradius internal attribute 
i wonder how the profile assigned to the user looks like ? 
more info needed. 

note that you will have to put the counter name in freeradius config file 
/etc/freeradius/3.0/sites-enabled/default
under section 

`authorize {
`

you should have all your counter like this 
```
	expiration
	logintime
	dailycounter
	accessperiod
	monthlycounter
	noresetcounter
	expire_on_login

```
