### ISSUE TITLE
Attribute non-existent

### ISSUE THREAD

**Issue by dleventidis** [lirantal/daloradius#402]
Hello,

Trying to select attributes from dictionary throws an Attribute non-existent or inconsistency in your vendor attribute dictionary as it shows the attached screenshot. Mostly the issue is on dictionary.XXXX Vendors.
In MySQL Database the data are imported correctly.

![dalo2](https://user-images.githubusercontent.com/76202817/222402271-b195864a-9f70-4755-a04b-283ba24be71a.jpg)

**Comment by PlanetDigitalBS** [comment]
I have the same Issue!
Installed a new Server with Daloradius and importet the "old" Database.
Everything works as it should, without 3 Issues:
- Attributes failure like in the Screenshot
- Existing Notes from Users could not be changed and new Users could not add any notes.
- Disconnectiong from Users isnt Working (radius)

![Bildschirm­foto 2023-03-03 um 09 53 36](https://user-images.githubusercontent.com/70692835/222678058-2cacae4e-b1f1-479f-b4cb-7f8630566be6.png)
![Bildschirm­foto 2023-03-03 um 10 00 55](https://user-images.githubusercontent.com/70692835/222678089-51b6fc6b-3a30-4efa-a3c5-446dc96499e7.png)


thanks 4 help :-)

**Comment by filippolauria** [comment]
Hello all,
thanks for your feedback.
What you reported has been fixed in #409.
If the attribute is not present in the db, though, a warning will still (and always) pop up.

**Comment by dleventidis** [comment]
It looks like it isn't fixed
