### ISSUE TITLE
CRON Status

### ISSUE THREAD

**Issue by bmwfrs** [lirantal/daloradius#404]
i have error enabling the crontab for stale sessions please help!

rror: crontab is not configured for www-data
Details: no crontab for www-data.
![image](https://user-images.githubusercontent.com/67933182/222584666-88a5af76-dce8-4e31-9bed-8ccb413a5355.png)

**Comment by filippolauria** [comment]
Hello @bmwfrs ,
thanks for your feedback.

This has been addressed in #409.
