### ISSUE TITLE
Docker compose errors

### ISSUE THREAD

**Issue by prabath84** [lirantal/daloradius#407]
[docker-error-info.txt](https://github.com/lirantal/daloradius/files/10893699/docker-error-info.txt)

I'm getting attached error when executing docker-compose. @lirantal Could you please have a look ?

**Comment by filippolauria** [comment]
A new Dockerfile, compliant with version 2.0 beta, should be created.

**Comment by filippolauria** [comment]
Hi @prabath84  .
As I said in #406  

> The point is this:
> we are looking for people that contribute to project creating a new `Dockerfile`. This `Dockerfile` could be based on a `Debian 11 container`, and created according to what I have written in `INSTALL.debian.md`.
> I don't think it is a difficult task. If you are able to do it, you contribution will be really appreciated.
