### ISSUE TITLE
Debian - Errors post install

### ISSUE THREAD

**Issue by thomasbruchet** [lirantal/daloradius#408]
Hello,
I've just finished the install of daloradius according the process in INSTALL.debian and some modification is needed that are not in the process.

```
chown www-data:www-data /var/www/daloradius -R
chmod 644 /var/www/daloradius/library/daloradius.conf.php
```

and modify the line "secret = testing123" with our secret
```
sudo vi  /etc/freeradius/3.0/clients.conf
```

When we change this setting the information into daloradius with webinterface, the parameter is not modified and we receive error: "Ignoring request to auth address"

**Comment by filippolauria** [comment]
Hello @thomasbruchet ,
thanks for your feedback.
While it is necessary to change ownership for daloradius.conf.php (thanks again for having pointed that out), there's no need to change ownership of the whole daloradius dir, unless others cannot read the files (which is not the default in debian 11).

Along with other reported issues, in #409 I have added the command you suggested and fixed the ability to change the secret key from the web interface.

**Comment by thomasbruchet** [comment]
Thank you very much for your answer.
