### ISSUE TITLE
Hotspot Comparison Charts not loading

### ISSUE THREAD

**Issue by momothefox** [lirantal/daloradius#411]
### **I wonder how it looks like, seems promising.**

![bandicam 2023-03-08 11-22-47-146](https://user-images.githubusercontent.com/25464943/223674468-4742e11d-ffd7-4f08-b645-11eb78d1f4ad.jpg)
![bandicam 2023-03-08 11-21-42-229](https://user-images.githubusercontent.com/25464943/223674502-33457c61-4bf0-4e72-9585-98aa4f00defd.jpg)
![bandicam 2023-03-08 11-21-39-892](https://user-images.githubusercontent.com/25464943/223674521-404078bc-4c86-4487-b1a7-8531974f0473.jpg)
![bandicam 2023-03-08 11-21-36-734](https://user-images.githubusercontent.com/25464943/223674548-8870dc91-4563-4983-b7ab-1e2060b33dd6.jpg)
![bandicam 2023-03-08 11-21-25-755](https://user-images.githubusercontent.com/25464943/223674580-b5314ae7-df6b-421d-9648-7ccce7703e9d.jpg)

**Comment by filippolauria** [comment]
On my end it works just fine. Please, provide some part of the error.log file.

**Comment by momothefox** [comment]
after looking into error log file 
found out 

/operators/library/graphs/hotspot_details.php
lines 83,84
```
include_once('jpgraph/jpgraph.php');
include_once('jpgraph/jpgraph_pie.php');
```

wrong path it is moved to daloradius/common/library/jpgraph/jpgraph_pie.php

it should be 

    include_once('../../../common/library/jpgraph/jpgraph.php');
    include_once('../../../common/library/jpgraph/jpgraph_pie.php');

worked great after fixing it please update it. thanks.
