### ISSUE TITLE
importing fr3-mysql-freeradius.sql fails on mysql

### ISSUE THREAD

**Issue by momothefox** [lirantal/daloradius#412]
executing schema import command 
 
mysql -u root radius < /var/www/html/daloradius/contrib/db/fr3-mysql-freeradius.sql

returns 

ERROR 1067 (42000) at line 217: Invalid default value for 'lastaccounting'

mysql -V
mysql  Ver 8.0.30-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))

**Comment by filippolauria** [comment]
That schema is provided by freeRADIUS. I tested it on debian 11 and with mariadb-server instead of mysql-server it worked just fine. Try using mariadb-server on Ubuntu. If you are installing a fresh instance, try to write a INSTALL.ubuntu.md guide (just like the INSTALL.debian.md).

**Comment by momothefox** [comment]
i think i was wrong about this, there is something related to my setup sorry for bothering.
