### ISSUE TITLE
Log File directory permissions

### ISSUE THREAD

**Issue by Supergumby14** [lirantal/daloradius#413]
Hi.  Linux noob here

Followed the INSTALL.debian.md instructions on a fresh install today and all is well until step 21:
`systemctl enable apache2 
systemctl restart apache2`

I get:
`(2)No such file or directory: AH02291: Cannot access directory '/daloradius/users/' for error log of vhost defined at /etc/apache2/sites-enabled/users.conf:1`
`(2)No such file or directory: AH02291: Cannot access directory '/daloradius/operators/' for error log of vhost defined at /etc/apache2/sites-enabled/operators.conf:1`

I'm guessing this is a permissions error from step 14:
`mkdir -p /var/log/apache2/daloradius/{users,operators}`

Thanks for any assistance.

**Comment by filippolauria** [comment]
Hello @Supergumby14 ,
There was a little typo in the `install.DEBIAN.md`. Repeat installation steps. I think you can start over from step number 12.

**Comment by Supergumby14** [comment]
That fixed it.

Thanks!
