### ISSUE TITLE
Batch Users Management Issues

### ISSUE THREAD

**Issue by momothefox** [lirantal/daloradius#414]
**Checking Enable User Portal Login checkbox does not enter 1 value in `enableportalogin` column 
Checking Enable User Update checkbox does not enter 1 value in `changeuserinfo` column 
I am not sure what it should be 1 and 0 or not and i am not sure what it should do. 
Also `creationdate` and `creationby` are untouched.**

**One more thing `Number of instances to create` must be even number? just wondering why.**

![bandicam 2023-03-09 05-24-38-973](https://user-images.githubusercontent.com/25464943/223908742-e6576e9d-888d-4e30-993d-27c80aeb62a2.jpg)

![bandicam 2023-03-09 05-14-37-956](https://user-images.githubusercontent.com/25464943/223908567-9c3e34ee-d8c5-4abe-a2db-ddfcaf68eba4.jpg)

**Comment by filippolauria** [comment]
This should have been fixed in #420

**Comment by momothefox** [comment]
![bandicam 2023-03-10 14-10-24-412](https://user-images.githubusercontent.com/25464943/224312792-c8e347a4-52e8-46f4-b7a3-0418a621340a.jpg)

changeuserinfo yes 
enableportallogin no 
creation date no

**Comment by momothefox** [comment]
Fixed Perfectly Thanks #421
