### ISSUE TITLE
Missing Favicon in User Portal

### ISSUE THREAD

**Issue by momothefox** [lirantal/daloradius#415]
Missing Favicon in user portal

**Comment by filippolauria** [comment]
@momothefox I have fixed some typo in the installation steps written in `INSTALL.debian.md`.
Ensure virtual hosts are created as shown there (for instance with the directive `Options -Indexes +FollowSymLinks`).

**Comment by momothefox** [comment]
@filippolauria  Hi i updated my config files with no success try to clear history of your browser 
(delete downloaded files for all time)

**Comment by filippolauria** [comment]
The icon is displaying just fine. I haven't tested a lot of browseres, though.
What browser on your end has this issue? Have you tried with multiple browsers?

**Comment by momothefox** [comment]
Issue has gone by latest git 
maybe my mistake sorry.

**Comment by momothefox** [comment]
my bad sorry for bother.
