### ISSUE TITLE
config-backup-createbackups.php

### ISSUE THREAD

**Issue by momothefox** [lirantal/daloradius#416]
Create Backups
For FreeRADIUS checked Tables, backup succeeded 

`Successfully created backup for 7 table(s) [radcheck, radgroupreply, radgroupcheck, radusergroup, radacct, nas, radpostauth]`

If Both FreeRADIUS and daloRADIUS are checked, backup succeeded

`Successfully created backup for 22 table(s) [radcheck, radgroupreply, radgroupcheck, radusergroup, radacct, nas, radpostauth, userinfo, dictionary, realms, billing_plans, batch_history, billing_plans_profiles, userbillinfo, invoice_status, invoice_type, payment_type, operators, operators_acl, operators_acl_files, hotspots, node]`

But if you try to backup only daloRADIUS tables, Fails with 

![bandicam 2023-03-09 06-52-30-509](https://user-images.githubusercontent.com/25464943/224111541-f6a784ab-6d44-4b84-8c13-a66a9e0a2d32.jpg)

**Comment by filippolauria** [comment]
I don't see any problem there, on my end.
Try to use #421, if the problem is still there you need to share part of your `/var/log/apache2/daloradius/operators/error.log` file.

**Comment by momothefox** [comment]
Issue has gone by latest git
maybe my mistake sorry
