### ISSUE TITLE
Billing improvements are welcome?

### ISSUE THREAD

**Issue by MiguelVis** [lirantal/daloradius#42]
Hi!

I was thinking about doing some improvements to billing options, but I would like to know if there is a real interest in that - ie:

- Invoicing preview (in addition to downloading and sending by email as pdf).
- Amount and prices format including number of decimals, decimal separator, thousands separator, currency symbol.
- Company name, address, legal identification, etc.
- Name of tax (VAT, etc.).

Are you using Daloradius billing options? Any additional ideas? Or it would be better if I make an effort in another area of Daloradius?

Thanks.

**Comment by MiguelVis** [comment]
I am already working on that, but before I do a pull request, I would to know if there are any suggestions or comments regarding this matter.

I have modified the code to support a "new style" invoicing template system, but supporting the current one also, for compatibilty reasons.

There are a lot of new fields you can use in the templates.

Now it's possible to set in the configuration file two templates: one for the invoice and another for the invoice items. You can configure them for the default location or for any other location you have defined.

Any comment on this will be very appreciated.

Thanks.

PD: The attached image shows the output of an invoice using the new template system.

PD2: One problem I have seen is that the user table has not any field related to VAT number, company id or equivalent.

![invoice_preview](https://user-images.githubusercontent.com/4165032/34233268-a45d47a8-e5e4-11e7-96fb-5864a8f6a413.jpg)

**Comment by lirantal** [comment]
Looks cool. I'll be happy to merge if you open a PR :-)

**Comment by lirantal** [comment]
I merged #43 !

**Comment by MiguelVis** [comment]
Thanks Liran!
