### ISSUE TITLE
Expire-After attribute

### ISSUE THREAD

**Issue by esaaprillia** [lirantal/daloradius#424]
@filippolauria 

can you add Expire-After in profile attribute

https://github.com/FreeRADIUS/freeradius-server/issues/2675

**Comment by esaaprillia** [comment]
@filippolauria 
How to?

**Comment by esaaprillia** [comment]
Ping @filippolauria 

I don't understand adding this attribute. can you try adding this attribute

**Comment by momothefox** [comment]
@esaaprillia  go to Management > Attributes > New Vendor attribute > 
And Fill in the data

**Comment by esaaprillia** [comment]
@momothefox 
have you tried it? i want your screenshot how to fill

**Comment by esaaprillia** [comment]
![Screenshot_2023-03-16_180110](https://user-images.githubusercontent.com/122262432/225583013-d80ae844-5e57-4384-95ac-9f999f481b6a.jpg)

**Comment by esaaprillia** [comment]
I don't know the vendor or Expired-After dictionary

**Comment by momothefox** [comment]
you can simply type in a new vendor name for your self 
Ask your self these questions. 
what do i want exactly? 
do you want to count starting from 1st login? 
do you want to count several sessions? 
do you want the user to expire in a specific date?

**Comment by esaaprillia** [comment]
@momothefox 
Set an account to expire T seconds after first login.

**Comment by esaaprillia** [comment]
thank you I understand and I have tried it and it works

**Comment by momothefox** [comment]
**1- This should be in your /etc/freeradius/3.0/mods-enabled/sqlcounter file** 

```
sqlcounter expire_on_login {
	sql_module_instance = sql
	dialect = ${modules.sql.dialect}

	counter_name = Expire-After-Initial-Login
	check_name = Expire-After
	key = User-Name
	reset = never

	$INCLUDE ${modconfdir}/sql/counter/${dialect}/${.:instance}.conf
}

```

**2- This is your query at /etc/freeradius/3.0/mods-config/sql/counter/mysql/expire_on_login.conf**

```
query = "\
	SELECT IFNULL( MAX(TIME_TO_SEC(TIMEDIFF(NOW(), acctstarttime))),0) \
	FROM radacct \
	WHERE UserName='%{${key}}' \
	ORDER BY acctstarttime \
	LIMIT 1;"

```

**3- Put this attribute in a profile `Expire-After` and assign := op for it and type in seconds count** 


![bandicam 2023-03-16 12-57-08-517](https://user-images.githubusercontent.com/25464943/225596739-d5832372-9fce-4022-a379-5d4cdbfd9561.jpg)


**4- If you want to add it permanently so you won't type it every time.** 

 
![bandicam 2023-03-16 12-15-46-516](https://user-images.githubusercontent.com/25464943/225597043-3182d589-96e8-4ef3-8db9-ca9e9b4c0113.jpg)

![bandicam 2023-03-16 12-16-14-645](https://user-images.githubusercontent.com/25464943/225597141-38a1be67-4b04-4c23-8675-bd0bb18201e8.jpg)

![bandicam 2023-03-16 12-16-00-620](https://user-images.githubusercontent.com/25464943/225597113-a475f738-f402-4d97-b812-f3f7de56eb4b.jpg)

**Comment by esaaprillia** [comment]
Thanks
@momothefox
