### ISSUE TITLE
/daloradius/library/ directory missing

### ISSUE THREAD

**Issue by fitzwar** [lirantal/daloradius#426]
Hi,

I've noticed in the latest version when completing the install the /library/ directory is missing. Can someone confirm if this directory is missing from the latest install ?

Has the daloradius.conf.php file moved ?

**Comment by filippolauria** [comment]
Hi @fitzwar ,
the whole application has been split in 2 main parts: `operators` and `users`. They both share a `common` part of code.
You can find this structure in the `app` directory. The file `INSTALL.debian.md` describes how to install the application in a Debian 11 enviroment, using Apache 2 and two port-based vhosts: the first one on the port 8000 for operators and the other one on the port 80 for users.

**Comment by fitzwar** [comment]
Thanks, is Ubuntu 22.04 supported with this setup ?

**Comment by filippolauria** [comment]
I haven't tested it personally.
You can follow INSTALL.debian.md for an Ubuntu system, then write here what you find out.

**Comment by esaaprillia** [comment]
i tested on openwrt using php8.1.16 and uhttpd as webserver i haven't tested using apache2 on openwrt. What I see is that the web UI looks less good if you use Android, the view is the same if you use desktop mode on Google Chrome. looks like index.php is not in use anymore

![Screenshot_2023-03-18_174015](https://user-images.githubusercontent.com/122262432/226098426-84d734d0-b1b8-43fb-99bb-83260d37bf1d.jpg)
![Screenshot_2023-03-18_174040](https://user-images.githubusercontent.com/122262432/226098516-29dbab68-1ca0-4685-b44f-9b49ed81d725.jpg)
![Screenshot_2023-03-18_174117](https://user-images.githubusercontent.com/122262432/226098555-5644b998-76bf-4cb0-b478-1455f6b60cd9.jpg)
![Screenshot_2023-03-18_174212](https://user-images.githubusercontent.com/122262432/226098574-93e4291f-9b4c-4c19-bf3a-6026ca7e6dfe.jpg)
![Screenshot_2023-03-18_174223](https://user-images.githubusercontent.com/122262432/226098582-67f2a1b4-06f9-402b-9d34-a4b5c67a73c1.jpg)
![Screenshot_2023-03-18_174236](https://user-images.githubusercontent.com/122262432/226098592-1c0b3b29-8801-4454-b985-20b0c57a4a2c.jpg)

**Comment by fitzwar** [comment]
Tested on Ubuntu 22.04 but everytime it crashing the MariaDB database service

**Comment by fitzwar** [comment]
I have to say, this new change has affect 1,000's of users globally because all the documentation/ blogs etc all have instructions for the previous installation method. Is there an option to revert back to the old installation method as i'm seeing so many new users being affected?

**Comment by esaaprillia** [comment]
@fitzwar 
you can use daloradius version 1.3

**Comment by fitzwar** [comment]
@esaaprillia thanks, is there instructions on deploying v 1.3 ?

**Comment by esaaprillia** [comment]
https://www.google.com/amp/s/computingforgeeks.com/how-to-install-freeradius-and-daloradius-on-ubuntu/%3famp

**Comment by fitzwar** [comment]
Thanks, in the tutorial you shared it references to get the master zip: 
wget https://github.com/lirantal/daloradius/archive/master.zip

What would be the master zip 1.3 ?

**Comment by esaaprillia** [comment]
> Thanks, in the tutorial you shared it references to get the master zip: wget https://github.com/lirantal/daloradius/archive/master.zip
> 
> What would be the master zip 1.3 ?

https://github.com/lirantal/daloradius/tree/1.3

**Comment by fitzwar** [comment]
Correct URL to Zip for anyone else is: https://github.com/lirantal/daloradius/archive/refs/tags/1.3.zip

**Comment by filippolauria** [comment]
> i tested on openwrt using php8.1.16 and uhttpd as webserver i haven't tested using apache2 on openwrt. What I see is that the web UI looks less good if you use Android, the view is the same if you use desktop mode on Google Chrome. looks like index.php is not in use anymore
> 
> ![Screenshot_2023-03-18_174015](https://user-images.githubusercontent.com/122262432/226098426-84d734d0-b1b8-43fb-99bb-83260d37bf1d.jpg) ![Screenshot_2023-03-18_174040](https://user-images.githubusercontent.com/122262432/226098516-29dbab68-1ca0-4685-b44f-9b49ed81d725.jpg) ![Screenshot_2023-03-18_174117](https://user-images.githubusercontent.com/122262432/226098555-5644b998-76bf-4cb0-b478-1455f6b60cd9.jpg) ![Screenshot_2023-03-18_174212](https://user-images.githubusercontent.com/122262432/226098574-93e4291f-9b4c-4c19-bf3a-6026ca7e6dfe.jpg) ![Screenshot_2023-03-18_174223](https://user-images.githubusercontent.com/122262432/226098582-67f2a1b4-06f9-402b-9d34-a4b5c67a73c1.jpg) ![Screenshot_2023-03-18_174236](https://user-images.githubusercontent.com/122262432/226098592-1c0b3b29-8801-4454-b985-20b0c57a4a2c.jpg)

The recommended backend is: Debian 11 / Apache 2.4 / PHP 7.4 / MariaDB 15.1.
The frontend uses [Bootstrap v.5.3 frontend toolkit](https://getbootstrap.com/docs/5.3/getting-started/introduction/) and it has successfully tested on Ubuntu Linux, Windows 11 with Mozilla Firefox and Google Chrome.

From your screenshots, it looks like that some network information cannot be successfully loaded. We can debug this and fix the code. If you want, you can share the output of this command:

```bash
for iface in $(cat /proc/net/dev | grep ":" | cut -d':' -f1); do echo "$iface:"; ip addr show $iface; done
```

**Comment by esaaprillia** [comment]
@filippolauria 

if I have time later I will try it using php7 apache2.4 mariadb15 on openwrt.

--------------------------------------------------
```
root@OpenWrt:~# for iface in $(cat /proc/net/dev | grep ":" | cut -d':' -f1); do

 echo "$iface:"; ip addr show $iface; done
teql0:
5: teql0:  mtu 1500 qdisc noop state DOWN qlen 100
    link/void 
eth0:
2: eth0:  mtu 1500 qdisc mq master br-lan state UP qlen 1000
    link/ether 00:15:18:01:81:31 brd ff:ff:ff:ff:ff:ff
eth1:
6: eth1:  mtu 1500 qdisc fq_codel state UNKNOWN qlen 1000
    link/ether 0c:5b:8f:27:9a:64 brd ff:ff:ff:ff:ff:ff
    inet 192.168.8.100/24 brd 192.168.8.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::e5b:8fff:fe27:9a64/64 scope link 
       valid_lft forever preferred_lft forever
sit0:
3: sit0@NONE:  mtu 1480 qdisc noop state DOWN qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
br-lan:
7: br-lan:  mtu 1500 qdisc noqueue state UP qlen 1000
    link/ether 00:15:18:01:81:31 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.1/24 brd 192.168.1.255 scope global br-lan
       valid_lft forever preferred_lft forever
    inet6 fdfd:e8a5:6410::1/60 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::215:18ff:fe01:8131/64 scope link 
       valid_lft forever preferred_lft forever
lo:
1: lo:  mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
ip6tnl0:
4: ip6tnl0@NONE:  mtu 1452 qdisc noop state DOWN qlen 1000
    link/tunnel6 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00 brd 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
root@OpenWrt:~# 
```

**Comment by esaaprillia** [comment]
@filippolauria 

I have tried it seems there is no problem anymore. only if I use Google Chrome on Android it looks very ugly

![Screenshot_2023-04-05_090216](https://user-images.githubusercontent.com/122262432/229955347-bda89994-50da-4950-ae6f-5708e7749d17.jpg)
