### ISSUE TITLE
Ubiquiti

### ISSUE THREAD

**Issue by nickabocker171** [lirantal/daloradius#429]
Anyone here have any insights on using DaloRadius with Ubiquiti Airmax products? I know this may be more the Freeradius but i have been  struggling to get a Airmax radio to auth and work correctly

nick

**Comment by momothefox** [comment]
@nickabocker171

**Comment by momothefox** [comment]
@nickabocker171 
check out /var/log/freeradius/radacct/10.10.9.62/auth-detail
see what attributes being sent by the Airmax
add a profile to check and reply auth request. 
and then do the same with /var/log/freeradius/radacct/10.10.9.62/detail
