### ISSUE TITLE
Custom Attributes not parsed on COA

### ISSUE THREAD

**Issue by mherb63** [lirantal/daloradius#434]
When I try to enter a custom attribute via the disconnect user feature, the attribute name is missing.

![image](https://user-images.githubusercontent.com/1205814/229640741-d2eb7e2a-7914-46fb-970b-0d16e39094f2.png)

**Comment by Focuslinkstech** [comment]
@mherb63 please is this a new daloradius interface or did you change the template to meet this design? I love the interface. How can I change it to look like yours?

**Comment by mherb63** [comment]
@Focuslinkstech I just installed the latest version using the instructions found here: https://github.com/lirantal/daloradius/blob/master/INSTALL.debian.md

**Comment by Malto4** [comment]
Bump this issue, the same is happening to me when using: Framed-IP-Address=10.10.10.10
Only '10.10.10.10' appears

**Comment by filippolauria** [comment]
#488 should have fixed the issue

**Comment by Malto4** [comment]
Hello @filippolauria ,
I have proceeded to update my daloRADIUS instance following the user-manual (from version 0.9-9), first backing up daloradius.conf.php, then the database, and finally re-downloading the git repository (previously deleting /var/www/daloradius), and now when I try to disconnect a user, the username field doesn't show any users.
In case it were a database issue (even though the database hasn't been modified), I created a new user, and still nothing.
Have also tried using a different web browser, and still nothing.

**Comment by filippolauria** [comment]
Is the user you're trying to disconnected, connected?

**Comment by Malto4** [comment]
So sorry, it seems that the user was offline when trying to disconnect (I didn't know that daloRADIUS checked if user was online first either). Thank you for the clarification!

I can now see the additional parameters, but when I try to apply the command, it gives me the following error:

![image](https://github.com/lirantal/daloradius/assets/30811936/5e6918a2-a447-4158-bdeb-92ac4b2a0133)

When I try the command via CLI, I get the same issue:

![image](https://github.com/lirantal/daloradius/assets/30811936/b0d82a22-b787-43e9-bd67-4b8bbcb378ba)

But if we remove the " ' " air quotes from the attributes, it works correctly:

![image](https://github.com/lirantal/daloradius/assets/30811936/14f002a5-3fe6-4e03-b218-f6f14b3cff72)

If I remove the air quotes from the whole custom attributes/values part, it also works correctly.

Is there any way to remove the air quotes from custom attributes using daloRADIUS GUI?

**Comment by filippolauria** [comment]
I see where the error is. The fact is that single quotes are part of parameter escaping/validation, necessary to prevent the so-called "arbitrary code execution" security issue. In particular [here](https://github.com/lirantal/daloradius/blob/2bbe2722213a05d5d360ebf60adcc45e81a1f096/app/operators/library/extensions/maintenance_radclient.php#L130) the function `escapeshellarg($attr)` should not be used. Instead, another way to escape/validate `$attr` should be put in place (maybe regex-based?).
