### ISSUE TITLE
Delete User

### ISSUE THREAD

**Issue by SMRSH** [lirantal/daloradius#44]
Hello,

When I try to delete a user from daloradius i have this error:

`Database error
Error Message: DB Error: syntax error
Debug info: DELETE FROM radpostauth WHERE ='XXXXX' [nativecode=1064 ** You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '='XXXXX'' at line 1]`

OS: Debian 9.1 64bit
PHP: 7

**Comment by lirantal** [comment]
Thanks for reporting this @SMRSH 

Can you show me your daloradius.conf.php file? you should reduct any sensitive information like username/password in it, etc.

**Comment by davidzodelin** [comment]
I have same problem. I delete a user, but, when create new user with the same "username", then, take old values.

**Comment by MiguelVis** [comment]
Hi @davidzodelin.

After inspecting the code in the file `mng-del.php`, I suspect you are using FreeRADIUS v3.

Can you confirm that?

If afirmative, I will upload a patch for the issue.

**Comment by davidzodelin** [comment]
Hi, @MiguelVis, yes my FreeRADIUS is v3.

**Comment by MiguelVis** [comment]
Hi @davidzodelin.

I believe I have fixed this issue with PR #119.

Hope it helps.

**Comment by davidzodelin** [comment]
@MiguelVis  thanks, work perfectly.
