### ISSUE TITLE
Please Help Daloradius Graph not show

### ISSUE THREAD

**Issue by muhalfzzzz** [lirantal/daloradius#440]
![image](https://user-images.githubusercontent.com/114350591/232398852-1bcf575d-b37a-4270-9a61-6237576a20bd.png)
My Daloradius all graph not show please help how to fix it

**Comment by prabath84** [comment]
![image](https://user-images.githubusercontent.com/23372577/233837060-051366f5-c09c-4198-8308-1ebca9769a0f.png)

I'm getting above issue when running the Dabian setup. 
Can anyone please suggest me complete Freeradius + daloradius Installation guide ?
