### ISSUE TITLE
daloRadius - user accounting is not working 

### ISSUE THREAD

**Issue by prabath84** [lirantal/daloradius#443]
I have installed FreeRadius, MariaDB and daloradius in Dabian 11.
Daloradius version is : version 2.0 beta / 9 Feb 2023

I can able to add users + nas via daloradius web interface. 
But i cannot see any User accounting is log into the db side. 

Server Details : 
![image](https://user-images.githubusercontent.com/23372577/234212462-cb2f02c5-66d8-463b-8f6d-fd0cf7f197d8.png)

Debug log file attached for more reference ( VPN User name "prabath", Connected and disconnect session )
sudo freeradius -X
[debug25.txt](https://github.com/lirantal/daloradius/files/11320167/debug25.txt)

Example : All User Accounting is empty 
![image](https://user-images.githubusercontent.com/23372577/234211997-bb4f6152-ebd5-4c59-b372-cd6be3d93d0e.png)

Installed daloradius based on the : https://github.com/lirantal/daloradius/blob/master/INSTALL.debian.md

Can anyone expert help on this issue for me ?

**Comment by schindlerd** [comment]
Seems to be related to the SQL schema.

This post helped me out: https://serverfault.com/questions/1095415/daloradius-error-3-sql-error-rlm-sql-mysql-error-1054-unknown-column-acc

Hope this helps.

**Comment by prabath84** [comment]
@schindlerd - I have not noticed an error that you refer in the blog post. seems something else.

**Comment by momothefox** [comment]
> Seems to be related to the SQL schema.
> 
> This post helped me out: https://serverfault.com/questions/1095415/daloradius-error-3-sql-error-rlm-sql-mysql-error-1054-unknown-column-acc
> 
> Hope this helps.

@schindlerd  This is for fixing old schema to support freeradius 3 
already fixed in new schema

**Comment by schindlerd** [comment]
Typical installation guides refer to these steps regarding schema setup:
`cd /var/www/html/daloradius`
`mysql -u root -p radius < contrib/db/fr2-mysql-daloradius-and-freeradius.sql`
`mysql -u root -p radius < contrib/db/mysql-daloradius.sql`

What would be the correct steps when you use freeradius 3 then?

**Comment by momothefox** [comment]
@schindlerd  for daloradius 1.3 
you will use the schema provided and then do that fix you found.. to support freeradius3 
OR i guess you can use new schema for new version of daloradius 2b

but for new daloradius 2b https://github.com/lirantal/daloradius/blob/master/INSTALL.debian.md

**Comment by prabath84** [comment]
@momothefox  - I exactly followed the steps in the "https://github.com/lirantal/daloradius/blob/master/INSTALL.debian.md". 

in the installation step:18 below step is already covered. 
mysql -u root raddb < /var/www/daloradius/contrib/db/fr3-mysql-freeradius.sql
mysql -u root raddb < /var/www/daloradius/contrib/db/mysql-daloradius.sql

I have not sure reason for not capture any accounting data.


![image](https://user-images.githubusercontent.com/23372577/236720255-716320eb-4e0f-4c79-9e4d-c27b1593310d.png)
