### ISSUE TITLE
Cannot login Daloradius 

### ISSUE THREAD

**Issue by phongtt2506** [lirantal/daloradius#444]
Cannot login Daloradius with default username "administrator" and password "radius".

**Comment by nandish486** [comment]
Kindly read document carefully, or find how to on net, 
[phongtt2506](https://github.com/phongtt2506) commented [on Apr 27](https://github.com/lirantal/daloradius/issues/444#issue-1686410645) • 
Cannot login Daloradius with default username "administrator" and password "radius".

this is just start up and it has no problem for login user administrator.
check database and so on.

**Comment by imanassypov** [comment]
same issue, not able to login with default credentials.
checked db, credentials in table match expected default

which logs can I check?

**Comment by jgroom33** [comment]
The operator login is at x.x.x.x:8000

The administrator / radius user does not exist on the user login x.x.x.x:80
