### ISSUE TITLE
Cannot login from users web interface

### ISSUE THREAD

**Issue by rclabs-dev** [lirantal/daloradius#446]
Hi dear,

I have a freeradius + mysql + dolaradius working fine for user authentication. I setup it to use single user like "john" (without realm) and NT password based hash. Remote clients (Access Points) made its authentication fine.

But using user interface URL like https://FQDN/daloradius/app/users/login.php I cant to do any login. After try the login, Daloradius show me something to inform about the err as below:

**
Cannot Log In

If you are having trouble logging in to your account, it is likely that you have entered the wrong username and/or password. Please ensure that you have correctly entered your login credentials and try again.

If you are still unable to log in after verifying your information, please don't hesitate to contact our support team for assistance. We're always here to help you regain access to your account and get back to using our services as quickly as possible.
** 

I needs to use users interface for my users from Access Points to change yours passwords.

Please, some idea regarding this problem?

Thanks in advance.

Best regards.

Regivaldo Costa

 
**Adittional information about systems version**:

**OS**: Ubuntu 22.04
**Freeradius**: 3.0.26
**Dalosradius**: 2.0 beta
**PHP**: 8.1
**Apache2**: 2.4.52
**MySQL**: 8.0.29

**Comment by Focuslinkstech** [comment]
Do you grant the user permission to log in to the user dashboard?

**Comment by Focuslinkstech** [comment]
![image](https://user-images.githubusercontent.com/45756999/235342407-927678ad-33d6-415c-91f7-97537397c38a.png)

**Comment by rclabs-dev** [comment]
Dear,

I am really sorry. Falling into the rookie error. Now everything is ok. 

Immense apologies for opening the issues and thank you very much for the feedback regarding the resolution.

Best regards,

Regivaldo Costa
--
