### ISSUE TITLE
Daloradius Graph now showing

### ISSUE THREAD

**Issue by JulienRonin** [lirantal/daloradius#453]
I installed the latest Daloradius 1.3 and everything looks fine except the graph doesn't work. 
![dalogrpah](https://github.com/lirantal/daloradius/assets/64393869/8a8ba727-61ba-4237-bc3e-9894ce3bb758)

**Comment by Focuslinkstech** [comment]
@JulienRonin please install the latest version 2.0 
Follow [https://github.com/lirantal/daloradius/blob/master/INSTALL.debian.md](https://github.com/lirantal/daloradius/blob/master/INSTALL.debian.md)

**Comment by Focuslinkstech** [comment]
Or install required dependencies

`apt install php-gd php-db php-mail php-mail-mime `

**Comment by filippolauria** [comment]
> @JulienRonin please install the latest version 2.0 Follow https://github.com/lirantal/daloradius/blob/master/INSTALL.debian.md

We also have a very detailed installation how-to in the wiki. [Check it out](https://github.com/lirantal/daloradius/wiki/Installing-daloRADIUS).
