### ISSUE TITLE
NAS management listing error (daloradius/mng-rad-nas-list.php) 

### ISSUE THREAD

**Issue by hegedusg** [lirantal/daloradius#454]
If there are more than 25 lines, the second page changes the order from asc to desc. This results in wrong second page (the beginning of the first page is repeated but in reverse order).

`on page: /daloradius/mng-rad-nas-list.php  SELECT * FROM nas ORDER BY id desc LIMIT 25, 25;  Jun 08 12:53:26 DEBUG - SQL - SELECT * FROM nas `

`on page: /daloradius/mng-rad-nas-list.php  SELECT * FROM nas ORDER BY id asc LIMIT 0, 25;  Jun 08 12:53:23 DEBUG - SQL - SELECT * FROM nas `

mng-rad-nas-list.php line 119-123 automatically changes the order:
`if ($orderType == "asc") {
                $orderType = "desc";
        } else  if ($orderType == "desc") {
                $orderType = "asc";
        }`
But it should only change order if the sorting changed on the GUI, not automatically on the second page.

**Comment by filippolauria** [comment]
Hello @hegedusg what version of daloRADIUS do you use?
