### ISSUE TITLE
Total Users are not showing in graph chart   daloradius version (1.1-2)

### ISSUE THREAD

**Issue by Mfarkhan** [lirantal/daloradius#457]
I have upgraded the dalo radius from 0.9 to 1.1-2, everything is working fine but the total users are not showing in the graph.

![daloradius (1 1-2)  total users](https://github.com/lirantal/daloradius/assets/49471567/86e7c1dd-43b8-4877-91cb-0c06f0219b4d)

**Comment by Mfarkhan** [comment]
Even, recently  I have installed the 1.3 version but facing the same issue. Please help asap.

**Comment by Focuslinkstech** [comment]
> Even, recently I have installed the 1.3 version but facing the same issue. Please help asap.

Install version 2.0 follow this guide
[https://github.com/lirantal/daloradius/wiki/Installing-daloRADIUS](https://github.com/lirantal/daloradius/wiki/Installing-daloRADIUS)
