### ISSUE TITLE
User not disconnect when coa success

### ISSUE THREAD

**Issue by nandish486** [lirantal/daloradius#463]
Executed:
echo "User-Name='dc',Acct-Session-Id=ADB5B4BC0C993C6CDB21D0E2007CE901,Framed-IP-Address=10.11.0.2" | radclient -c '1' -n '3' -r '3' -t '3' -x '192.168.1.111:3799' 'disconnect' 'testing123' 2>&1

Results:
Sent Disconnect-Request Id 123 from 0.0.0.0:50169 to 192.168.1.111:3799 length 64
User-Name = "dc"
Acct-Session-Id = "ADB5B4BC0C993C6CDB21D0E2007CE901"
Framed-IP-Address = 10.11.0.2
Received Disconnect-ACK Id 123 from 192.168.1.111:3799 to 192.168.1.111:50169 length 20

user still show online and not disconnect 

in additionally Session-Timeout not working at all.
Session-Timeout := reply (600 sec)
Max-All-Session (600 sec) check work when user logout and login.
(Reply-Message = "Your maximum never usage time has been reached")

any help really appreciate

**Comment by nandish486** [comment]
in additionally  Session-Timeout not working at all.
Session-Timeout :=  reply  (600 sec)
Max-All-Session (600 sec) check work when user logout and login.

**Comment by nandish486** [comment]
In this world people are too busy to give answer. FYI I am trying from 38 days but still not work.

**Comment by nandish486** [comment]
[root@localhost ~]# echo "User-Name='king'" | radclient -x 127.0.0.1:3799 disconnect testing123^C
[root@localhost ~]# echo "User-Name=king,Framed-IP-Address=192.168.1.5" | radclient -x 192.168.1.111:3799 disconnect testing123
Sent Disconnect-Request Id 182 from 0.0.0.0:32983 to 192.168.1.111:3799 length 32
        User-Name = "king"
        Framed-IP-Address = 192.168.1.5
Received Disconnect-ACK Id 182 from 192.168.1.111:3799 to 192.168.1.111:32983 length 20
[root@localhost ~]# echo "User-Name=king,Framed-IP-Address=10.25.0.2" | radclient -x 192.168.1.111:3799 disconnect testing123
Sent Disconnect-Request Id 44 from 0.0.0.0:53360 to 192.168.1.111:3799 length 32
        User-Name = "king"
        Framed-IP-Address = 10.25.0.2
Received Disconnect-ACK Id 44 from 192.168.1.111:3799 to 192.168.1.111:53360 length 20
[root@localhost ~]# echo "User-Name=king,Framed-IP-Address=10.25.0.2" | radclient -x 127.0.0.1:3799 disconnect testing123
Sent Disconnect-Request Id 66 from 0.0.0.0:36667 to 127.0.0.1:3799 length 32
        User-Name = "king"
        Framed-IP-Address = 10.25.0.2
Received Disconnect-ACK Id 66 from 127.0.0.1:3799 to 127.0.0.1:36667 length 20


user show online but not disconnect

**Comment by momothefox** [comment]
Is your NAS reachable from the RADIUS Server?

**Comment by nandish486** [comment]
> Is your NAS reachable from the RADIUS Server?

Yes, accounting is working, but disconnect request to Nas doesn't works, Se Linux is also disabled and both are CentOS 7.

I there anything to be configured to tell openvpn for disconnect request?

**Comment by momothefox** [comment]
Is your NAS reachable from the RADIUS Server? 
Can you Ping the NAS IP from the RADIUS server ? 
Accounting will work anyway. but if NAS is behind NAT, how the RADIUS will reach ?

**Comment by filippolauria** [comment]
@nandish486 , this looks to be a problem related to (the way you use) radclient and in general your specific deployment. It doesn't look to be an issue related to daloRADIUS.
