### ISSUE TITLE
daloradius problem with Docker

### ISSUE THREAD

**Issue by jonatanfreire** [lirantal/daloradius#468]
Hello,

I have two problems with my installation of dolaroradius in docker.

1 - The services appear as down, but all are UP.

<img width="1312" alt="Captura de Tela 2023-09-02 às 09 07 49" src="https://github.com/lirantal/daloradius/assets/110001459/d46a5475-5fb9-46e5-97cd-b259302b36c9">

2 - I have an error in the radius log

<img width="771" alt="Captura de Tela 2023-09-02 às 09 10 09" src="https://github.com/lirantal/daloradius/assets/110001459/d83972aa-da1c-4da4-a7a6-a19ce2eeff74">

I'm using a container for daloradius, one for freeradius and another for mariadb.

Can someone help me?

**Comment by gitwittidbit** [comment]
Same problem here.

**Comment by filippolauria** [comment]
The **service status tab** is reliable only in "standalone deployments", such as the one you can set up by following [the installation guide](https://github.com/lirantal/daloradius/wiki/Installing-daloRADIUS).
