### ISSUE TITLE
Security Vulnerabilities Identified

### ISSUE THREAD

**Issue by sahiloj** [lirantal/daloradius#473]
Hey @lirantal, I have identified mutiple security vulnerabilities in daloradius application. I am not able to report via huntr. Can i email or create a issue here? Please respond ASAP.

**Comment by filippolauria** [comment]
Hello @sahiloj , what daloRADIUS version is affected?

**Comment by sahiloj** [comment]
Hello @filippolauria , It's Version 1.3 released on 04 NOV 2021. Is there any  way i can report these vulnerabilities?

**Comment by filippolauria** [comment]
That version is no more supported (at least by me).
If you want, you can try looking for security issues in the master branch of this repository.
