### ISSUE TITLE
Multiples issues on main

### ISSUE THREAD

**Issue by pyromiko** [lirantal/daloradius#475]
Using "dockerfile: Dockerfile" on fresh install:

- On compose if you not commnent "command: -X" you will get a error on "docker-compose up" at end.

- On Daloradius for Management,Reports,Accounting got database error:

example:
_Database error
Error message: DB Error: no such table
Debug info:
SELECT DISTINCT(username) FROM radacct ORDER BY username ASC [nativecode=1146 ** Table 'radius.radacct' doesn't exist]_

- Any change on daloradius GUI you get:

_Could not open the file for writing: /var/www/daloradius/app/common/includes/daloradius.conf.php
Check file permissions. The file should be writable by the webserver's user/group_

- On daloradius Service Status, you get all _"not running"_ ; or log:
_Error accessing log file: (none).
Looked for log file in /var/log/syslog, /var/log/messages but could not find it.
If you know where your system log file is located, specify its location in /library/extensions/syslog_log.php._

**Comment by filippolauria** [comment]
Currently, the recommended solution is to deploy daloRADIUS on an LXC with Debian 11 or 12 following the installation procedure provided [here](https://github.com/lirantal/daloradius/wiki/Installing-daloRADIUS).
