### ISSUE TITLE
Default username and password

### ISSUE THREAD

**Issue by saba4good** [lirantal/daloradius#478]
I just installed Daloradius using the docker-compose from this repository, but I can't figure out the default username and password to login the web page.
I tried the usernames 'radius', 'administrator', and the passwords 'radius', 'radiusdbpw', 'testing123' without any success.

Then I found this : https://stackoverflow.com/questions/51125216/reset-daloradius-password. So I tried 'administrator' with password 'radius' as the username and password in the operators table, but it didn't work either.

So where should I look now? And what else can I try?

**Comment by drummerroma** [comment]
You will find the solution here:
https://github.com/lirantal/daloradius/issues/456#issuecomment-1716197289
