### ISSUE TITLE
Permission issues - the file /etc/freeradius/proxy.conf isn't writable, I can't save realms information to the file

### ISSUE THREAD

**Issue by saimsaiyed** [lirantal/daloradius#479]
Dear All,

Happy new year!
We have configured and installed FreeRADIUS + DaloRADIUS. We are not able to add new Realms through the DaloRADIUS web gui.
It give the error "the file /etc/freeradius/proxy.conf isn't writable, I can't save realms information to the file"

Please help.

Thanks in advance.

**Comment by filippolauria** [comment]
If you are using freeRADIUS 3.0.* that file has been moved to: `/etc/freeradius/3.0/proxy.conf`.
Also ensure that daloRADIUS can read/write it.
