### ISSUE TITLE
Duplicate sql insert value

### ISSUE THREAD

**Issue by HerdiEhza** [lirantal/daloradius#481]
I'm sorry if i make issues about this, but this is my first time to contribute to any project (if this action still count as contibution)

ERROR 1062 (23000) at line 10166: Duplicate entry '252' for key 'PRIMARY'

https://github.com/lirantal/daloradius/blob/5f827435d5b20dccd91757090abd6934b161965e/contrib/db/mariadb-daloradius.sql#L10166

**Comment by filippolauria** [comment]
@HerdiEhza , thanks for your contribution. This is a typo in the SQL query for populating the `operators_acl` table. Can you manage to create a pull request and push this fix to our repository?

**Comment by rovshan91** [comment]
does that problem resolved?

**Comment by rovshan91** [comment]
but i`m dowloaded the latest version from git today and stil have same problem. Sorry for stupid guestion but where i can find working  mariadb-daloradius.sql ?
