### ISSUE TITLE
I've issue when import mariadb-daloradius.sql

### ISSUE THREAD

**Issue by AungThuMyint** [lirantal/daloradius#483]
I'll install it in the step-by-step from "https://github.com/lirantal/daloradius/wiki/Installing-daloRADIUS", but I've issues import mariadb-daloradius.sql, error is ERROR 1062 (23000) at line 10166: Duplicate entry '252' for key 'PRIMARY'. I already installed the mariadb-server and it is still running. how to fix it?

<img width="761" alt="Untitled" src="https://github.com/lirantal/daloradius/assets/63327282/07e5ede5-a64d-4cf0-9ac8-adb3e8727166">

**Comment by filippolauria** [comment]
Hi @AungThuMyint look at #481

**Comment by filippolauria** [comment]
Issue has been fixed.
