### ISSUE TITLE
VPN session details not working from daloRadius front interface.

### ISSUE THREAD

**Issue by prabath84** [lirantal/daloradius#487]
My VPN users are authenticating via FreeRadius and DaloRadius.
But Session details are not visible from daloRadius Frontend All records sesions.

See below User is connected 
![image](https://github.com/lirantal/daloradius/assets/23372577/147a71c6-13e6-4807-a7b2-862eb8894ba7)

But If you navigate to the Accounting section and try to view records, its empty. 

![image](https://github.com/lirantal/daloradius/assets/23372577/690871e3-c785-4387-84ae-8103170224c5)

NOTE: Radius Accounting data is enabled on my pfsense VPN server side .

![image](https://github.com/lirantal/daloradius/assets/23372577/ecb9cafc-3790-4028-a44e-f00578f62be2)

Can you please help me how to resolve this issues? 
Is it due to new code changes causing these types of issues?

**Comment by filippolauria** [comment]
The first query gets data from `radpostauth` while the second one gets them from `radacct`. It looks like that the latter is empty. Check if RADIUS accounting is correctly configured.

**Comment by prabath84** [comment]
@filippolauria : Thanks for the insights. I believe I have correctly installed RADIUS. Let me reinstall it again and check.

**Comment by prabath84** [comment]
Hi @filippolauria ,

I followed the KBA (https://github.com/lirantal/daloradius/wiki/Installing-daloRADIUS) today and installed it the same way in the document. User accounting data is not captured in the DaloRadius section. 

![image](https://github.com/lirantal/daloradius/assets/23372577/bc4b3376-67f8-4c01-848c-b2efcb6b1c5e)

Can someone please help me with this section?

**Comment by filippolauria** [comment]
daloRADIUS does not show anything because the `radacct` table is apparently empty. This suggests that something is not properly working with your freeRADIUS config. Please try troubleshooting it also  using other related resources you find on the Internet.

**Comment by kokonod** [comment]
if you need more support contact us telegram: +919547443406

**Comment by prabath84** [comment]
-
