### ISSUE TITLE
Missing validation.php file in library folder

### ISSUE THREAD

**Issue by fmalfatto** [lirantal/daloradius#498]
I have such error in log, called from several pgms:
PHP Warning:  include_once(): Failed opening 'library/validation.php' for inclusion (include_path='.:/usr/share/php8:/usr/share/php/PEAR') in /srv/www/daloradius/app/operators/library/extensions/maintenance_radclient.php on line 188

I verified that validation.php is not in library but in common/includes:
 # find . -name 'validation.php'
./app/common/includes/validation.php

**Comment by nikbehjati** [comment]
Missing DB.php file in library folder
