### ISSUE TITLE
daloRADIUS PHP-7 Support

### ISSUE THREAD

**Issue by lirantal** [lirantal/daloradius#5]
# How to get daloRADIUS to work in PHP-7?
# Dependencies
- This assumes an Ubuntu 16.04 OS installled
- This assumes PHP 7 installed
- This assumes MySQL >= 5.7.5 installed
- This assumes you have already installed all the LAMP related packages and have a working LAMP environment.
  Next, is to make sure you have the required extra packages for daloRADIUS, run:

``` bash
sudo apt-get install php-common php-gd php-curl php-mail php-mail-mime php-pear php-db
```

and then

``` bash
pear install DB
```
# daloRADIUS internal change
## Changing file `library/daloradius.conf.php`

It's required to update daloRADIUS's database connection code so that it identifies the MySQL server using the new and improved _mysqli_ driver:
1. Open for editing the file `library/daloradius.conf.php` and locate the configuration variable `CONFIG_DB_ENGINE` and change it to the value of `mysqli` (it is now probably set to `mysql`, notice the extra `i`). It should end up looking as follows: `$configValues['CONFIG_DB_ENGINE'] = 'mysqli';`
## Changing file `library/opendb.php`
1. Open for editing the file `library/opendb.php`
2. At the very end of the file just add this new line of code: `$dbSocket->query("SET GLOBAL sql_mode = '';");` which makes the MySQL version work with less strict SQL syntax

**Comment by lirantal** [comment]
Re-opening for issue to be pinned at the top for everyone to consult

**Comment by Riply** [comment]
Thanks for this man. 
I'm still getting the error, but at least I'm that little bit closer!

**Comment by lirantal** [comment]
@Riply np. what error are you getting?

**Comment by Riply** [comment]
(: 

On the http://auth1.enetworks.co.za/sentinel/dologin.php page, I'm getting:

Database connection error
Error Message: DB Error: connect failed

Even after making your suggested changes.

**Comment by lirantal** [comment]
@Riply which version of daloRADIUS? MySQL? PHP? etc can you provide these details?
In a nutshell it seems you don't have the correct settings to connect to the MySQL database in `library/daloradius.conf.php`

**Comment by Riply** [comment]
It was even worse that that - I had the wrong user stipulated in the library/daloradius.conf.php.. it didn't have permissions to use the DB.

**Comment by lirantal** [comment]
Ok thanks for the update. Just noticed now that you updated your previous comment.

**Comment by amlluch** [comment]
Now I can access to Daloradius after applying the changes but I can't change any value of the database. If I try change a reply value for a user or anything else I get an error 500. I have read that may be an error with pear-db. Has anyone the same issue?

Thanks in advance

**Comment by lirantal** [comment]
@amlluch never heard of it... not even on the forums on SF.

**Comment by NCKCN** [comment]
Liran, Same exact thing here as amlluch with Apache 2.4.18 throwing a 500 error. Everything appeared to work initially. Was able to add a new User, add a new Profile, add an Filter-ID Attribute to that Profile. Then nothing can be written to the database...
Ubuntu0.16.04.2
daloRADIUS version 0.9.9
MySQL version 5.7.13
Apache version 2.4.18
PHP version7.0.8

Thanks

**Comment by amlluch** [comment]
More on this ... I can add a new user but I can't change any value. I can't clear sessions disconnected but hanged on the data base. Not sure if this helps.

**Comment by NCKCN** [comment]
amlluch, exact same here. Apache always throws a PHP error such as: "PHP Fatal error:  Uncaught Error: Call to undefined function split() in /var/www/html/mng-rad-profiles-edit.php:53\nStack trace:\n#0 {main}\n  thrown in /var/www/html/mng-rad-profiles-edit.php on line 53, referer: https://radius.nck-wifi.com/mng-rad-profiles-edit.php?profile=NCK-WiFi-Guest".

Tried the pear/MDB2 and that broke everything.

**Comment by lirantal** [comment]
Can you revert back to the Pear DB driver and then continue testing?
The issue with split is that it's deprecated in PHP 7:
![image](https://cloud.githubusercontent.com/assets/316371/17933011/17c836e0-6a1b-11e6-986f-809276a86553.png)

I'll evaluate what's the required effort to refactor the split function to fix this.

**Comment by NCKCN** [comment]
Liran, already switched back to Pear DB. Thanks for the quick response!

**Comment by amlluch** [comment]
when I try to delete a user hanged, on /var/log/apache2/error.log I get:

[Fri Aug 26 10:48:12.451397 2016] [:error] [pid 14461] [client xxx.xx.xx.xxx:59869] PHP Fatal error:  Uncaught Error: Call to undefined function split() in /var/www/daloradius/mng-del.php:157\nStack trace:\n#0 {main}\n  thrown in /var/www/daloradius/mng-del.php on line 157, referer: http://radius.anonymousvpn.es/rep-online.php?usernameOnline=

May be this could help.

**Comment by amlluch** [comment]
I have seen that split() function is deprecated so I changed to explode but stale record is not deleted and I get next error on apache2 error.log:

[Fri Aug 26 11:35:48.041862 2016] [:error] [pid 17483] [client xxx.xxx.xxx.xxx:60581] PHP Notice:  Undefined offset: 1 in /var/www/daloradius/mng-del.php on line 157, referer: http://radius.anonymousvpn.es/rep-online.php?usernameOnline=

**Comment by amlluch** [comment]
Ok ... finally I fixed the error changing at line 157 of /var/www/daloradius/mng-del.php from **split('\|\|', $value)** to **explode('||', $value)**

The point is that there are many erros with php7. I get errors in more places and I think the reason why is that Daloradius is an "old software" with few revissions.

**Comment by NCKCN** [comment]
amlluch, I think Liran is working on fixing the PHP code for an updated release of the daloRADIUS if I understood his post correctly? I'll bet he'll get back with us an put out a new version with all the corrected old split functions. Since he's the one who knows all the "under the hood" stuff, I'll wait for this input. In the meantime, Liran, let us know if you need us to test anything on our end.  :)

**Comment by lirantal** [comment]
Hey guys @amlluch , @NCKCN 
I fixed the issues in this PR #8 - can you please test the fix there? you need to checkout that branch locally and test it. Will you handle doing that?

It should fix the PHP7 errors with the split function because I replaced all occurrences of it.
I need someone to confirm that it's fixed so I can merge it to the master branch.

**Comment by NCKCN** [comment]
Liran,
Updated the 18 files, restarted and I see no errors. Doing some more thorough testing and let you know if I do see any anomalies. Are they any specific functions/features you want tested? Excellent work my friend!

**Comment by lirantal** [comment]
Awesome! thanks for the feedback @NCKCN 
Would be great if you can generally just test through-out the functionality and see if there are PHP7 related issues and I'll be happy to apply some more fixes.

Happy to help :)

**Comment by NCKCN** [comment]
Liran,
I've pretty much threw everything that I have configured for my part, and seems to be working like a champ. Granted, I don't have all the bells and whistles, but functioning exactly as my PHP5.6 install. I'd say you have the split error exploded >;0

**Comment by lirantal** [comment]
LOL

Cool, so thanks a lot in helping test this out.

**Comment by hmachine1999** [comment]
its help me solve troubles，thx

**Comment by amlluch** [comment]
Hi Liran ... everything was working more or less fine but after making a dist-upgrade I get again next error:

Database connection error
Error Message: DB Error: connect failed

Not sure what can I do

**Comment by lirantal** [comment]
That's very vague, I can't really understand what is going on.
Possibly your database is down? the db has changed? access details (user/pass) changed?

**Comment by bredis** [comment]
lirantal, thank you.
For its setting the problem figured out all the instructions on the Ubuntu.
Everything works, thank you.[https://github.com/lirantal/daloradius/issues/11](url)

**Comment by lirantal** [comment]
@bredis awesome, happy you got it working! :)

**Comment by plnavarro76** [comment]
It works for me. Thanks!! Ubuntu 16.04 server.

**Comment by lirantal** [comment]
Great, happy to hear

**Comment by zukimonster** [comment]
I'm getting the following:
PHP Parse error:  syntax error, unexpected ';', expecting ',' or ')' in /var/www/html/daloradius/library/opendb.php 

I've got PHP 7.0.15

**Comment by lirantal** [comment]
@zukimonster you ommited the most important debug info - which line is it complaining about? :)

**Comment by lirantal** [comment]
@zukimonster I can't find any such static code analysis issues on that file.
Can you make sure you pulled the latest code from the master branch and try again? If it happens please be more verbose in the error you provide

**Comment by zukimonster** [comment]
[:error] [pid 29920] [client _ip:port_] PHP Parse error:  syntax error, unexpected ';', expecting ',' or ')' in /var/www/html/daloradius/library/opendb.php on line 97, referer: http://192.168.123.40/daloradius/login.php

line 97:  $dbSocket->query("SET GLOBAL sql_mode = ";");

**Comment by zukimonster** [comment]
Now I'm getting:

Database connection error
Error Message: DB Error: connect failed

**Comment by lirantal** [comment]
can you check your database details to figure it out?
would be good if you can also look into mysql log or anything else that gives an idea for why the connection failed.

**Comment by amuiruri** [comment]
@lirantal I am new in github, where can I download all daloradius files working with php7 without errors ??

**Comment by lirantal** [comment]
if you're new to git/github and you don't know how to clone a project you can also just click the green button and choose to download a .zip file of the current 'master' branch. unzip it can continue regularly...
![daloradius-download](https://cloud.githubusercontent.com/assets/316371/26218856/368569c8-3c15-11e7-88a2-948684d3c93c.png)

**Comment by amuiruri** [comment]
Thanks @lirantal

**Comment by bhesterberg78** [comment]
Your php7 trick worked, I can now log into daloradius and navigate it. It seems I can create a new user as well, but when I go to "List Users" under "Users Management", I get the following error... 
Error Message: DB Error: unknown error
Debug info: SELECT distinct(radcheck.username),radcheck.value, radcheck.id,radusergroup.groupname as groupname, attribute FROM radcheck LEFT JOIN radusergroup ON radcheck.username=radusergroup.username WHERE (Attribute='Auth-Type') or (Attribute LIKE '%-Password') GROUP BY UserName [nativecode=1055 ** Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'radius.radcheck.value' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by]

Can anyone help with this?

**Comment by lirantal** [comment]
Not sure about that, sorry. Either the schema doesn't match anymore the query or it's related to the sql_mode we set.

Can you investigate and let me know if you find a fix for it?

**Comment by Sailing74** [comment]
Running into the same issue.
The error message some other place is `Database error
Error Message: DB Error: unknown error
Debug info: SET GLOBAL sql_mode = ''; [nativecode=1227 ** Access denied; you need (at least one of) the SUPER privilege(s) for this operation]`
That gave me a pretty good hint. Apparently, the user I was using did not have sufficient rights for the work around. I granted all rights to the user, and the error messages - including the one reported by @bhesterberg78 - are gone. Maybe this helps someone.

**Comment by Sailing74** [comment]
Ok, now I'm running into other php7 related issues reported here, mostly regarding split () so far. I'm using 0.9.9 currently. Which branch should I check out? Master? Feature/daloradius-php7-support?

**Comment by lirantal** [comment]
just master, that should be compatible with php7.
let me know which issues you're having.

**Comment by Carlospenate** [comment]
It works for me, thanks!

**Comment by lirantal** [comment]
Awesome :-)

**Comment by MiGzY** [comment]
Hi Liran, I changed the files above to support PHP7 but now I get this error in my headers on the rendered PHP output. 

Database error
Error Message: DB Error: unknown error
Debug info: SET GLOBAL sql_mode = ''; [nativecode=1227 ** Access denied; you need (at least one of) the SUPER privilege(s) for this operation]

Assuming this is because the radius user needs to be a SUPER?

**Comment by crgl2002** [comment]
Liran, Thans for such a good work.
Ive followed  PR #8 fix and got a problem, cannot disconnect users. The error  One of NAS Address, NAS Port or NAS Secret fields were left empty 
Looking at apache error log:
Undefined index: customAttributes in /var/www/daloradius-0.9-9/config-maint-disconnect-user.php on line 194
Undefined variable: customAttributes in /var/www/daloradius-0.9-9/config-maint-disconnect-user.php on line 195
What Im doing wrong or  missing?
Thanks.

**Comment by lirantal** [comment]
Hey @crgl2002 

Looks like they are just warnings.
Regardless seems you're using the tar'ed package downloaded from SF so I suggest cloning the master's branch repository here and working with that instead.

**Comment by crgl2002** [comment]
Hi Liran, may be they are but the user is not disconnected. This started to happen after I updated to php7. I m new to github, downloading the .zip file and unzip it will keep all actual configs? Thanks.

**Comment by lirantal** [comment]
So you can download the zip from GitHub too and try it.
Don't forget to make a backup of the existing daloRADIUS directory and then just copy over the config files

**Comment by m00zi** [comment]
same here

**Comment by MiguelVis** [comment]
Hi @m00zi

What's your problem exactly?

**Comment by m00zi** [comment]
Hi, I hade the DB error issue, after jumping between stackoverflow and github finaly I was able to login to GUI, but now in the GUI's header I have this error:

```Database error
Error Message: DB Error: unknown error
Debug info: SET GLOBAL sql_mode = ''; [nativecode=1227 ** Access denied; you need (at least one of) the SUPER privilege(s) for this operation]```

**Comment by MiguelVis** [comment]
It's related to the privileges of the user you are using to access the database.

It was already commented and solved in this [same thread](https://github.com/lirantal/daloradius/issues/5#issuecomment-322055642)

> Running into the same issue.
> The error message some other place is `Database error Error Message: DB Error: unknown error Debug info: SET GLOBAL sql_mode = ''; [nativecode=1227 ** Access denied; you need (at least one of) the SUPER privilege(s) for this operation]`
> That gave me a pretty good hint. Apparently, the user I was using did not have sufficient rights for the work around. I granted all rights to the user, and the error messages - including the one reported by @bhesterberg78 - are gone. Maybe this helps someone.

**Comment by MiguelVis** [comment]
@m00zi

After some checking, I have determined you are running an old version of Daloradius.

The GLOBAL part in your query is now SESSION, allowing non ROOT users to change the sql mode for the application:

`$dbSocket->query("SET SESSION sql_mode = '';");`

Please, download the master branch located here at GitHub, and make the changes you need to the Daloradius configuration file `library/daloradius.conf.php`.

DO NOT SUBSTITUTE it by your current configuration file, because there are new configuration variables.

All should go ok.

**Comment by brbrow** [comment]
This tutorial shows how to [Install Daloradius install using php7 on ubuntu linux](https://techexpert.tips/freeradius/freeradius-installation-mysql-integration-ubuntu-linux/).
