### ISSUE TITLE
Website suspended

### ISSUE THREAD

**Issue by dedayoa** [lirantal/daloradius#50]
The daloradius.com website is suspended

**Comment by lirantal** [comment]
Thanks! I'm quite busy this time but I'll try to get around to this within a reasonable time.
Is there something on the website that wasn't accessible now?

**Comment by InnovativeInventor** [comment]
No, the whole website doesn't work, this is how it looks:
![screenshot-2018-4-6 hosting suspended](https://user-images.githubusercontent.com/20117409/38433031-745ed34e-3997-11e8-9650-fca3b522aabd.png)

**Comment by bayden10** [comment]
hi, I can help, we run a hosting business and I can provide your hosting for free.. cPanel access etc.. pm me

**Comment by lirantal** [comment]
Sorry @InnovativeInventor , @dedayoa , have been extremely busy that I can't attend to this atm.

Thanks @bayden10, I appreciate that!
The official daloradius.com website is really just presentation so there's no heavy lifting DBs or server-side code.

Would you or anyone else be interested in building the new site?
Maybe we can even host it opensourcely on github pages?

**Comment by lirantal** [comment]
Thanks @bayden10 

The repository for the website is at https://github.com/lirantal/daloradius-web and the website is still accessible over here: https://web.archive.org/web/20170804092851/http://www.daloradius.com:80/ for a visual reference.

There are only a couple of pages there.
If you'd be able to create a static website out of it (you're welcome to go crazy on the design, layout etc) then you're welcome to push a new PR for that repository (lirantal/daloradius-web) and I'll be hapy to merge it. We can then just use Netlify or GH Pages to host it.

**Comment by bayden10** [comment]
ok not familiar with these alternatives, I was offering to host with us in providing your domain daloradius.com public visibility again.

**Comment by InnovativeInventor** [comment]
Do you have a sitemap or a list of all the pages (you mentioned that only a couple of pages are in the git repo)?

**Comment by lirantal** [comment]
@InnovativeInventor no I meant that the website itself was just like 2 or 3 pages.
Even just a single landing page would be enough really.

**Comment by InnovativeInventor** [comment]
@lirantal I just opened a pull request with a static version of the website.

**Comment by bayden10** [comment]
its a start - http://daloradius.org (https will be active in 24hrs)

lirantal you can point your .com to .org now within your DNS settings at godaddy
InnovativeInventor if you wish to continue PM me and I will provide cPanel access.

**Comment by InnovativeInventor** [comment]
@bayden10 Sure, I'm happy to help, although you don't seem to have an email address I can reach you at.

**Comment by bayden10** [comment]
hmm, ok just sent a PM

**Comment by lirantal** [comment]
@bayden10 thanks! 
that website doesn't load for me, can you check?

**Comment by InnovativeInventor** [comment]
@lirantal Github Pages works well when I made a static version of your site. Here it is: https://innovativeinventor.github.io/daloradius-web/
It'll probably be easier to accept contributions through GitHub.

**Comment by lirantal** [comment]
@InnovativeInventor thanks for all the help, I merged and updated A and CNAME records to point to the new URL.

I also added you as a collaborator on the `daloradius-web` repo in-case you'd be interested in making other updates in the future.

Appreciate all the help guys ❤️ @InnovativeInventor @bayden10
