### ISSUE TITLE
Test user connectivity command not work 

### ISSUE THREAD

**Issue by nandish486** [lirantal/daloradius#505]
below is not working
echo "User-Name='xxx',User-Password='xxx'" | /usr/bin/radclient  -c '1' -n '3' -r '3' -t '3' 1 '127.0.0.1:1812' 'auth' 'testing123' 2>&1

working
echo "User-Name='dhc',User-Password='489'" | /usr/bin/radclient  -c '1' -n '3' -r '3' -t '3' -x '127.0.0.1:1812' 'auth' 'testing123' 2>&1

/usr/bin/radclient  -c '1' -n '3' -r '3' -t '3' after -x require not 1 .

so please update

**Comment by lirantal** [comment]
Did you use the latest version of daloRADIUS that is in the `master` branch of this repository? Filippo merged a big update with many fixes just 2 days ago.

**Comment by nandish486** [comment]
> Did you use the latest version of daloRADIUS that is in the `master` branch of this repository? Filippo merged a big update with many fixes just 2 days ago.

Not installed from releases,  was done with git clone to this branch directly yesterday, and found so.

**Comment by lirantal** [comment]
Ok so yes still relevant.

**Comment by lirantal** [comment]
Merged a fix here: https://github.com/lirantal/daloradius/pull/506
