### ISSUE TITLE
total_users.php not counting properly

### ISSUE THREAD

**Issue by trpl7** [lirantal/daloradius#509]
Migrating from 0.9-9 and it seems that total_users.php does not seem to be counting correctly.  I have 525 users in my database, but the counter only counts 500.

I replaced the section below from total_users.php

`$sql = sprintf("SELECT COUNT(DISTINCT ui.username) FROM %s AS rc, %s AS ra, %s AS ui
	WHERE ui.username=ra.username AND ui.username=rc.username
        AND (rc.attribute='Auth-Type' OR rc.attribute LIKE '%%-Password')",
        $configValues['CONFIG_DB_TBL_RADCHECK'],
        $configValues['CONFIG_DB_TBL_RADACCT'],
        $configValues['CONFIG_DB_TBL_DALOUSERINFO']);`

With dalo 0.9-9 chart-mng-total-users.php makes the count work properly

`$sql = "SELECT COUNT(DISTINCT(UserName)) from ".$configValues['CONFIG_DB_TBL_RADCHECK'].";";`

home-main.php also has the same user count problem.

It looks like accounts with MAC authentication are not being counted, but that only accounts for about half of the missing users.

**Comment by filippolauria** [comment]
@trpl7,
The second query you wrote considers all records _distinctly_ in the `radcheck` table.
However, the first query only considers `Auth-Type` and `Password-like` attributes.
Which RADIUS attributes are you using for your MAC authentication users?

**Comment by trpl7** [comment]
I think this problem is coming from the check against the radacct table.  A new user will not have entries in the table until they authenticate and generate accounting data which is throwing off the total user count.  Modifying total_users.php to the query below is returning the correct count.

>$sql = sprintf("SELECT COUNT(DISTINCT ui.username) FROM %s AS rc, %s AS ui
>                       WHERE ui.username=rc.username
>                       AND (rc.attribute='Auth-Type' OR rc.attribute LIKE '%%-Password')",
>                       $configValues['CONFIG_DB_TBL_RADCHECK'],
>                       $configValues['CONFIG_DB_TBL_DALOUSERINFO']);

**Comment by filippolauria** [comment]
Yeah, I can see your point. I managed to fix that.
