### ISSUE TITLE
UI issues: daloRADIUS - RADIUS Management version 2.0 beta / 9 Feb 2023

### ISSUE THREAD

**Issue by CALROB** [lirantal/daloradius#510]
<img width="1577" alt="image" src="https://github.com/lirantal/daloradius/assets/10970988/1759ba12-6ac7-42ac-b3d5-3c17d9931e78">

New dashboard looks great, counters incorrect though. Users, always 0, NAS 0 and hotspots counting NAS.

<img width="1299" alt="image" src="https://github.com/lirantal/daloradius/assets/10970988/1dca1ddc-e7c0-45eb-b7c3-07ded4654b75">
No metric graphs working either.

Upgraded from previous version before the new dashboard.

**Comment by filippolauria** [comment]
Update to a newer version. Also if you can, please share what kind of check attributes you expect will be taken into account when counting users.

**Comment by CALROB** [comment]
updated, now working, graphs still no longer working.

In terms of counting, just present a row counter from db i'd expect from this, what do you think? This UI overhaul is looking really good though now!

**Comment by filippolauria** [comment]
@CALROB, I'm glad to hear that you like the UI! 😊

However, it seems like some _important details_ are still missing. Don't worry, this is something that happens quite often! For this reason, I decided to create a short guide in our wiki which should help in [reporting issues](https://github.com/lirantal/daloradius/wiki/Reporting-issues). My goal is to refer to it from now on whenever necessary.
