### ISSUE TITLE
Problema con mariadb, no inicia (ubuntu 16.04)

### ISSUE THREAD

**Issue by byjatp** [lirantal/daloradius#512]
muy buenas tardes, configurando mi servidor daloradius, me he encontrado con el siguiente problema: al completar la instalación, he visto que en los servicios activos, están todos funcionando menos MariaDB, tras mirar en muchos archivos de configuración no he dado con la solución, alguien puede ayudarme? Seguí el siguiente tutorial https://youtu.be/JwFhljT5hyQ Gracias.

**Comment by filippolauria** [comment]
@byjatp , I'm glad to hear that you are trying to install daloRADIUS! 😊

However, it seems like some _important details_ are still missing. Don't worry, this is something that happens quite often! For this reason, I decided to create a short guide in our wiki which should help in [reporting issues](https://github.com/lirantal/daloradius/wiki/Reporting-issues).

**Comment by byjatp** [comment]
> @byjatp , I'm glad to hear that you are trying to install daloRADIUS! 😊
> 
> However, it seems like some _important details_ are still missing. Don't worry, this is something that happens quite often! For this reason, I decided to create a short guide in our wiki which should help in [reporting issues](https://github.com/lirantal/daloradius/wiki/Reporting-issues).
Hi, i´m ussing ubuntu server 16.04 with mariadb 10.0.38 and the version of daloradius is 2.0 beta/ 9 feb 2023 
![image](https://github.com/lirantal/daloradius/assets/167542738/eeed5cc4-f86a-40b7-8a67-e72b4a69f50c)

**Comment by filippolauria** [comment]
@byjatp ,
both MariaDB and MySQL are relational database management systems; only one of them has to be up, running and properly configured for daloRADIUS to work.
