### ISSUE TITLE
attribute value not change

### ISSUE THREAD

**Issue by nandish486** [lirantal/daloradius#516]
not able to edit attribute value in profile like when I change session-time from 3600 to 7200. value not change.

**Comment by filippolauria** [comment]
@nandish486  , I'm glad to hear that you are trying to install daloRADIUS! 😊

However, it seems like some _important details_ are still missing. Don't worry, this is something that happens quite often! For this reason, I decided to create a short guide in our wiki which should help in [reporting issues](https://github.com/lirantal/daloradius/wiki/Reporting-issues).

**Comment by nandish486** [comment]
> @nandish486 , I'm glad to hear that you are using daloRADIUS! 😊
> 
> However, it seems like some _important details_ are still missing. Don't worry, this is something that happens quite often! For this reason, I decided to create a short guide in our wiki which should help in [reporting issues](https://github.com/lirantal/daloradius/wiki/Reporting-issues).

In profile settings, when values of attribute are changed, in my case let's say session-time edited from 3600s to 7200s the value of session timeout is not changed to 7200s.
In Short we could say: EDIT PROFILE ATTRIBUTES CAN'T BE CHANGED IF CHANGED IT STAYS THEY SAME !
