### ISSUE TITLE
New Install - Authentication Issues

### ISSUE THREAD

**Issue by cjasmith97** [lirantal/daloradius#517]
**Describe the bug**
Following the instructions to the letter in the GitHub Wiki, all sites and services load up fine.
But - browsing to the user ports (:80) and logging in with the default administrator/radius account fails due to wrong username/password.
Logging in to the operator portal (:8000) - login works fine.
Even if you create a new operator from the operator portal, you still get wrong user/pwd from the user portal.

**To Reproduce**
1. Install using the guide on Wki
2. Login to operator portal with administrator/radius (works)
3. Login to user portal with administrator/radius (doesn't work)
4. Create new user via operator portal, and try logging in to user portal (doesn't work)

**Expected behavior**
The default creds should work from user portal and new operators creators should be able to login.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Your Browser:  Chrome
 - daloRADIUS Version: cloned master branch today
 - FreeRADIUS Version: 3

**Additional context**
brand new install - tried rebuilding multiple times.

**Helpful communication**
- Write in clear and concise *English*.
- Avoid using slang or technical jargon that may be difficult to understand.
- Respond promptly to any follow-up questions or requests for more information.
- Be open to suggestions or troubleshooting steps proposed by maintainers or other users.

**Comment by white-rabbit07** [comment]
same here -- but on Debian 12

**Comment by white-rabbit07** [comment]
Ok -- it's no bug ... I found this tutorial (german) meanwhile:
https://administrator.de/tutorial/freeradius-management-mit-webgui-6972997853.html
-> Daloradius Funktionscheck -> "User Info" -> Other -> Settings
After that a testuser was able to login.
