### ISSUE TITLE
Import users - CSV-formatted data - Polish characters

### ISSUE THREAD

**Issue by Jacekz70** [lirantal/daloradius#518]
Validation removes Polish characters from the Name and Surname field when importing multiple users (żźć... etc.).

What should I do to ensure that the data imports correctly?

Kind regards
Jack

**Comment by Jacekz70** [comment]
Problem solved.
In the file: validation.php
row: 46

I changed from: define("ALL_PRINTABLE_CHARS_REGEX", '/^[ -~]+$/');
on: define("ALL_PRINTABLE_CHARS_REGEX", '/^[ -~ąćęłńóśźżĄĆĘŁŃÓŚŹŻ]+$/');

I'm not sure if this is the best solution, but it works ;)

**Comment by lirantal** [comment]
Thanks for sharing! I applied this fix and commited the change.
