### ISSUE TITLE
Issues with PHP 7.0

### ISSUE THREAD

**Issue by antoniovalenzuela** [lirantal/daloradius#52]
Issues with PHP 7.0

View logs
2018/03/31 17:57:05 [error] 19899#19899: *1928 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function eregi_replace() in /usr/share/nginx/html/daloradius/library/exten-radius_log.php:62
Stack trace:
#0 /usr/share/nginx/html/daloradius/rep-logs-radius.php(61): include()
#1 {main}
  thrown in /usr/share/nginx/html/daloradius/library/exten-radius_log.php on line 62" while reading upstream

Server Status
2018/03/31 17:58:33 [error] 19899#19899: *1940 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function split() in /usr/share/nginx/html/daloradius/library/exten-server_info.php:33
Stack trace:
#0 /usr/share/nginx/html/daloradius/library/exten-server_info.php(258): uptime()
#1 /usr/share/nginx/html/daloradius/rep-stat-server.php(56): include('/usr/share/ngin...')
#2 {main}
  thrown in /usr/share/nginx/html/daloradius/library/exten-server_info.php on line 33" while reading upstream

**Comment by lirantal** [comment]
Hi @antoniovalenzuela,

Seems like you're using an older copy of daloRADIUS.
Can you please copy this git repository's master branch and check with that?
