### ISSUE TITLE
Cannot add/edit groups.

### ISSUE THREAD

**Issue by momuskk** [lirantal/daloradius#525]
I've downloaded yesterday (2024-05-22) newest code . There is no option in GUI to add/edit groups.

If I want assign user to the group, I have only 2 options:
1. empty field
2. daloRADIUS-Disabled-Users

How to add new groups?

I tried to find the module manually by specifying the action php file, but without success.

**Comment by filippolauria** [comment]
Dear @momuskk , look under the section **Management > Profiles**.
