### ISSUE TITLE
Search Users

### ISSUE THREAD

**Issue by rdesjardine** [lirantal/daloradius#526]
**Describe the bug**

The search field on Management -> Users -> Search Users does not return any results.

**To Reproduce**
Search any partial or full username.

**Expected behavior**
List of users matching the entered string.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Your Browser:  Firefox
 - daloRADIUS Version: [e.g. "cloned the master branch on May 27th"]
 - FreeRADIUS Version: 3

**Possible Solution**
Found that in the mng-search.php file the LEFT JOIN between radreply and userinfo was causing the issue.   Most of our users in the system don't have records in the radreply table.  

Changing the join on line 154 of mng-search.php to a RIGHT JOIN resolved the issue.

**Comment by filippolauria** [comment]
Dear @rdesjardine . The reported issue has been fixed. Thank you.
