### ISSUE TITLE
default web username and password

### ISSUE THREAD

**Issue by hoseini3** [lirantal/daloradius#529]
i have installed a daloradius by your guide. everything seems good and i hadn't any error during the installation but i can't login to daloradius Web Interface by default user and password that you mentioned in the guide. i changed the default password of administrator on the maria db but i can't login to the web. 

Database changed
MariaDB [raddb]> select * from operators;
+----+---------------+----------+-----------+----------+-------+------------+---------+--------+--------+--------+--------+------------+------------+-------+---------------------+---------------------+------------+---------------------+---------------+
| id | username      | password | firstname | lastname | title | department | company | phone1 | phone2 | email1 | email2 | messenger1 | messenger2 | notes | lastlogin           | creationdate        | creationby | updatedate          | updateby      |
+----+---------------+----------+-----------+----------+-------+------------+---------+--------+--------+--------+--------+------------+------------+-------+---------------------+---------------------+------------+---------------------+---------------+
|  6 | administrator | radius   |           |          |       |            |         |        |        |        |        |            |            |       | 2009-12-07 20:13:20 | 2009-12-07 20:12:33 | admin      | 2009-12-07 20:14:01 | administrator |
+----+---------------+----------+-----------+----------+-------+------------+---------+--------+--------+--------+--------+------------+------------+-------+---------------------+---------------------+------------+---------------------+---------------+
please tell me how can i login to web page by administrator and radius .

**Comment by hoseini3** [comment]
I got this error.
![Screenshot 2024-06-06 232551](https://github.com/lirantal/daloradius/assets/66909916/04d57dd6-5342-4fe9-a51f-f435f1ac045b)

**Comment by filippolauria** [comment]
Dear @hoseini3 , please read carefully this: https://github.com/lirantal/daloradius/wiki/Installing-daloRADIUS#testing-the-infrastructure

**Comment by rajaeem** [comment]
![Screenshot 2024-06-12 090014](https://github.com/lirantal/daloradius/assets/29551782/2a91f39b-9f33-41ca-a57d-956a963102ea)
![Screenshot 2024-06-12 090029](https://github.com/lirantal/daloradius/assets/29551782/faa17092-848f-4a3d-ab80-b270e75b96d1)

**Comment by Mezosoft5** [comment]
User Name And Password Is :
Username : administrator
Password : radius
