### ISSUE TITLE
Last connection attempts no show

### ISSUE THREAD

**Issue by fourluo** [lirantal/daloradius#53]
Last connection attempts no show, with all in sudden, it just keep stop at last 2 days record, not updating, but i can see there are some records in the database, kindda weird

**Comment by fourluo** [comment]
actually, not showing every 30th ,31st  's data of every month

**Comment by lirantal** [comment]
Enable the SQL debugger and check the queries being made. See if you can run them manually and if they are the problem or something else.

**Comment by fourluo** [comment]
there's nothing wrong with SQL, but i have already fix problem by modify rep-lastconnect.php

isset($_GET['startdate']) ? $startdate = $_GET['startdate'] : $startdate = date("Y-m-01");
	isset($_GET['enddate']) ? $enddate = $_GET['enddate'] : $enddate = date( "Y-m-01",mktime (0,0,0,date('n')+1,1,date('Y')));

**Comment by lirantal** [comment]
@fourluo does the problem exist in the current daloradius code of the master branch?
If so I'd be happy to merge a PR for this quick fix from you

**Comment by fourluo** [comment]
@lirantal yes, i confirm this bug exist in the current daloradius code of the master branch. I deployed daloradius on 2 VM, and they have same issue on certain days (every last 2 days of month). I appreciate u could fix that.

**Comment by fourluo** [comment]
@lirantal also u gonna have to insert the same code that i provided into rep-main.php. cause they have same issue .Thx for the reply

**Comment by lirantal** [comment]
Thanks I pushed the fix to master now https://github.com/lirantal/daloradius/commit/918b128e9b0fc4fc82d652c4808fd4f3ae420d23
