### ISSUE TITLE
daloradius is completely broken on Postgres.

### ISSUE THREAD

**Issue by anayrat** [lirantal/daloradius#530]
Hello,

Contrary to what is mentioned in readme, daloradius do not work on Postgres.

I tried to import the schema from this issue https://github.com/lirantal/daloradius/issues/169
Then, I have many errors : 

![image](https://github.com/lirantal/daloradius/assets/6862220/fc1395f6-e31a-410d-a1b4-37eff9777b82)

**Comment by filippolauria** [comment]
Dear @anayrat , you totally made a good point.

The readme should state something like this: "[..] Although DAL _might allow_ the use of different [database management systems](https://en.wikipedia.org/wiki/Database#Database_management_system) (DBMSs) (e.g., MariaDB, MySQL, PostgreSQL, SQLite, MsSQL, etc.), it is important to note that **daloRADIUS has been fully tested only on the [MariaDB](https://mariadb.org/) DBMS**. Therefore, **the use of other DBMSs is not recommended**. [..]".
