### ISSUE TITLE
Default Username and Password doesn't match

### ISSUE THREAD

**Issue by Carlos-strong** [lirantal/daloradius#540]
Hello,
After complete the installation, Im not abble to connect wit the defaut credentials. 

Need help. Thanks

**Comment by filippolauria** [comment]
@Carlos-strong  at the end of the quick installation procedure, random credentials to be used for the operator's first login are generated.

**Comment by p2v-4u** [comment]
@Carlos-strong 
check RADIUS Management application at port :8000 and use the following default credentials:

Username: administrator
Password: radius

More details is here
https://github.com/lirantal/daloradius/wiki/Installing-daloRADIUS#testing-the-infrastructure

**Comment by RostKost** [comment]
@Carlos-strong
Pls check RADIUS Management application at port :8000 and use the following default credentials:

Username: administrator
Password: radius

More details is here
https://github.com/lirantal/daloradius/wiki/Installing-daloRADIUS#testing-the-infrastructure

**Comment by Carlos-strong** [comment]
Hello,
Thank for your reply. But after installation, the random credentials is not generated. Or where I suppose to get it?. And also, when I use my IP:8000, the login page not display. 
Thank.

**Comment by Carlos-strong** [comment]
its ok now. Just add port 8000.

Thanks for help.
