### ISSUE TITLE
Simultaneous-Use login

### ISSUE THREAD

**Issue by tomoxwell** [lirantal/daloradius#57]
Hi 
please elaborate on how to setup Simultaneous-Use login so that users are limited to the number of loggins.  I am using a pfsense captive portal which is not among the listed vendors. Which vendor exactly has the feature?

**Comment by lirantal** [comment]
You just need to specify it as a check attribute.
See here for more details: https://github.com/FreeRADIUS/www.freeradius.org/blob/master/radiusd/doc/Simultaneous-Use

**Comment by tomoxwell** [comment]
Much appreciated. Thanks
