### ISSUE TITLE
Bug in mng-del.php

### ISSUE THREAD

**Issue by Seazonx** [lirantal/daloradius#59]
Line 157
which is
`list($userSessions,$acctStartTime) = preg_split('\|\|', $value);`
should be
`list($userSessions,$acctStartTime) = preg_split('/\\|\\|/', $value);`

**Comment by Seazonx** [comment]
OK, done...  A 3-Day-bug-troubled user's first Pull Request...  haha

**Comment by lirantal** [comment]
Awesome, thank you! ;-)
