### ISSUE TITLE
Problem with Users Accounting

### ISSUE THREAD

**Issue by leonardopc1991** [lirantal/daloradius#67]
Good afternoon, I have a problem, I have clients with PPPoE sessions and I create the users in FreeRadius with DaloRadius, what happens is that before going to version 3 of FreeRadius a history of the client's login was saved as well as the total consumption of it, but now no longer, have any solution for that ?.

**Comment by MiguelVis** [comment]
That's not a problem with Daloradius. You must configure FreeRadius 3 for that. It seems something related with the radacct table and the MySQL module. Take into account that FreeRadius 3 configuration has changed a lot, and you must adapt your old FreeRadius 2 configuration to the new requirements. It's not directly compatible.

**Comment by MiguelVis** [comment]
Closed because it's related to FreeRadius accounting configuration.
