### ISSUE TITLE
PHP Fatal error:  Call to undefined function session_start() in checklogin.php line 27

### ISSUE THREAD

**Issue by Strykar** [lirantal/daloradius#7]
Running Apache 2.4 with PHP version 5.6.24 on FreeBSD 10.2
PHP is working when tested with `<?php phpinfo(); ?>`

index.php loads as a blank page and apache error log shows:

`[Sat Aug 06 20:56:52.608468 2016] [:error] [pid 87226] [client 1.2.3.4:14883] PHP Fatal error:  Call to undefined function session_start() in /usr/local/www/daloradius-0.9-9/library/checklogin.php on line 27`

login.php loads but trying to login with the default username and password also gives a blank page with apache logging:
`
[Sat Aug 06 21:06:17.046399 2016] [:error] [pid 87225] [client 1.2.3.4:15859] PHP Fatal error:  Call to undefined function session_id() in /usr/local/www/daloradius-0.9-9/dologin.php on line 36, referer: http://my.host.name/radius/login.php`

PHP warnings in apache error log:
```
PHP Warning:  PHP Startup: gd: Unable to initialize module\nModule compiled with build ID=API20131226,NTS,debug\nPHP    compiled with build ID=API20131226,NTS\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/20131226/db.so' - Cannot open &quot;/usr/local/lib/php/20131226/db.so&quot; in Unknown on line 0
PHP Warning:  PHP Startup: session: Unable to initialize module\nModule compiled with build ID=API20131226,NTS,debug\nPHP    compiled with build ID=API20131226,NTS\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: xml: Unable to initialize module\nModule compiled with build ID=API20131226,NTS,debug\nPHP    compiled with build ID=API20131226,NTS\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: gd: Unable to initialize module\nModule compiled with build ID=API20131226,NTS,debug\nPHP    compiled with build ID=API20131226,NTS\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: zlib: Unable to initialize module\nModule compiled with build ID=API20131226,NTS,debug\nPHP    compiled with build ID=API20131226,NTS\nThese options need to match\n in Unknown on line 0
PHP Warning:  Module 'mysql' already loaded in Unknown on line 0
```

```
 % ls /usr/local/lib/php/20131226
total 968
drwxr-xr-x  2 root  wheel   512B Aug  6 21:25 ./
drwxr-xr-x  5 root  wheel   512B Aug  6 20:47 ../
-r--r--r--  1 root  wheel   510K Aug  6 21:25 gd.so
-r--r--r--  1 root  wheel    48K Jul 28 09:08 mysql.so
-r--r--r--  1 root  wheel   134K Jul 28 07:47 mysqli.so
-r--r--r--  1 root  wheel   112K Aug  6 21:25 session.so
-r--r--r--  1 root  wheel    64K Aug  6 21:25 xml.so
-r--r--r--  1 root  wheel    47K Aug  6 21:25 zlib.so
```

**Comment by lirantal** [comment]
@Strykar 
Seems like it's not just daloRADIUS but other PHP extensions are having issues to load up.
I would also suggest that you clone the `master` branch here from GitHub and try to work with that instead of the older packages on SourceForge.

**Comment by lirantal** [comment]
Closing this issue, no response and no issues as far as I can see on the PHP7 thread.
