### ISSUE TITLE
Enginx website address.

### ISSUE THREAD

**Issue by MiguelVis** [lirantal/daloradius#81]
Hi @lirantal .

There are some places in daloRADIUS with links to a website not available now: [Enginx](http://www.enginx.com/).

Please, tell me what to do with this issue (another website address, perhaps?).

Thanks.

**Comment by lirantal** [comment]
Good point.
A different website indeed. Let me think about it for a second and get back to you.

**Comment by lirantal** [comment]
@MiguelVis:

(1) Where it says in the header "by Enginx" let's update to "by Liran Tal" with a link to https://github.com/lirantal/daloradius
(2) Where it says in the footer "Copyright of Enginx and Liran Tal" let's make a change where `Enginx` is not a link to anywhere, and instead `Liran Tal` is a link to https://github.com/lirantal/daloradius

Wherever else it says "by Enginx" we can follow (1).
Makes sense?

**Comment by MiguelVis** [comment]
@lirantal 

Done with #83.
