### ISSUE TITLE
Missing DB.php

### ISSUE THREAD

**Issue by aras-4u** [lirantal/daloradius#82]
Hello,

i tried to use this project but i have some warning : 

Warning: include_once(): Failed opening 'DB.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/daloradius/library/opendb.php on line 84

Fatal error: Uncaught Error: Class 'DB' not found in /var/www/html/daloradius/library/opendb.php:86 Stack trace: #0 /var/www/html/daloradius/dologin.php(49): include() #1 {main} thrown in /var/www/html/daloradius/library/opendb.php on line 86

Regards,

Aras

**Comment by MiguelVis** [comment]
daloRADIUS needs the PEAR DB package, in order to use the database. Please, install it with:

`pear install DB`

It's something asked on and off, so I will reflect this in the documentation asap.

**Comment by lirantal** [comment]
thanks @MiguelVis, agree! we see it all the time

**Comment by aras-4u** [comment]
Thanks,

Regards
