### ISSUE TITLE
daloRADIUS Install Requirements

### ISSUE THREAD

**Issue by lirantal** [lirantal/daloradius#87]
# Requirements

  * Apache.
 * PHP v5 or higher.
 * MySQL v4.1 or higher.
 * [PEAR](https://pear.php.net/) PHP extension.
 * PEAR package DB in order to access the database. To install it, execute at the command line:
   ```
   pear install DB
   ```
 * PEAR packages Mail and Mail_Mime to send notifications by email. To install them, execute at the command line:
   ```
   pear install -a Mail
   pear install -a Mail_Mime
   ```

 More details about installation and requirements can be found if needed on the (maybe very old) files:

  * INSTALL
 * INSTALL.openSUSE
 * INSTALL.quick
 * INSTALL.win
 * FAQS

**Comment by siliconhippy** [comment]
Can daloRADIUS support *wired* clients behind firewalls ( i.e., with private IP only) via say reverse SSH ?

**Comment by lirantal** [comment]
daloRADIUS doesn't really care as long as it gets the record/sessions handled by something like FreeRADIUS that will manage all of this and keep the DB up to date

**Comment by siliconhippy** [comment]
Thanks for the prompt response. So unlike some online hype, daloRADIUS is alive and well 😎

Since I am a noob, can you give me a link or two that explain how I might set up say a PAM module on a minimal Linux distro like discourse.coreelec.org ( it has Entware package manager so PAM/RADIUS packages can be installed); then communicate behind firewall with a public server VPS running RADIUS server?

Essentially I am looking to authenticate many such home based TV boxes so that I can remotely log into the RADIUS server and manually configure a small database of these boxes with userID /password plus predefined permissions to run/shut various applications on each tv box.

I looked at below but it doesn't tell me about the NATed situation, or how to set up some minimal permissions per client:

https://www.howtoforge.com/configuring-ssh-to-use-freeradius-and-wikid-for-two-factor-authentication


As you might know, CoreELEC and other Kodi JeOSes run on TV boxes more efficiently than the original Android OS, and have become very popular, including on RPi boards as well !

**Comment by lirantal** [comment]
I don't really have a link to share but I can say that this is mostly a FreeRADIUS configuration thing so I suggest focusing the search there to enable this capability. You can always jump on the mailing list and ask as well.

**Comment by frauhottelmann** [comment]
pear DB is appearently deprecated:

> This package has been superseded, but is still maintained for bugs and security fixes. Use MDB2 instead.

https://pear.php.net/package/DB/redirected

I don't know anything about pear. Can we move to the new package?

**Comment by MiguelVis** [comment]
> pear DB is appearently deprecated:
> 
> > This package has been superseded, but is still maintained for bugs and security fixes. Use MDB2 instead.
> 
> https://pear.php.net/package/DB/redirected
> 
> I don't know anything about pear. Can we move to the new package?

It seems DB is more regularly maintained than MDB2 - current releases:

DB:

> 1.9.3 (stable) was released on 2018-12-05 by ashnazg (Changelog)

MDB2:

> 2.5.0b5 (beta) was released on 2012-10-29 by danielc (Changelog)
> 2.4.1 (stable) was released on 2007-05-03 (Changelog)

I continue with DB without any apparent problem.

**Comment by frauhottelmann** [comment]
I was thinking the same :smiley:

**Comment by siliconhippy** [comment]
Lirantal,

Can daloRadius be installed in a cloud server ( AWS, Google, Azure) so it
can manage remote devices in different locations , i.e., not in the same
LAN?

Would this require an openvpn setup in the cloud and an openvpn client on
each device?

Can you please provide any tutorials/links to such a remote setup with
freeRADIUS AAA integrated?

Cheers 😄
Shippy.

**Comment by lirantal** [comment]
thanks @frauhottelmann. @MiguelVis do you think you can push a PR to move to DB? 

> Can daloRadius be installed in a cloud server ( AWS, Google, Azure) so it
can manage remote devices in different locations , i.e., not in the same
LAN?
@siliconhippy yes, you can install daloRADIUS in the cloud. perhaps open this question in a new issue to not hijack this one and allow others to easily find it.

**Comment by MiguelVis** [comment]
> @MiguelVis do you think you can push a PR to move to DB?

Hi @lirantal, no need for that, we are already linked to DB!

:)

**Comment by lirantal** [comment]
@MiguelVis you're the best ✨

**Comment by edimondi** [comment]
In Freeradius v3.0.20 these are the tables that need to be added to fr2-mysq-daloradius-and-freeradius.sql and than do **mysql -u root -p radius < contrib/db/fr2-mysql-daloradius-and-freeradius.sql** :   
  `acctupdatetime` datetime default NULL,
  `acctinterval` int(12) default NULL,
  `framedipv6address` varchar(15) collate utf8_unicode_ci NOT NULL default '',
  `framedipv6prefix` varchar(15) collate utf8_unicode_ci NOT NULL default '',
  `framedinterfaceid` varchar(15) collate utf8_unicode_ci NOT NULL default '',
  `delegatedipv6prefix` varchar(15) collate utf8_unicode_ci NOT NULL default '',

**Comment by lirantal** [comment]
perhaps it is worth to create a fr3-* mysql schema?
if you end up doing that @edimondi and submit a PR for this new FR3 version then I'm happy to merge it in.

**Comment by siliconhippy** [comment]
Hi again Liran,

Great to see all the github updates for Daloradius and the March 3
Operators features add.

I was looking at this nice DALORadius + FreeRadius set up description:

https://www.youtube.com/watch?v=JffiXdMFkOc

I will ask the same question as in my comment, to hear from the horse's
mouth😋:

1. Can I use this to enable/disable apps on a device (Kodi, VLC), say,
based on a user list with admin updated app permissions in a database? Will
opening/closing device ports be involved ? 2. Can NAS Server + MySQL+
Freeradius+ GUI be set up in the cloud ?
(I guess the answer here is yes, from your earlier answer in 2019 email
below.) 3. Does device traffic pass through NAS or is NAS just a
permissions gateway?

Here I am wondering: if device traffic must pass through NAS, for #1, then
maybe the NAS Server should be on the device or at least within the local
network, to save on bandwidth streaming charges ?

Cheers 😂,
Shippy.
----
