### ISSUE TITLE
daloRADIUS version number

### ISSUE THREAD

**Issue by MiguelVis** [lirantal/daloradius#89]
@lirantal 

Maybe it's time to increment version number to reflect bug fixes or enhancements. What do you think?

It can be confusing to maintain the version number while we continue fixing issues and add enhancements.

See for example the now closed issue #88

**Comment by lirantal** [comment]
yeah definitely.
do you want to create a small PR to bump the version in the files/repo information from 0.9.9 to 1.0.0 and I'll then also upload that archive to sourceforge to be in par.

**Comment by MiguelVis** [comment]
Ok, I'm preparing a PR.

I need to do some changes in language files to get the version # from the configuration - instead of:

`lang/en.php:$l['all']['daloRADIUS'] = "daloRADIUS 0.9-9";`

Regarding the version #, do you agree with the semantic versioning?

ie 1.2,3:
- 1 = Major
- 2 = Minor
- 3 = Patch

Good to know for the future.

Thanks.

**Comment by MiguelVis** [comment]
Done with #92 

Any comments about this, please?

> Regarding the version #, do you agree with the semantic versioning?
> 
> ie 1.2,3:
> 
> 1 = Major
> 2 = Minor
> 3 = Patch
> Good to know for the future.

**Comment by lirantal** [comment]
That's perfect 👌

**Comment by MiguelVis** [comment]
Then, we have a new daloRADIUS version since 2011!

Thanks @lirantal

**Comment by lirantal** [comment]
@MiguelVis I uploaded the archive and released here: https://sourceforge.net/projects/daloradius/

**Comment by lirantal** [comment]
haha true awesome!!
