### ISSUE TITLE
Create an new Profile at Management section

### ISSUE THREAD

**Issue by yaigor5** [lirantal/daloradius#95]
Incorrect SQL syntax - no table name present:
INSERT INTO (id...

![2019-03-24_164447](https://user-images.githubusercontent.com/48884281/54880580-b43fb380-4e4e-11e9-8a65-156660de2b0b.jpg)

**Comment by MiguelVis** [comment]
@yaigor5 

I have reproduced the error by leaving empty the field `Target` in an attribute when adding a profile.

Fixed with #96 in order to detect the issue and show an error message:

> Failed adding profile name [MaketRTU] - no attributes where provided by user
